CREATE OR REPLACE TRIGGER TR_ACCN_AIU_FLAT
AFTER INSERT OR UPDATE ON ACCN
FOR EACH ROW
BEGIN
	IF :NEW.ACCN_NUMBER != :OLD.ACCN_NUMBER THEN
		UPDATE FLAT SET 
			STALE_FLAG = 1,
			LASTUSER = SYS_CONTEXT('USERENV', 'SESSION_USER'),
			LASTDATE = SYSDATE
		WHERE ACCN_ID = :NEW.TRANSACTION_ID;
END IF;
END;



CREATE OR REPLACE TRIGGER trg_accn_datecheck
before INSERT or update ON accn
FOR EACH ROW
	declare status varchar2(255);
BEGIN
	status:=is_iso8601(:NEW.RECEIVED_DATE);
    IF status != 'valid' THEN
        raise_application_error(-20001,'RECEIVED_DATE: ' || status);
    END IF;
END;
/
sho err
