CREATE OR REPLACE TRIGGER TR_ACCN_AIU_FLAT
AFTER INSERT OR UPDATE ON ACCN
FOR EACH ROW
BEGIN
	IF :NEW.ACCN_NUMBER != :OLD.ACCN_NUMBER THEN
		UPDATE FLAT SET 
			STALE_FLAG = 1,
			LASTUSER = SYS_CONTEXT('USERENV', 'SESSION_USER'),
			LASTDATE = SYSDATE
		WHERE ACCN_ID = :NEW.TRANSACTION_ID;
END IF;
END;
