CREATE OR REPLACE TRIGGER TR_ALA_PLANT_IMAGING_SQ
BEFORE INSERT ON ALA_PLANT_IMAGING
FOR EACH ROW
BEGIN
    IF :NEW.IMAGE_ID IS NULL THEN
	    SELECT SQ_ALA_IMAGE_ID.NEXTVAL
		INTO :NEW.IMAGE_ID 
		FROM DUAL;
    END IF;
END;
