CREATE OR REPLACE TRIGGER TR_COLLOBJCONTHIST_AD
AFTER DELETE ON COLL_OBJ_CONT_HIST
FOR EACH ROW
BEGIN
    DELETE FROM container 
    WHERE container_id = :OLD.container_id;
END;

CREATE OR REPLACE TRIGGER TR_COLLOBJ_OTHERIDNUM_SQ
BEFORE INSERT ON COLL_OBJ_OTHER_ID_NUM
FOR EACH ROW
BEGIN
    IF :NEW.COLL_OBJ_OTHER_ID_NUM_ID IS NULL THEN
    	SELECT SQ_COLL_OBJ_OTHER_ID_NUM_ID.NEXTVAL
		INTO :NEW.COLL_OBJ_OTHER_ID_NUM_ID
		FROM DUAL;
    END IF;
END;
