/*
    This UPDATE adds table bulkloader to the VPD, and generalizes bulkloader apps.
*/
-- MAKE SURE THERE ARE NO SALVEAGABLE DATA!!
-- email sent 27Jul2011

delete from bulkloader where collection_cde || '::' || institution_acronym not in (
	select collection_cde || '::' || institution_acronym from collection);
	
delete from bulkloader where enteredby not in (
	select agent_name from agent_name);	

delete from bulkloader where enteredby is null;

-- /MAKE SURE THERE ARE NO SALVEAGABLE DATA!!

alter table bulkloader add collection_id number;

update bulkloader set collection_id=(
	select collection_id from collection where 
		bulkloader.collection_cde=collection.collection_cde and
		bulkloader.institution_acronym=collection.institution_acronym
	);
	
alter table bulkloader modify collection_id number not null;


alter table bulkloader add entered_agent_id number;

update bulkloader set entered_agent_id=(select agent_id from agent_name where agent_name_type='login' and agent_name=enteredby);

alter table bulkloader modify entered_agent_id not null;


alter table bulkloader add enteredtobulkdate timestamp;

update bulkloader set enteredtobulkdate=systimestamp;

drop trigger BULK_NO_NULL_LOADED;

--select dbms_metadata.get_ddl('TABLE', 'BULKLOADER') from dual;
-- SELECT 'partition ' || institution_acronym || '_' || collection_cde || ' values (' || collection_id || '),' FROM collection;

CREATE TABLE bulk_temp AS SELECT * FROM bulkloader;

DROP TABLE bulkloader;

CREATE TABLE "UAM"."BULKLOADER" (
    "COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE,
	"LOADED" VARCHAR2(255),
	"ENTEREDBY" VARCHAR2(255),
	"CAT_NUM" VARCHAR2(20),
	"OTHER_ID_NUM_5" VARCHAR2(255),
	"OTHER_ID_NUM_TYPE_5" VARCHAR2(255),
	"OTHER_ID_NUM_1" VARCHAR2(255),
	"OTHER_ID_NUM_TYPE_1" VARCHAR2(255),
	"ACCN" VARCHAR2(30),
	"TAXON_NAME" VARCHAR2(255),
	"NATURE_OF_ID" VARCHAR2(255),
	"ID_MADE_BY_AGENT" VARCHAR2(255),
	"MADE_DATE" VARCHAR2(20),
	"IDENTIFICATION_REMARKS" VARCHAR2(4000),
	"VERBATIM_DATE" VARCHAR2(255),
	"BEGAN_DATE" VARCHAR2(20),
	"ENDED_DATE" VARCHAR2(20),
	"HIGHER_GEOG" VARCHAR2(255),
	"SPEC_LOCALITY" VARCHAR2(255),
	"VERBATIM_LOCALITY" VARCHAR2(255),
	"ORIG_LAT_LONG_UNITS" VARCHAR2(255),
	"DEC_LAT" VARCHAR2(255),
	"DEC_LONG" VARCHAR2(255),
	"LATDEG" VARCHAR2(20),
	"DEC_LAT_MIN" VARCHAR2(255),
	"LATMIN" VARCHAR2(255),
	"LATSEC" VARCHAR2(255),
	"LATDIR" VARCHAR2(50),
	"LONGDEG" VARCHAR2(20),
	"DEC_LONG_MIN" VARCHAR2(255),
	"LONGMIN" VARCHAR2(255),
	"LONGSEC" VARCHAR2(255),
	"LONGDIR" VARCHAR2(50),
	"DATUM" VARCHAR2(255),
	"LAT_LONG_REF_SOURCE" VARCHAR2(255),
	"MAX_ERROR_DISTANCE" VARCHAR2(255),
	"MAX_ERROR_UNITS" VARCHAR2(255),
	"GEOREFMETHOD" VARCHAR2(255),
	"DETERMINED_BY_AGENT" VARCHAR2(255),
	"DETERMINED_DATE" VARCHAR2(20),
	"LAT_LONG_REMARKS" VARCHAR2(4000),
	"VERIFICATIONSTATUS" VARCHAR2(255),
	"MAXIMUM_ELEVATION" VARCHAR2(20),
	"MINIMUM_ELEVATION" VARCHAR2(20),
	"ORIG_ELEV_UNITS" VARCHAR2(255),
	"LOCALITY_REMARKS" VARCHAR2(255),
	"HABITAT_DESC" VARCHAR2(255),
	"COLL_EVENT_REMARKS" VARCHAR2(255),
	"COLLECTOR_AGENT_1" VARCHAR2(255),
	"COLLECTOR_ROLE_1" VARCHAR2(255),
	"COLLECTOR_AGENT_2" VARCHAR2(255),
	"COLLECTOR_ROLE_2" VARCHAR2(255),
	"COLLECTOR_AGENT_3" VARCHAR2(255),
	"COLLECTOR_ROLE_3" VARCHAR2(255),
	"COLLECTOR_AGENT_4" VARCHAR2(255),
	"COLLECTOR_ROLE_4" VARCHAR2(50),
	"COLLECTOR_AGENT_5" VARCHAR2(255),
	"COLLECTOR_ROLE_5" VARCHAR2(255),
	"COLLECTOR_AGENT_6" VARCHAR2(255),
	"COLLECTOR_ROLE_6" VARCHAR2(255),
	"COLLECTOR_AGENT_7" VARCHAR2(255),
	"COLLECTOR_ROLE_7" VARCHAR2(255),
	"COLLECTOR_AGENT_8" VARCHAR2(255),
	"COLLECTOR_ROLE_8" VARCHAR2(255),
	"COLLECTION_CDE" VARCHAR2(5),
	"INSTITUTION_ACRONYM" VARCHAR2(50),
	"FLAGS" VARCHAR2(20),
	"COLL_OBJ_DISPOSITION" VARCHAR2(255),
	"CONDITION" VARCHAR2(255),
	"COLL_OBJECT_REMARKS" VARCHAR2(4000),
	"DISPOSITION_REMARKS" VARCHAR2(255),
	"OTHER_ID_NUM_2" VARCHAR2(255),
	"OTHER_ID_NUM_TYPE_2" VARCHAR2(255),
	"OTHER_ID_NUM_3" VARCHAR2(255),
	"OTHER_ID_NUM_TYPE_3" VARCHAR2(255),
	"OTHER_ID_NUM_4" VARCHAR2(255),
	"OTHER_ID_NUM_TYPE_4" VARCHAR2(255),
	"PART_NAME_1" VARCHAR2(255),
	"PART_CONDITION_1" VARCHAR2(255),
	"PART_BARCODE_1" VARCHAR2(50),
	"PART_CONTAINER_LABEL_1" VARCHAR2(50),
	"PART_LOT_COUNT_1" VARCHAR2(5),
	"PART_DISPOSITION_1" VARCHAR2(255),
	"PART_REMARK_1" VARCHAR2(255),
	"PART_NAME_2" VARCHAR2(255),
	"PART_CONDITION_2" VARCHAR2(255),
	"PART_BARCODE_2" VARCHAR2(50),
	"PART_CONTAINER_LABEL_2" VARCHAR2(50),
	"PART_LOT_COUNT_2" VARCHAR2(2),
	"PART_DISPOSITION_2" VARCHAR2(255),
	"PART_REMARK_2" VARCHAR2(255),
	"PART_NAME_3" VARCHAR2(255),
	"PART_CONDITION_3" VARCHAR2(255),
	"PART_BARCODE_3" VARCHAR2(50),
	"PART_CONTAINER_LABEL_3" VARCHAR2(50),
	"PART_LOT_COUNT_3" VARCHAR2(2),
	"PART_DISPOSITION_3" VARCHAR2(255),
	"PART_REMARK_3" VARCHAR2(255),
	"PART_NAME_4" VARCHAR2(255),
	"PART_CONDITION_4" VARCHAR2(255),
	"PART_BARCODE_4" VARCHAR2(50),
	"PART_CONTAINER_LABEL_4" VARCHAR2(50),
	"PART_LOT_COUNT_4" VARCHAR2(2),
	"PART_DISPOSITION_4" VARCHAR2(255),
	"PART_REMARK_4" VARCHAR2(255),
	"PART_NAME_5" VARCHAR2(255),
	"PART_CONDITION_5" VARCHAR2(255),
	"PART_BARCODE_5" VARCHAR2(50),
	"PART_CONTAINER_LABEL_5" VARCHAR2(50),
	"PART_LOT_COUNT_5" VARCHAR2(2),
	"PART_DISPOSITION_5" VARCHAR2(255),
	"PART_REMARK_5" VARCHAR2(255),
	"PART_NAME_6" VARCHAR2(255),
	"PART_CONDITION_6" VARCHAR2(255),
	"PART_BARCODE_6" VARCHAR2(50),
	"PART_CONTAINER_LABEL_6" VARCHAR2(50),
	"PART_LOT_COUNT_6" VARCHAR2(2),
	"PART_DISPOSITION_6" VARCHAR2(255),
	"PART_REMARK_6" VARCHAR2(255),
	"PART_NAME_7" VARCHAR2(255),
	"PART_CONDITION_7" VARCHAR2(255),
	"PART_BARCODE_7" VARCHAR2(50),
	"PART_CONTAINER_LABEL_7" VARCHAR2(50),
	"PART_LOT_COUNT_7" VARCHAR2(2),
	"PART_DISPOSITION_7" VARCHAR2(255),
	"PART_REMARK_7" VARCHAR2(255),
	"PART_NAME_8" VARCHAR2(255),
	"PART_CONDITION_8" VARCHAR2(255),
	"PART_BARCODE_8" VARCHAR2(50),
	"PART_CONTAINER_LABEL_8" VARCHAR2(50),
	"PART_LOT_COUNT_8" VARCHAR2(2),
	"PART_DISPOSITION_8" VARCHAR2(255),
	"PART_REMARK_8" VARCHAR2(255),
	"PART_NAME_9" VARCHAR2(255),
	"PART_CONDITION_9" VARCHAR2(255),
	"PART_BARCODE_9" VARCHAR2(50),
	"PART_CONTAINER_LABEL_9" VARCHAR2(50),
	"PART_LOT_COUNT_9" VARCHAR2(50),
	"PART_DISPOSITION_9" VARCHAR2(255),
	"PART_REMARK_9" VARCHAR2(255),
	"PART_NAME_10" VARCHAR2(255),
	"PART_CONDITION_10" VARCHAR2(255),
	"PART_BARCODE_10" VARCHAR2(50),
	"PART_CONTAINER_LABEL_10" VARCHAR2(50),
	"PART_LOT_COUNT_10" VARCHAR2(50),
	"PART_DISPOSITION_10" VARCHAR2(255),
	"PART_REMARK_10" VARCHAR2(255),
	"PART_NAME_11" VARCHAR2(255),
	"PART_CONDITION_11" VARCHAR2(255),
	"PART_BARCODE_11" VARCHAR2(50),
	"PART_CONTAINER_LABEL_11" VARCHAR2(50),
	"PART_LOT_COUNT_11" VARCHAR2(50),
	"PART_DISPOSITION_11" VARCHAR2(255),
	"PART_REMARK_11" VARCHAR2(255),
	"PART_NAME_12" VARCHAR2(255),
	"PART_CONDITION_12" VARCHAR2(255),
	"PART_BARCODE_12" VARCHAR2(50),
	"PART_CONTAINER_LABEL_12" VARCHAR2(50),
	"PART_LOT_COUNT_12" VARCHAR2(50),
	"PART_DISPOSITION_12" VARCHAR2(255),
	"PART_REMARK_12" VARCHAR2(255),
	"ATTRIBUTE_1" VARCHAR2(50),
	"ATTRIBUTE_VALUE_1" VARCHAR2(255),
	"ATTRIBUTE_UNITS_1" VARCHAR2(255),
	"ATTRIBUTE_REMARKS_1" VARCHAR2(255),
	"ATTRIBUTE_DATE_1" VARCHAR2(20),
	"ATTRIBUTE_DET_METH_1" VARCHAR2(50),
	"ATTRIBUTE_DETERMINER_1" VARCHAR2(255),
	"ATTRIBUTE_2" VARCHAR2(50),
	"ATTRIBUTE_VALUE_2" VARCHAR2(255),
	"ATTRIBUTE_UNITS_2" VARCHAR2(50),
	"ATTRIBUTE_REMARKS_2" VARCHAR2(255),
	"ATTRIBUTE_DATE_2" VARCHAR2(20),
	"ATTRIBUTE_DET_METH_2" VARCHAR2(50),
	"ATTRIBUTE_DETERMINER_2" VARCHAR2(255),
	"ATTRIBUTE_3" VARCHAR2(50),
	"ATTRIBUTE_VALUE_3" VARCHAR2(255),
	"ATTRIBUTE_UNITS_3" VARCHAR2(50),
	"ATTRIBUTE_REMARKS_3" VARCHAR2(255),
	"ATTRIBUTE_DATE_3" VARCHAR2(20),
	"ATTRIBUTE_DET_METH_3" VARCHAR2(50),
	"ATTRIBUTE_DETERMINER_3" VARCHAR2(255),
	"ATTRIBUTE_4" VARCHAR2(50),
	"ATTRIBUTE_VALUE_4" VARCHAR2(255),
	"ATTRIBUTE_UNITS_4" VARCHAR2(50),
	"ATTRIBUTE_REMARKS_4" VARCHAR2(255),
	"ATTRIBUTE_DATE_4" VARCHAR2(20),
	"ATTRIBUTE_DET_METH_4" VARCHAR2(50),
	"ATTRIBUTE_DETERMINER_4" VARCHAR2(255),
	"ATTRIBUTE_5" VARCHAR2(50),
	"ATTRIBUTE_VALUE_5" VARCHAR2(255),
	"ATTRIBUTE_UNITS_5" VARCHAR2(50),
	"ATTRIBUTE_REMARKS_5" VARCHAR2(255),
	"ATTRIBUTE_DATE_5" VARCHAR2(20),
	"ATTRIBUTE_DET_METH_5" VARCHAR2(50),
	"ATTRIBUTE_DETERMINER_5" VARCHAR2(255),
	"ATTRIBUTE_6" VARCHAR2(50),
	"ATTRIBUTE_VALUE_6" VARCHAR2(255),
	"ATTRIBUTE_UNITS_6" VARCHAR2(50),
	"ATTRIBUTE_REMARKS_6" VARCHAR2(255),
	"ATTRIBUTE_DATE_6" VARCHAR2(20),
	"ATTRIBUTE_DET_METH_6" VARCHAR2(50),
	"ATTRIBUTE_DETERMINER_6" VARCHAR2(255),
	"ATTRIBUTE_7" VARCHAR2(50),
	"ATTRIBUTE_VALUE_7" VARCHAR2(255),
	"ATTRIBUTE_UNITS_7" VARCHAR2(50),
	"ATTRIBUTE_REMARKS_7" VARCHAR2(255),
	"ATTRIBUTE_DATE_7" VARCHAR2(20),
	"ATTRIBUTE_DET_METH_7" VARCHAR2(50),
	"ATTRIBUTE_DETERMINER_7" VARCHAR2(255),
	"ATTRIBUTE_8" VARCHAR2(50),
	"ATTRIBUTE_VALUE_8" VARCHAR2(255),
	"ATTRIBUTE_UNITS_8" VARCHAR2(50),
	"ATTRIBUTE_REMARKS_8" VARCHAR2(255),
	"ATTRIBUTE_DATE_8" VARCHAR2(20),
	"ATTRIBUTE_DET_METH_8" VARCHAR2(50),
	"ATTRIBUTE_DETERMINER_8" VARCHAR2(255),
	"ATTRIBUTE_9" VARCHAR2(50),
	"ATTRIBUTE_VALUE_9" VARCHAR2(255),
	"ATTRIBUTE_UNITS_9" VARCHAR2(50),
	"ATTRIBUTE_REMARKS_9" VARCHAR2(255),
	"ATTRIBUTE_DATE_9" VARCHAR2(50),
	"ATTRIBUTE_DET_METH_9" VARCHAR2(50),
	"ATTRIBUTE_DETERMINER_9" VARCHAR2(255),
	"ATTRIBUTE_10" VARCHAR2(50),
	"ATTRIBUTE_VALUE_10" VARCHAR2(255),
	"ATTRIBUTE_UNITS_10" VARCHAR2(50),
	"ATTRIBUTE_REMARKS_10" VARCHAR2(255),
	"ATTRIBUTE_DATE_10" VARCHAR2(50),
	"ATTRIBUTE_DET_METH_10" VARCHAR2(50),
	"ATTRIBUTE_DETERMINER_10" VARCHAR2(255),
	"RELATIONSHIP" VARCHAR2(60),
	"RELATED_TO_NUMBER" VARCHAR2(60),
	"RELATED_TO_NUM_TYPE" VARCHAR2(255),
	"MIN_DEPTH" VARCHAR2(20),
	"MAX_DEPTH" VARCHAR2(20),
	"DEPTH_UNITS" VARCHAR2(30),
	"COLLECTING_METHOD" VARCHAR2(255),
	"COLLECTING_SOURCE" VARCHAR2(255),
	"COLL_OBJECT_HABITAT" VARCHAR2(255),
	"ASSOCIATED_SPECIES" VARCHAR2(4000),
	"LOCALITY_ID" VARCHAR2(20),
	"UTM_ZONE" VARCHAR2(3),
	"UTM_EW" VARCHAR2(60),
	"UTM_NS" VARCHAR2(60),
	"EXTENT" VARCHAR2(60),
	"GPSACCURACY" VARCHAR2(60),
	"GEOLOGY_ATTRIBUTE_1" VARCHAR2(255),
	"GEO_ATT_VALUE_1" VARCHAR2(255),
	"GEO_ATT_DETERMINER_1" VARCHAR2(255),
	"GEO_ATT_DETERMINED_DATE_1" VARCHAR2(255),
	"GEO_ATT_DETERMINED_METHOD_1" VARCHAR2(255),
	"GEO_ATT_REMARK_1" VARCHAR2(4000),
	"GEOLOGY_ATTRIBUTE_2" VARCHAR2(255),
	"GEO_ATT_VALUE_2" VARCHAR2(255),
	"GEO_ATT_DETERMINER_2" VARCHAR2(255),
	"GEO_ATT_DETERMINED_DATE_2" VARCHAR2(255),
	"GEO_ATT_DETERMINED_METHOD_2" VARCHAR2(255),
	"GEO_ATT_REMARK_2" VARCHAR2(4000),
	"GEOLOGY_ATTRIBUTE_3" VARCHAR2(255),
	"GEO_ATT_VALUE_3" VARCHAR2(255),
	"GEO_ATT_DETERMINER_3" VARCHAR2(255),
	"GEO_ATT_DETERMINED_DATE_3" VARCHAR2(255),
	"GEO_ATT_DETERMINED_METHOD_3" VARCHAR2(255),
	"GEO_ATT_REMARK_3" VARCHAR2(4000),
	"GEOLOGY_ATTRIBUTE_4" VARCHAR2(255),
	"GEO_ATT_VALUE_4" VARCHAR2(255),
	"GEO_ATT_DETERMINER_4" VARCHAR2(255),
	"GEO_ATT_DETERMINED_DATE_4" VARCHAR2(255),
	"GEO_ATT_DETERMINED_METHOD_4" VARCHAR2(255),
	"GEO_ATT_REMARK_4" VARCHAR2(4000),
	"GEOLOGY_ATTRIBUTE_5" VARCHAR2(255),
	"GEO_ATT_VALUE_5" VARCHAR2(255),
	"GEO_ATT_DETERMINER_5" VARCHAR2(255),
	"GEO_ATT_DETERMINED_DATE_5" VARCHAR2(255),
	"GEO_ATT_DETERMINED_METHOD_5" VARCHAR2(255),
	"GEO_ATT_REMARK_5" VARCHAR2(4000),
	"GEOLOGY_ATTRIBUTE_6" VARCHAR2(255),
	"GEO_ATT_VALUE_6" VARCHAR2(255),
	"GEO_ATT_DETERMINER_6" VARCHAR2(255),
	"GEO_ATT_DETERMINED_DATE_6" VARCHAR2(255),
	"GEO_ATT_DETERMINED_METHOD_6" VARCHAR2(255),
	"GEO_ATT_REMARK_6" VARCHAR2(4000),
	"COLLECTING_EVENT_ID" NUMBER,
	"COLLECTION_ID" NUMBER NOT NULL ENABLE,
	"ENTERED_AGENT_ID" NUMBER NOT NULL ENABLE,
	"ENTEREDTOBULKDATE" TIMESTAMP (6)
)
  TABLESPACE UAM_DAT_1
  PARTITION BY LIST (collection_id) ( 
    partition UAM_Mamm values (1),
    partition UAM_Bird values (2),
    partition UAM_Herp values (3),
    partition UAM_Ento values (4),
    partition UAM_Herb values (6),
    partition NBSB_Bird values (7),
    partition UAM_Fish values (10),
    partition UAM_Inv values (11),
    partition KWP_Ento values (12),
    partition UAMObs_Mamm values (13),
    partition MSB_Mamm values (14),
    partition DGR_Ento values (15),
    partition DGR_Bird values (16),
    partition DGR_Mamm values (17),
    partition DGR_Herp values (18),
    partition DGR_Fish values (19),
    partition MSB_Bird values (20),
    partition UAM_ES values (21),
    partition WNMU_Bird values (22),
    partition WNMU_Fish values (23),
    partition WNMU_Mamm values (24),
    partition PSU_Mamm values (25),
    partition CRCM_Bird values (26),
    partition MSB_Para values (27),
    partition MVZ_Mamm values (28),
    partition MVZ_Bird values (29),
    partition MVZ_Herp values (30),
    partition MVZ_Egg values (31),
    partition MVZ_Hild values (32),
    partition MVZ_Img values (33),
    partition MVZ_Page values (34),
    partition MVZObs_Bird values (35),
    partition MVZObs_Herp values (36),
    partition MVZObs_Mamm values (37),
    partition UAM_Art values (39),
    partition UAMb_Herb values (40),
    partition MSBObs_Mamm values (41),
    partition UAMObs_Fish values (42),
    partition DMNS_Bird values (43),
    partition MSB_Herp values (44),
    partition DMNS_Mamm values (45),
    partition KNWR_Ento values (46),
    partition KNWR_Herb values (47),
    partition HWML_Para values (48),
    partition MSB_Host values (49)
  );
	
    INSERT INTO bulkloader (SELECT * FROM bulk_temp);

	DROP INDEX pk_bulkloader;
	
	CREATE UNIQUE INDEX pk_bulkloader ON bulkloader(collection_object_id) TABLESPACE uam_idx_1;
	
	ALTER TABLE bulkloader DROP CONSTRAINT fk_bl_collectionid;
	
	ALTER TABLE bulkloader ADD CONSTRAINT fk_bl_collectionid FOREIGN KEY (collection_id) REFERENCES collection(collection_id);
	
	ALTER TABLE bulkloader DROP CONSTRAINT fk_bl_enteredbyid;
	
	ALTER TABLE bulkloader ADD CONSTRAINT fk_bl_enteredbyid FOREIGN KEY (entered_agent_id) REFERENCES agent(agent_id);
	

CREATE
OR REPLACE TRIGGER ti_bulk_cid before
INSERT
OR
UPDATE
ON bulkloader FOR EACH ROW DECLARE cid INTEGER;

ismgr INTEGER;
c     INTEGER;
BEGIN
        SELECT COUNT(*)
        INTO   ismgr
        FROM   dba_role_privs
        WHERE  UPPER(grantee) = Sys_context ('USERENV', 'SESSION_USER')
        AND    granted_role   = 'MANAGE_COLLECTION';
        
        IF :new.collection_id IS NULL THEN
                SELECT NVL(collection_id, 0)
                INTO   :NEW.collection_id
                FROM   collection
                WHERE  collection_cde      = :new.collection_cde
                AND    institution_acronym = :new.institution_acronym;
                
                IF ( :NEW.collection_id = 0 ) THEN
                        Raise_application_error(-20002, 
                            'invalid collection_cde (' || :new.collection_cde || ') and/or institution_acronym (' || :new.institution_acronym || ')');
                END IF;
        END IF;
        IF :new.collection_object_id IS NULL THEN
                SELECT bulkloader_pkey.nextval
                INTO   :NEW.collection_object_id
                FROM   dual;
        
        END IF;
        IF :NEW.entered_agent_id IS NULL THEN
                SELECT NVL(agent_id, 0)
                INTO   :NEW.entered_agent_id
                FROM   agent_name
                WHERE  agent_name_type = 'login'
                AND    agent_name      = :NEW.enteredby;
                
                IF ( :NEW.entered_agent_id = 0 ) THEN
                        Raise_application_error(-20002, 'enteredby ('
                        || :NEW.enteredby
                        || ') is invalid');
                END IF;
        END IF;
        IF inserting THEN
                SELECT systimestamp
                INTO   :NEW.enteredtobulkdate
                FROM   dual;
                
                IF ismgr                      = 0
                        AND :NEW.loaded IS NULL THEN
                        Raise_application_error(-20002, 'You may not insert records with loaded=NULL.' );
                END IF;
        END IF;
        IF updating THEN
                IF :NEW.enteredtobulkdate != :OLD.enteredtobulkdate THEN
                        Raise_application_error(-20002, 'You may not change enteredtobulkdate');
                END IF;
                IF :NEW.enteredby != :OLD.enteredby THEN
                        Raise_application_error(-20002, 'You may not change enteredby');
                END IF;
                IF ismgr                     = 0 THEN
                        IF :NEW.loaded IS NULL THEN
                                Raise_application_error(-20002, 'You may not NULL loaded, and you may not update records with loaded=NULL.' );
                        END IF;
                        SELECT COUNT(*)
                        INTO   c
                        FROM   dual
                        WHERE  UPPER(:NEW.enteredby) = Sys_context ('USERENV', 'SESSION_USER');
                        
                        IF c = 0 THEN
                                Raise_application_error(-20001, 'You may only update your own records.');
                        END IF;
                END IF;
        END IF;
END;
/
show err




-- SELECT column_name FROM USEr_tab_cols WHERE table_name='BULKLOADER' AND column_name NOT IN (SELECT column_name FROM USEr_tab_cols WHERE table_name='BULKLOADER_DELETES')

ALTER TABLE bulkloader_deletes ADD collection_id NUMBER;
ALTER TABLE bulkloader_deletes ADD entered_agent_id NUMBER;
ALTER TABLE bulkloader_deletes ADD enteredtobulkdate TIMEstamp;





CREATE OR REPLACE TRIGGER TD_BULKLOADER
AFTER DELETE ON BULKLOADER
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
-- create a table to hold deleted records with:
-- drop table bulkloader_deletes;
-- create table bulkloader_deletes as select * from bulkloader;
-- delete from bulkloader_deletes;
-- build the guts of this trigger with:
-- select column_name||',' as cname from user_tab_cols where table_name = 'BULKLOADER' order by INTERNAL_COLUMN_ID;
-- paste in after insert into bulkloader_deletes ("
-- then remove last comma and ) VALUES (" then
-- select ':old.' || column_name ||',' as cname from user_tab_cols where table_name = 'BULKLOADER' order by INTERNAL_COLUMN_ID;
-- then remove last comma again
DECLARE NOTHING INTEGER;
BEGIN
    INSERT INTO bulkloader_deletes (
        COLLECTION_OBJECT_ID,
        LOADED,
        ENTEREDBY,
        CAT_NUM,
        OTHER_ID_NUM_5,
        OTHER_ID_NUM_TYPE_5,
        OTHER_ID_NUM_1,
        OTHER_ID_NUM_TYPE_1,
        ACCN,
        TAXON_NAME,
        NATURE_OF_ID,
        ID_MADE_BY_AGENT,
        MADE_DATE,
        IDENTIFICATION_REMARKS,
        VERBATIM_DATE,
        BEGAN_DATE,
        ENDED_DATE,
        HIGHER_GEOG,
        SPEC_LOCALITY,
        VERBATIM_LOCALITY,
        ORIG_LAT_LONG_UNITS,
        DEC_LAT,
        DEC_LONG,
        LATDEG,
        DEC_LAT_MIN,
        LATMIN,
        LATSEC,
        LATDIR,
        LONGDEG,
        DEC_LONG_MIN,
        LONGMIN,
        LONGSEC,
        LONGDIR,
        DATUM,
        LAT_LONG_REF_SOURCE,
        MAX_ERROR_DISTANCE,
        MAX_ERROR_UNITS,
        GEOREFMETHOD,
        DETERMINED_BY_AGENT,
        DETERMINED_DATE,
        LAT_LONG_REMARKS,
        VERIFICATIONSTATUS,
        MAXIMUM_ELEVATION,
        MINIMUM_ELEVATION,
        ORIG_ELEV_UNITS,
        LOCALITY_REMARKS,
        HABITAT_DESC,
        COLL_EVENT_REMARKS,
        COLLECTOR_AGENT_1,
        COLLECTOR_ROLE_1,
        COLLECTOR_AGENT_2,
        COLLECTOR_ROLE_2,
        COLLECTOR_AGENT_3,
        COLLECTOR_ROLE_3,
        COLLECTOR_AGENT_4,
        COLLECTOR_ROLE_4,
        COLLECTOR_AGENT_5,
        COLLECTOR_ROLE_5,
        COLLECTOR_AGENT_6,
        COLLECTOR_ROLE_6,
        COLLECTOR_AGENT_7,
        COLLECTOR_ROLE_7,
        COLLECTOR_AGENT_8,
        COLLECTOR_ROLE_8,
        COLLECTION_CDE,
        INSTITUTION_ACRONYM,
        FLAGS,
        COLL_OBJ_DISPOSITION,
        CONDITION,
        COLL_OBJECT_REMARKS,
        DISPOSITION_REMARKS,
        OTHER_ID_NUM_2,
        OTHER_ID_NUM_TYPE_2,
        OTHER_ID_NUM_3,
        OTHER_ID_NUM_TYPE_3,
        OTHER_ID_NUM_4,
        OTHER_ID_NUM_TYPE_4,
        PART_NAME_1,
        PART_CONDITION_1,
        PART_BARCODE_1,
        PART_CONTAINER_LABEL_1,
        PART_LOT_COUNT_1,
        PART_DISPOSITION_1,
        PART_REMARK_1,
        PART_NAME_2,
        PART_CONDITION_2,
        PART_BARCODE_2,
        PART_CONTAINER_LABEL_2,
        PART_LOT_COUNT_2,
        PART_DISPOSITION_2,
        PART_REMARK_2,
        PART_NAME_3,
        PART_CONDITION_3,
        PART_BARCODE_3,
        PART_CONTAINER_LABEL_3,
        PART_LOT_COUNT_3,
        PART_DISPOSITION_3,
        PART_REMARK_3,
        PART_NAME_4,
        PART_CONDITION_4,
        PART_BARCODE_4,
        PART_CONTAINER_LABEL_4,
        PART_LOT_COUNT_4,
        PART_DISPOSITION_4,
        PART_REMARK_4,
        PART_NAME_5,
        PART_CONDITION_5,
        PART_BARCODE_5,
        PART_CONTAINER_LABEL_5,
        PART_LOT_COUNT_5,
        PART_DISPOSITION_5,
        PART_REMARK_5,
        PART_NAME_6,
        PART_CONDITION_6,
        PART_BARCODE_6,
        PART_CONTAINER_LABEL_6,
        PART_LOT_COUNT_6,
        PART_DISPOSITION_6,
        PART_REMARK_6,
        PART_NAME_7,
        PART_CONDITION_7,
        PART_BARCODE_7,
        PART_CONTAINER_LABEL_7,
        PART_LOT_COUNT_7,
        PART_DISPOSITION_7,
        PART_REMARK_7,
        PART_NAME_8,
        PART_CONDITION_8,
        PART_BARCODE_8,
        PART_CONTAINER_LABEL_8,
        PART_LOT_COUNT_8,
        PART_DISPOSITION_8,
        PART_REMARK_8,
        PART_NAME_9,
        PART_CONDITION_9,
        PART_BARCODE_9,
        PART_CONTAINER_LABEL_9,
        PART_LOT_COUNT_9,
        PART_DISPOSITION_9,
        PART_REMARK_9,
        PART_NAME_10,
        PART_CONDITION_10,
        PART_BARCODE_10,
        PART_CONTAINER_LABEL_10,
        PART_LOT_COUNT_10,
        PART_DISPOSITION_10,
        PART_REMARK_10,
        PART_NAME_11,
        PART_CONDITION_11,
        PART_BARCODE_11,
        PART_CONTAINER_LABEL_11,
        PART_LOT_COUNT_11,
        PART_DISPOSITION_11,
        PART_REMARK_11,
        PART_NAME_12,
        PART_CONDITION_12,
        PART_BARCODE_12,
        PART_CONTAINER_LABEL_12,
        PART_LOT_COUNT_12,
        PART_DISPOSITION_12,
        PART_REMARK_12,
        ATTRIBUTE_1,
        ATTRIBUTE_VALUE_1,
        ATTRIBUTE_UNITS_1,
        ATTRIBUTE_REMARKS_1,
        ATTRIBUTE_DATE_1,
        ATTRIBUTE_DET_METH_1,
        ATTRIBUTE_DETERMINER_1,
        ATTRIBUTE_2,
        ATTRIBUTE_VALUE_2,
        ATTRIBUTE_UNITS_2,
        ATTRIBUTE_REMARKS_2,
        ATTRIBUTE_DATE_2,
        ATTRIBUTE_DET_METH_2,
        ATTRIBUTE_DETERMINER_2,
        ATTRIBUTE_3,
        ATTRIBUTE_VALUE_3,
        ATTRIBUTE_UNITS_3,
        ATTRIBUTE_REMARKS_3,
        ATTRIBUTE_DATE_3,
        ATTRIBUTE_DET_METH_3,
        ATTRIBUTE_DETERMINER_3,
        ATTRIBUTE_4,
        ATTRIBUTE_VALUE_4,
        ATTRIBUTE_UNITS_4,
        ATTRIBUTE_REMARKS_4,
        ATTRIBUTE_DATE_4,
        ATTRIBUTE_DET_METH_4,
        ATTRIBUTE_DETERMINER_4,
        ATTRIBUTE_5,
        ATTRIBUTE_VALUE_5,
        ATTRIBUTE_UNITS_5,
        ATTRIBUTE_REMARKS_5,
        ATTRIBUTE_DATE_5,
        ATTRIBUTE_DET_METH_5,
        ATTRIBUTE_DETERMINER_5,
        ATTRIBUTE_6,
        ATTRIBUTE_VALUE_6,
        ATTRIBUTE_UNITS_6,
        ATTRIBUTE_REMARKS_6,
        ATTRIBUTE_DATE_6,
        ATTRIBUTE_DET_METH_6,
        ATTRIBUTE_DETERMINER_6,
        ATTRIBUTE_7,
        ATTRIBUTE_VALUE_7,
        ATTRIBUTE_UNITS_7,
        ATTRIBUTE_REMARKS_7,
        ATTRIBUTE_DATE_7,
        ATTRIBUTE_DET_METH_7,
        ATTRIBUTE_DETERMINER_7,
        ATTRIBUTE_8,
        ATTRIBUTE_VALUE_8,
        ATTRIBUTE_UNITS_8,
        ATTRIBUTE_REMARKS_8,
        ATTRIBUTE_DATE_8,
        ATTRIBUTE_DET_METH_8,
        ATTRIBUTE_DETERMINER_8,
        ATTRIBUTE_9,
        ATTRIBUTE_VALUE_9,
        ATTRIBUTE_UNITS_9,
        ATTRIBUTE_REMARKS_9,
        ATTRIBUTE_DATE_9,
        ATTRIBUTE_DET_METH_9,
        ATTRIBUTE_DETERMINER_9,
        ATTRIBUTE_10,
        ATTRIBUTE_VALUE_10,
        ATTRIBUTE_UNITS_10,
        ATTRIBUTE_REMARKS_10,
        ATTRIBUTE_DATE_10,
        ATTRIBUTE_DET_METH_10,
        ATTRIBUTE_DETERMINER_10,
        RELATIONSHIP,
        RELATED_TO_NUMBER,
        RELATED_TO_NUM_TYPE,
        MIN_DEPTH,
        MAX_DEPTH,
        DEPTH_UNITS,
        COLLECTING_METHOD,
        COLLECTING_SOURCE,
        COLL_OBJECT_HABITAT,
        ASSOCIATED_SPECIES,
        LOCALITY_ID,
        UTM_ZONE,
        UTM_EW,
        UTM_NS,
        EXTENT,
        GPSACCURACY,
        GEOLOGY_ATTRIBUTE_1,
        GEO_ATT_VALUE_1,
        GEO_ATT_DETERMINER_1,
        GEO_ATT_DETERMINED_DATE_1,
        GEO_ATT_DETERMINED_METHOD_1,
        GEO_ATT_REMARK_1,
        GEOLOGY_ATTRIBUTE_2,
        GEO_ATT_VALUE_2,
        GEO_ATT_DETERMINER_2,
        GEO_ATT_DETERMINED_DATE_2,
        GEO_ATT_DETERMINED_METHOD_2,
        GEO_ATT_REMARK_2,
        GEOLOGY_ATTRIBUTE_3,
        GEO_ATT_VALUE_3,
        GEO_ATT_DETERMINER_3,
        GEO_ATT_DETERMINED_DATE_3,
        GEO_ATT_DETERMINED_METHOD_3,
        GEO_ATT_REMARK_3,
        GEOLOGY_ATTRIBUTE_4,
        GEO_ATT_VALUE_4,
        GEO_ATT_DETERMINER_4,
        GEO_ATT_DETERMINED_DATE_4,
        GEO_ATT_DETERMINED_METHOD_4,
        GEO_ATT_REMARK_4,
        GEOLOGY_ATTRIBUTE_5,
        GEO_ATT_VALUE_5,
        GEO_ATT_DETERMINER_5,
        GEO_ATT_DETERMINED_DATE_5,
        GEO_ATT_DETERMINED_METHOD_5,
        GEO_ATT_REMARK_5,
        GEOLOGY_ATTRIBUTE_6,
        GEO_ATT_VALUE_6,
        GEO_ATT_DETERMINER_6,
        GEO_ATT_DETERMINED_DATE_6,
        GEO_ATT_DETERMINED_METHOD_6,
        GEO_ATT_REMARK_6,
        COLLECTING_EVENT_ID,
        COLLECTION_ID,
        ENTERED_AGENT_ID,
        ENTEREDTOBULKDATE
    ) VALUES (
		:old.COLLECTION_OBJECT_ID,
        :old.LOADED,
        :old.ENTEREDBY,
        :old.CAT_NUM,
        :old.OTHER_ID_NUM_5,
        :old.OTHER_ID_NUM_TYPE_5,
        :old.OTHER_ID_NUM_1,
        :old.OTHER_ID_NUM_TYPE_1,
        :old.ACCN,
        :old.TAXON_NAME,
        :old.NATURE_OF_ID,
        :old.ID_MADE_BY_AGENT,
        :old.MADE_DATE,
        :old.IDENTIFICATION_REMARKS,
        :old.VERBATIM_DATE,
        :old.BEGAN_DATE,
        :old.ENDED_DATE,
        :old.HIGHER_GEOG,
        :old.SPEC_LOCALITY,
        :old.VERBATIM_LOCALITY,
        :old.ORIG_LAT_LONG_UNITS,
        :old.DEC_LAT,
        :old.DEC_LONG,
        :old.LATDEG,
        :old.DEC_LAT_MIN,
        :old.LATMIN,
        :old.LATSEC,
        :old.LATDIR,
        :old.LONGDEG,
        :old.DEC_LONG_MIN,
        :old.LONGMIN,
        :old.LONGSEC,
        :old.LONGDIR,
        :old.DATUM,
        :old.LAT_LONG_REF_SOURCE,
        :old.MAX_ERROR_DISTANCE,
        :old.MAX_ERROR_UNITS,
        :old.GEOREFMETHOD,
        :old.DETERMINED_BY_AGENT,
        :old.DETERMINED_DATE,
        :old.LAT_LONG_REMARKS,
        :old.VERIFICATIONSTATUS,
        :old.MAXIMUM_ELEVATION,
        :old.MINIMUM_ELEVATION,
        :old.ORIG_ELEV_UNITS,
        :old.LOCALITY_REMARKS,
        :old.HABITAT_DESC,
        :old.COLL_EVENT_REMARKS,
        :old.COLLECTOR_AGENT_1,
        :old.COLLECTOR_ROLE_1,
        :old.COLLECTOR_AGENT_2,
        :old.COLLECTOR_ROLE_2,
        :old.COLLECTOR_AGENT_3,
        :old.COLLECTOR_ROLE_3,
        :old.COLLECTOR_AGENT_4,
        :old.COLLECTOR_ROLE_4,
        :old.COLLECTOR_AGENT_5,
        :old.COLLECTOR_ROLE_5,
        :old.COLLECTOR_AGENT_6,
        :old.COLLECTOR_ROLE_6,
        :old.COLLECTOR_AGENT_7,
        :old.COLLECTOR_ROLE_7,
        :old.COLLECTOR_AGENT_8,
        :old.COLLECTOR_ROLE_8,
        :old.COLLECTION_CDE,
        :old.INSTITUTION_ACRONYM,
        :old.FLAGS,
        :old.COLL_OBJ_DISPOSITION,
        :old.CONDITION,
        :old.COLL_OBJECT_REMARKS,
        :old.DISPOSITION_REMARKS,
        :old.OTHER_ID_NUM_2,
        :old.OTHER_ID_NUM_TYPE_2,
        :old.OTHER_ID_NUM_3,
        :old.OTHER_ID_NUM_TYPE_3,
        :old.OTHER_ID_NUM_4,
        :old.OTHER_ID_NUM_TYPE_4,
        :old.PART_NAME_1,
        :old.PART_CONDITION_1,
        :old.PART_BARCODE_1,
        :old.PART_CONTAINER_LABEL_1,
        :old.PART_LOT_COUNT_1,
        :old.PART_DISPOSITION_1,
        :old.PART_REMARK_1,
        :old.PART_NAME_2,
        :old.PART_CONDITION_2,
        :old.PART_BARCODE_2,
        :old.PART_CONTAINER_LABEL_2,
        :old.PART_LOT_COUNT_2,
        :old.PART_DISPOSITION_2,
        :old.PART_REMARK_2,
        :old.PART_NAME_3,
        :old.PART_CONDITION_3,
        :old.PART_BARCODE_3,
        :old.PART_CONTAINER_LABEL_3,
        :old.PART_LOT_COUNT_3,
        :old.PART_DISPOSITION_3,
        :old.PART_REMARK_3,
        :old.PART_NAME_4,
        :old.PART_CONDITION_4,
        :old.PART_BARCODE_4,
        :old.PART_CONTAINER_LABEL_4,
        :old.PART_LOT_COUNT_4,
        :old.PART_DISPOSITION_4,
        :old.PART_REMARK_4,
        :old.PART_NAME_5,
        :old.PART_CONDITION_5,
        :old.PART_BARCODE_5,
        :old.PART_CONTAINER_LABEL_5,
        :old.PART_LOT_COUNT_5,
        :old.PART_DISPOSITION_5,
        :old.PART_REMARK_5,
        :old.PART_NAME_6,
        :old.PART_CONDITION_6,
        :old.PART_BARCODE_6,
        :old.PART_CONTAINER_LABEL_6,
        :old.PART_LOT_COUNT_6,
        :old.PART_DISPOSITION_6,
        :old.PART_REMARK_6,
        :old.PART_NAME_7,
        :old.PART_CONDITION_7,
        :old.PART_BARCODE_7,
        :old.PART_CONTAINER_LABEL_7,
        :old.PART_LOT_COUNT_7,
        :old.PART_DISPOSITION_7,
        :old.PART_REMARK_7,
        :old.PART_NAME_8,
        :old.PART_CONDITION_8,
        :old.PART_BARCODE_8,
        :old.PART_CONTAINER_LABEL_8,
        :old.PART_LOT_COUNT_8,
        :old.PART_DISPOSITION_8,
        :old.PART_REMARK_8,
        :old.PART_NAME_9,
        :old.PART_CONDITION_9,
        :old.PART_BARCODE_9,
        :old.PART_CONTAINER_LABEL_9,
        :old.PART_LOT_COUNT_9,
        :old.PART_DISPOSITION_9,
        :old.PART_REMARK_9,
        :old.PART_NAME_10,
        :old.PART_CONDITION_10,
        :old.PART_BARCODE_10,
        :old.PART_CONTAINER_LABEL_10,
        :old.PART_LOT_COUNT_10,
        :old.PART_DISPOSITION_10,
        :old.PART_REMARK_10,
        :old.PART_NAME_11,
        :old.PART_CONDITION_11,
        :old.PART_BARCODE_11,
        :old.PART_CONTAINER_LABEL_11,
        :old.PART_LOT_COUNT_11,
        :old.PART_DISPOSITION_11,
        :old.PART_REMARK_11,
        :old.PART_NAME_12,
        :old.PART_CONDITION_12,
        :old.PART_BARCODE_12,
        :old.PART_CONTAINER_LABEL_12,
        :old.PART_LOT_COUNT_12,
        :old.PART_DISPOSITION_12,
        :old.PART_REMARK_12,
        :old.ATTRIBUTE_1,
        :old.ATTRIBUTE_VALUE_1,
        :old.ATTRIBUTE_UNITS_1,
        :old.ATTRIBUTE_REMARKS_1,
        :old.ATTRIBUTE_DATE_1,
        :old.ATTRIBUTE_DET_METH_1,
        :old.ATTRIBUTE_DETERMINER_1,
        :old.ATTRIBUTE_2,
        :old.ATTRIBUTE_VALUE_2,
        :old.ATTRIBUTE_UNITS_2,
        :old.ATTRIBUTE_REMARKS_2,
        :old.ATTRIBUTE_DATE_2,
        :old.ATTRIBUTE_DET_METH_2,
        :old.ATTRIBUTE_DETERMINER_2,
        :old.ATTRIBUTE_3,
        :old.ATTRIBUTE_VALUE_3,
        :old.ATTRIBUTE_UNITS_3,
        :old.ATTRIBUTE_REMARKS_3,
        :old.ATTRIBUTE_DATE_3,
        :old.ATTRIBUTE_DET_METH_3,
        :old.ATTRIBUTE_DETERMINER_3,
        :old.ATTRIBUTE_4,
        :old.ATTRIBUTE_VALUE_4,
        :old.ATTRIBUTE_UNITS_4,
        :old.ATTRIBUTE_REMARKS_4,
        :old.ATTRIBUTE_DATE_4,
        :old.ATTRIBUTE_DET_METH_4,
        :old.ATTRIBUTE_DETERMINER_4,
        :old.ATTRIBUTE_5,
        :old.ATTRIBUTE_VALUE_5,
        :old.ATTRIBUTE_UNITS_5,
        :old.ATTRIBUTE_REMARKS_5,
        :old.ATTRIBUTE_DATE_5,
        :old.ATTRIBUTE_DET_METH_5,
        :old.ATTRIBUTE_DETERMINER_5,
        :old.ATTRIBUTE_6,
        :old.ATTRIBUTE_VALUE_6,
        :old.ATTRIBUTE_UNITS_6,
        :old.ATTRIBUTE_REMARKS_6,
        :old.ATTRIBUTE_DATE_6,
        :old.ATTRIBUTE_DET_METH_6,
        :old.ATTRIBUTE_DETERMINER_6,
        :old.ATTRIBUTE_7,
        :old.ATTRIBUTE_VALUE_7,
        :old.ATTRIBUTE_UNITS_7,
        :old.ATTRIBUTE_REMARKS_7,
        :old.ATTRIBUTE_DATE_7,
        :old.ATTRIBUTE_DET_METH_7,
        :old.ATTRIBUTE_DETERMINER_7,
        :old.ATTRIBUTE_8,
        :old.ATTRIBUTE_VALUE_8,
        :old.ATTRIBUTE_UNITS_8,
        :old.ATTRIBUTE_REMARKS_8,
        :old.ATTRIBUTE_DATE_8,
        :old.ATTRIBUTE_DET_METH_8,
        :old.ATTRIBUTE_DETERMINER_8,
        :old.ATTRIBUTE_9,
        :old.ATTRIBUTE_VALUE_9,
        :old.ATTRIBUTE_UNITS_9,
        :old.ATTRIBUTE_REMARKS_9,
        :old.ATTRIBUTE_DATE_9,
        :old.ATTRIBUTE_DET_METH_9,
        :old.ATTRIBUTE_DETERMINER_9,
        :old.ATTRIBUTE_10,
        :old.ATTRIBUTE_VALUE_10,
        :old.ATTRIBUTE_UNITS_10,
        :old.ATTRIBUTE_REMARKS_10,
        :old.ATTRIBUTE_DATE_10,
        :old.ATTRIBUTE_DET_METH_10,
        :old.ATTRIBUTE_DETERMINER_10,
        :old.RELATIONSHIP,
        :old.RELATED_TO_NUMBER,
        :old.RELATED_TO_NUM_TYPE,
        :old.MIN_DEPTH,
        :old.MAX_DEPTH,
        :old.DEPTH_UNITS,
        :old.COLLECTING_METHOD,
        :old.COLLECTING_SOURCE,
        :old.COLL_OBJECT_HABITAT,
        :old.ASSOCIATED_SPECIES,
        :old.LOCALITY_ID,
        :old.UTM_ZONE,
        :old.UTM_EW,
        :old.UTM_NS,
        :old.EXTENT,
        :old.GPSACCURACY,
        :old.GEOLOGY_ATTRIBUTE_1,
        :old.GEO_ATT_VALUE_1,
        :old.GEO_ATT_DETERMINER_1,
        :old.GEO_ATT_DETERMINED_DATE_1,
        :old.GEO_ATT_DETERMINED_METHOD_1,
        :old.GEO_ATT_REMARK_1,
        :old.GEOLOGY_ATTRIBUTE_2,
        :old.GEO_ATT_VALUE_2,
        :old.GEO_ATT_DETERMINER_2,
        :old.GEO_ATT_DETERMINED_DATE_2,
        :old.GEO_ATT_DETERMINED_METHOD_2,
        :old.GEO_ATT_REMARK_2,
        :old.GEOLOGY_ATTRIBUTE_3,
        :old.GEO_ATT_VALUE_3,
        :old.GEO_ATT_DETERMINER_3,
        :old.GEO_ATT_DETERMINED_DATE_3,
        :old.GEO_ATT_DETERMINED_METHOD_3,
        :old.GEO_ATT_REMARK_3,
        :old.GEOLOGY_ATTRIBUTE_4,
        :old.GEO_ATT_VALUE_4,
        :old.GEO_ATT_DETERMINER_4,
        :old.GEO_ATT_DETERMINED_DATE_4,
        :old.GEO_ATT_DETERMINED_METHOD_4,
        :old.GEO_ATT_REMARK_4,
        :old.GEOLOGY_ATTRIBUTE_5,
        :old.GEO_ATT_VALUE_5,
        :old.GEO_ATT_DETERMINER_5,
        :old.GEO_ATT_DETERMINED_DATE_5,
        :old.GEO_ATT_DETERMINED_METHOD_5,
        :old.GEO_ATT_REMARK_5,
        :old.GEOLOGY_ATTRIBUTE_6,
        :old.GEO_ATT_VALUE_6,
        :old.GEO_ATT_DETERMINER_6,
        :old.GEO_ATT_DETERMINED_DATE_6,
        :old.GEO_ATT_DETERMINED_METHOD_6,
        :old.GEO_ATT_REMARK_6,
        :old.COLLECTING_EVENT_ID,
        :old.COLLECTION_ID,
        :old.ENTERED_AGENT_ID,
        :old.ENTEREDTOBULKDATE
    );
END;


BEGIN
    DBMS_RLS.ADD_POLICY(
         object_schema => 'UAM'
        ,object_name => 'BULKLOADER'
        ,policy_name => 'BULKLOADER_SIUD_POL'
        ,function_schema => 'UAM'
        ,policy_function=> 'APP_SECURITY_CONTEXT.SET_CID_PRED'
        ,statement_types => 'SELECT,INSERT,UPDATE,DELETE'
        ,policy_type => DBMS_RLS.CONTEXT_SENSITIVE
    );
END;
/


CREATE OR REPLACE PUBLIC SYNONYM bulkloader FOR bulkloader;
    
GRANT ALL ON bulkloader TO data_entry;