--from https://github.com/ArctosDB/arctos/issues/983

insert into  CTTAXONOMY_SOURCE (SOURCE,DESCRIPTION) values ('Arctos Relationships','Place to store relationship data in classifications. This resource exists as a search aid. It is not an authoritative source of taxonomy relationships; [hemi]homonyms will create false assertions, for example.');

-- ignore that in triggers
create or replace trigger trg_taxon_term_cts....

-- seed with existing data
-- temp for performance
create table temp_tax_rel as select * from taxon_relations;
alter table temp_tax_rel add pushed_to_class number;

declare
	cid varchar2(4000);
begin
	for r in (select * from temp_tax_rel where pushed_to_class is null and rownum<2) loop
		-- insert for TAXON_NAME_ID
		
	dbms_output.put_line(r.taxon_name_id);
	
		select sys_guid() into cid from dual;
		
	
		insert into taxon_term (
			TAXON_NAME_ID,
			CLASSIFICATION_ID,
			TERM,
			TERM_TYPE,
			SOURCE
		) (
			select
				taxon_name_id,
				cid,
				term,
				term_type,
				'Arctos Relationships'
			from
				taxon_term
			where
				taxon_name_id=r.taxon_name_id and
				source in (select source from CTTAXONOMY_SOURCE where source != 'Arctos Relationships')
		);
		insert into taxon_term (
			TAXON_NAME_ID,
			CLASSIFICATION_ID,
			TERM,
			TERM_TYPE,
			SOURCE
		) values (
			r.taxon_name_id,
			cid,
			'Autogenerated from relationship ' || r.TAXON_RELATIONSHIP || '.' || decode(r.RELATION_AUTHORITY,NULL,'','Authority: ' || r.RELATION_AUTHORITY),
			'remark',
			'Arctos Relationships'
		);

	end loop;
end ;
/





UAM@ARCTOSTE> desc 
 Name								   Null?    Type
 ----------------------------------------------------------------- -------- --------------------------------------------
 TAXON_NAME_ID							   NOT NULL NUMBER(10)
 RELATED_TAXON_NAME_ID						   NOT NULL NUMBER(10)
 TAXON_RELATIONSHIP						   NOT NULL VARCHAR2(50)
 RELATION_AUTHORITY							    VARCHAR2(255)
 TAXON_RELATIONS_ID						   NOT NULL NUMBER

