-- after changes to classification data, replace anything in display_name with a call to autoGenerateDispalyName()

-- temp table to hold changes

create table cf_autogen_display_name (classification_id varchar2(4000) not null);

-- modify DDL/triggers/taxon_term to insert

-- procedure


CREATE OR REPLACE PROCEDURE proc_autogen_display_name IS
	dn varchar2(4000);
	tid number;
	src  varchar2(4000);
	sttid number;
begin
	for r in (select distinct classification_id from cf_autogen_display_name) loop
		-- flush any old stuff
		delete from taxon_term where term_type='display_name' and classification_id=r.classification_id;
		-- see if we can create one
		select generateDisplayName(r.classification_id) into dn from dual;
		if dn is not null then
			-- need some seed stuff
			select TAXON_NAME_ID,SOURCE into tid,src from taxon_term where TAXON_TERM_ID in (select min(TAXON_TERM_ID) from
			taxon_term where classification_id=r.classification_id);
			-- insert
			insert into taxon_term (
				TAXON_NAME_ID,
				CLASSIFICATION_ID,
				TERM,
				TERM_TYPE,
				SOURCE,
				LASTDATE
			) values (
				tid,
				r.classification_id,
				dn,
				'display_name',
				src,
				sysdate
			);
		end if;
		-- clean up
		delete from cf_autogen_display_name where classification_id=r.classification_id;
	end loop;
end;
/
sho err;

insert into cf_autogen_display_name(classification_id) values ('71A744F1-9336-D272-6CACE8C38BBE1630');
		
		UAM@ARCTOS> 
UAM@ARCTOS> desc taxon_term
 Name								   Null?    Type
 ----------------------------------------------------------------- -------- --------------------------------------------
 TAXON_TERM_ID							   NOT NULL NUMBER
 TAXON_NAME_ID							   NOT NULL NUMBER
 CLASSIFICATION_ID							    VARCHAR2(4000)
 TERM								   NOT NULL VARCHAR2(4000)
 TERM_TYPE								    VARCHAR2(255)
 SOURCE 							   NOT NULL VARCHAR2(255)
 GN_SCORE								    NUMBER
 POSITION_IN_CLASSIFICATION						    NUMBER
 LASTDATE							   NOT NULL DATE
 MATCH_TYPE								    VARCHAR2(255)

UAM@ARCTOS> 



    update temp_dnametest set oracledname=generateDisplayName(cid) where oracledname is null;
end;
/