CREATE TABLE GREF_USER (
    ID NUMBER(22,0) NOT NULL,
    FIRST_NAME VARCHAR2(127),
    LAST_NAME VARCHAR2(127),
    USER_NAME VARCHAR2(127),
    EMAIL VARCHAR2(127),
    PASSWORD_SHA1 VARCHAR2(127),
    TITLE VARCHAR2(127),
    INSTITUTION VARCHAR2(127),
    APPROVED NUMBER(1,0),
        CONSTRAINT PK_GREF_USER
            PRIMARY KEY (ID)
            USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;
