CREATE TABLE GREF_ROI_NG (
    ID NUMBER NOT NULL,
    X NUMBER,
    Y NUMBER,
    W NUMBER,
    H NUMBER,
    PAGE_ID NUMBER,
    ROI_VALUE_NG_ID NUMBER,
    PUBLICATION_ID NUMBER(22,0),
    SECTION_NUMBER NUMBER(22,0),
    PAGE_NUMBER NUMBER(22,0),
    GLOBAL NUMBER(1,0) DEFAULT (0),
        CONSTRAINT PK_GREF_ROI_NG
            PRIMARY KEY (ID)
            USING INDEX TABLESPACE UAM_IDX_1,
        CONSTRAINT FK_ROING_PAGE
            FOREIGN KEY (PAGE_ID)
            REFERENCES PAGE (PAGE_ID),
        CONSTRAINT FK_ROING_PUBLICATION
            FOREIGN KEY (PUBLICATION_ID)
            REFERENCES PUBLICATION (PUBLICATION_ID),
        CONSTRAINT FK_ROING_ROIVALUENG
            FOREIGN KEY (ROI_VALUE_NG_ID)
            REFERENCES GREF_ROI_VALUE_NG (ID)
) TABLESPACE UAM_DAT_1;
