CREATE TABLE GREF_REFSET_ROI_NG (
    REFSET_NG_ID NUMBER NOT NULL,
    ROI_NG_ID NUMBER NOT NULL,
        CONSTRAINT FK_REFSETROING_REFSETNG
            FOREIGN KEY (REFSET_NG_ID)
            REFERENCES GREF_REFSET_NG (ID),
        CONSTRAINT FK_REFSETROING_ROING
            FOREIGN KEY (ROI_NG_ID)
            REFERENCES GREF_ROI_NG (ID)
) TABLESPACE UAM_DAT_1;
