CREATE TABLE GREF_PAGE_REFSET_NG (
    PAGE_ID NUMBER,
    REFSET_NG_ID NUMBER,
        CONSTRAINT FK_PAGEREFSETNG_PAGE
            FOREIGN KEY (PAGE_ID)
            REFERENCES PAGE (PAGE_ID)
) TABLESPACE UAM_DAT_1;
