CREATE TABLE GREF_ROI_VALUE_NG (
    ID NUMBER NOT NULL,
    ROI_NG_ID NUMBER,
    ROI_VALUE_TYPE VARCHAR2(4000),
    VERBATIM_BEGIN VARCHAR2(4000),
    VERBATIM_END VARCHAR2(4000),
    RANGE_BEGIN DATE,
    RANGE_END DATE,
    AGENT_ID NUMBER,
    HIGHER_GEOGRAPHY_ID NUMBER,
    CAT_NUM NUMBER(22,0),
    COLLECTION_OBJECT_ID NUMBER(22,0),
    COLLECTION_DESC VARCHAR2(255),
    AGENT_NAME VARCHAR2(184),
    HIGHER_GEOG VARCHAR2(255),
    SPEC_LOCALITY VARCHAR2(255),
    COLLECTOR_NUMBER VARCHAR2(255),
    SCIENTIFIC_NAME VARCHAR2(255),
    VERBATIM_LOCALITY VARCHAR2(300),
    COLLECTING_EVENT_ID NUMBER(22,0),
        CONSTRAINT PK_GREF_ROI_VALUE_NG
            PRIMARY KEY (ID)
            USING INDEX TABLESPACE UAM_IDX_1,
        CONSTRAINT FK_ROIVALUENG_COLLEVENT
            FOREIGN KEY (COLLECTING_EVENT_ID)
            REFERENCES COLLECTING_EVENT (COLLECTING_EVENT_ID),
        CONSTRAINT FK_ROIVALUENG_ROING
            FOREIGN KEY (ROI_NG_ID)
            REFERENCES GREF_ROI_NG (ID),
        CONSTRAINT FK_ROIVALUENG_COLLOBJECT
            FOREIGN KEY (COLLECTION_OBJECT_ID)
            REFERENCES COLL_OBJECT (COLLECTION_OBJECT_ID),
        CONSTRAINT FK_ROIVALUENG_AGENTNAME
            FOREIGN KEY (AGENT_ID)
            REFERENCES AGENT_NAME (AGENT_NAME_ID)
) TABLESPACE UAM_DAT_1;
