CREATE OR REPLACE FUNCTION does_not_end_statement (s VARCHAR2 )
RETURN INTEGER
-- we make sure that it does not have a ";" in it
IS
	n INTEGER;
BEGIN
	n := instr(s,';');
	IF n = 0 THEN
		RETURN 0;
	ELSE 
		RETURN 1;
	END IF;
EXCEPTION
	WHEN OTHERS THEN
	RETURN 0;
END;

CREATE PUBLIC SYNONYM DOES_NOT_END_STATEMENT FOR DOES_NOT_END_STATEMENT;
GRANT EXECUTE ON DOES_NOT_END_STATEMENT TO PUBLIC;