create OR REPLACE view PROJECT_MEDIA_RELATION_VIEW
 as 
SELECT 
MEDIA_ID, PROJECT_ID, project_name TITLE
FROM
MEDIA_RELATIONS, PROJECT
WHERE
RELATED_PRIMARY_KEY=PROJECT_ID and
lower(media_relationship) like '% project'
;

CREATE OR REPLACE public SYNONYM PROJECT_MEDIA_RELATION_VIEW FOR PROJECT_MEDIA_RELATION_VIEW;
GRANT SELECT ON PROJECT_MEDIA_RELATION_VIEW TO PUBLIC;
    