CREATE TABLE UAM_QUERY.QUERY_STATS_COLL (
    QUERY_ID NUMBER,
    REC_COUNT NUMBER,
    COLLECTION_ID NUMBER,
        CONSTRAINT PK_QUERY_STATS_COLL
            PRIMARY KEY (QUERY_ID, COLLECTION_ID)
            USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;
