-- not quite ready to get rid of tripartite accn numbers yet,
-- but we can disable the constraints on them to allow the new 
-- forms to work
-- alter table accn modify accn_num number null;
-- alter table accn modify ACCN_NUMBER VARCHAR2(60) not null;
 
CREATE TABLE ACCN (
	TRANSACTION_ID NUMBER NOT NULL,
	ACCN_TYPE VARCHAR2(35) NOT NULL,
	ACCN_NUM_PREFIX VARCHAR2(10),
	ACCN_NUM NUMBER,
	ACCN_NUM_SUFFIX VARCHAR2(4),
	ACCN_STATUS VARCHAR2(20) NOT NULL,
	ACCN_NUMBER VARCHAR2(60) NOT NULL,
	RECEIVED_DATE DATE,
	ESTIMATED_COUNT NUMBER,
		CONSTRAINT PK_ACCN
		    PRIMARY KEY (TRANSACTION_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_ACCN_TRANS
			FOREIGN KEY (TRANSACTION_ID)
			REFERENCES TRANS (TRANSACTION_ID),
		CONSTRAINT FK_CTACCN_STATUS
			FOREIGN KEY (ACCN_STATUS)
			REFERENCES CTACCN_STATUS (ACCN_STATUS),
		CONSTRAINT FK_CTACCN_TYPE
			FOREIGN KEY (ACCN_TYPE)
			REFERENCES CTACCN_TYPE (ACCN_TYPE)
) TABLESPACE UAM_DAT_1;
