CREATE TABLE ADDR (
	ADDR_ID NUMBER NOT NULL,
	STREET_ADDR1 VARCHAR2(255) NOT NULL,
	STREET_ADDR2 VARCHAR2(255),
	CITY VARCHAR2(60) NOT NULL,
	STATE VARCHAR2(20),
	ZIP VARCHAR2(10),
	COUNTRY_CDE VARCHAR2(50),
	MAIL_STOP VARCHAR2(20),
	FORMATTED_ADDR VARCHAR2(510),
	AGENT_ID NUMBER NOT NULL,
	ADDR_TYPE VARCHAR2(25) NOT NULL,
	JOB_TITLE VARCHAR2(60),
	VALID_ADDR_FG NUMBER NOT NULL,
	ADDR_REMARKS VARCHAR2(255),
	INSTITUTION VARCHAR2(255),
	DEPARTMENT VARCHAR2(255),
		CONSTRAINT PK_ADDR
		    PRIMARY KEY (ADDR_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_ADDR_AGENT
			FOREIGN KEY (AGENT_ID)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_CTADDR_TYPE
			FOREIGN KEY (ADDR_TYPE)
			REFERENCES CTADDR_TYPE (ADDR_TYPE)
) TABLESPACE UAM_DAT_1;
