CREATE TABLE AGENT (
	AGENT_ID NUMBER NOT NULL,
	AGENT_TYPE VARCHAR2(30) NOT NULL,
	AGENT_REMARKS VARCHAR2(4000),
	PREFERRED_AGENT_NAME_ID NUMBER NOT NULL,
		CONSTRAINT PK_AGENT
		    PRIMARY KEY (AGENT_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_CTAGENT_TYPE
			FOREIGN KEY (AGENT_TYPE)
			REFERENCES CTAGENT_TYPE (AGENT_TYPE)
) TABLESPACE UAM_DAT_1;
