CREATE TABLE AGENT_NAME (
	AGENT_NAME_ID NUMBER NOT NULL,
	AGENT_ID NUMBER NOT NULL,
	AGENT_NAME_TYPE VARCHAR2(18) NOT NULL,
	DONOR_CARD_PRESENT_FG NUMBER,
	AGENT_NAME VARCHAR2(184) NOT NULL,
		CONSTRAINT PK_AGENT_NAME
		    PRIMARY KEY (AGENT_NAME_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_AGENTNAME_AGENT
			FOREIGN KEY (AGENT_ID)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_CTAGENT_NAME_TYPE
			FOREIGN KEY (AGENT_NAME_TYPE)
			REFERENCES CTAGENT_NAME_TYPE (AGENT_NAME_TYPE)
) TABLESPACE UAM_DAT_1;