CREATE TABLE AGENT_RELATIONS (
	AGENT_ID NUMBER NOT NULL,
	RELATED_AGENT_ID NUMBER NOT NULL,
	AGENT_RELATIONSHIP VARCHAR2(18) NOT NULL,
        CONSTRAINT PK_AGENT_RELATIONS
            PRIMARY KEY (AGENT_ID, RELATED_AGENT_ID, AGENT_RELATIONSHIP)
            USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_AGENTRELATIONS_AGENT_ANID
			FOREIGN KEY (AGENT_ID)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_AGENTRELATIONS_AGENT_RANID
			FOREIGN KEY (RELATED_AGENT_ID)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_CTAGENT_RELATIONSHIP
			FOREIGN KEY (AGENT_RELATIONSHIP)
			REFERENCES CTAGENT_RELATIONSHIP (AGENT_RELATIONSHIP)
) TABLESPACE UAM_DAT_1;
