CREATE TABLE BINARY_OBJECT (
    COLLECTION_OBJECT_ID NUMBER NOT NULL,
	VIEWER_ID NUMBER NOT NULL,
	DERIVED_FROM_CAT_ITEM NUMBER NOT NULL,
	DERIVED_FROM_COLL_OBJ NUMBER,
	MADE_DATE DATE NOT NULL,
	SUBJECT VARCHAR2(50) NOT NULL,
	ASPECT VARCHAR2(30),
	DESCRIPTION VARCHAR2(255),
	FULL_URL VARCHAR2(255) NOT NULL,
	MADE_AGENT_ID NUMBER NOT NULL,
	THUMBNAIL_URL VARCHAR2(255),
		CONSTRAINT PK_BINARY_OBJECT
			PRIMARY KEY (COLLECTION_OBJECT_ID)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;
