CREATE TABLE BIOL_INDIV_RELATIONS (
    COLLECTION_OBJECT_ID NUMBER NOT NULL,
    RELATED_COLL_OBJECT_ID NUMBER NOT NULL,
    BIOL_INDIV_RELATIONSHIP VARCHAR2(18) NOT NULL,
        CONSTRAINT PK_BIOL_INDIV_RELATIONS
            PRIMARY KEY (COLLECTION_OBJECT_ID, RELATED_COLL_OBJECT_ID, BIOL_INDIV_RELATIONSHIP)
            USING INDEX TABLESPACE UAM_IDX_1,
        CONSTRAINT FK_BIOLINDIVRELN_CATITEM_COID
            FOREIGN KEY (COLLECTION_OBJECT_ID)
            REFERENCES CATALOGED_ITEM (COLLECTION_OBJECT_ID),
        CONSTRAINT FK_BIOLINDIVRELN_CATITEM_RCOID
            FOREIGN KEY (RELATED_COLL_OBJECT_ID)
            REFERENCES CATALOGED_ITEM (COLLECTION_OBJECT_ID),
        CONSTRAINT FK_CTBIOL_RELATIONS
            FOREIGN KEY (BIOL_INDIV_RELATIONSHIP)
            REFERENCES CTBIOL_RELATIONS (BIOL_INDIV_RELATIONSHIP)
) TABLESPACE UAM_DAT_1