CREATE TABLE BOOK (
	PUBLICATION_ID NUMBER NOT NULL,
	EDITED_WORK_FG NUMBER NOT NULL,
	VOLUME_NUMBER NUMBER,
	PAGE_TOTAL VARCHAR2(15),
	PUBLISHER_NAME VARCHAR2(127),
		CONSTRAINT PK_BOOK
		    PRIMARY KEY (PUBLICATION_ID)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;
