CREATE TABLE BORROW (
	TRANSACTION_ID NUMBER NOT NULL,
	LENDERS_TRANS_NUM_CDE VARCHAR2(20),
	BORROW_NUM NUMBER NOT NULL,
	LENDERS_INVOICE_RETURNED_FG NUMBER NOT NULL,
	RECEIVED_DATE DATE,
	DUE_DATE DATE,
	LENDERS_LOAN_DATE DATE,
	BORROW_STATUS VARCHAR2(20),
	LENDERS_INSTRUCTIONS VARCHAR2(255),
	LENDER_LOAN_TYPE VARCHAR2(60),
		CONSTRAINT PK_BORROW
		    PRIMARY KEY (TRANSACTION_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_BORROW_TRANS
			FOREIGN KEY (TRANSACTION_ID)
			REFERENCES TRANS (TRANSACTION_ID),
		CONSTRAINT FK_CTBORROW_STATUS
			FOREIGN KEY (BORROW_STATUS)
			REFERENCES CTBORROW_STATUS (BORROW_STATUS)
) TABLESPACE UAM_DAT_1;
