CREATE TABLE CATALOGED_ITEM (
	COLLECTION_OBJECT_ID NUMBER NOT NULL,
	CAT_NUM NUMBER NOT NULL,
	ACCN_ID NUMBER NOT NULL,
	COLLECTING_EVENT_ID NUMBER NOT NULL,
	COLLECTION_CDE VARCHAR2(5) NOT NULL,
	CATALOGED_ITEM_TYPE CHAR(2) NOT NULL,
	COLLECTION_ID NUMBER NOT NULL,
		CONSTRAINT PK_CATALOGED_ITEM
		    PRIMARY KEY (COLLECTION_OBJECT_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
        CONSTRAINT CK_CATITEM_CATNUM
            CHECK (cat_num > 0),
		CONSTRAINT FK_CATITEM_COLLECTION
			FOREIGN KEY (COLLECTION_ID)
			REFERENCES COLLECTION (COLLECTION_ID),
		CONSTRAINT FK_CATITEM_COLLEVENT
			FOREIGN KEY (COLLECTING_EVENT_ID)
			REFERENCES COLLECTING_EVENT (COLLECTING_EVENT_ID),
		CONSTRAINT FK_CATITEM_COLLOBJECT
			FOREIGN KEY (COLLECTION_OBJECT_ID)
			REFERENCES COLL_OBJECT (COLLECTION_OBJECT_ID),
		CONSTRAINT FK_CATITEM_ACCN
			FOREIGN KEY (ACCN_ID)
			REFERENCES ACCN (TRANSACTION_ID),
		CONSTRAINT FK_CTCATALOGED_ITEM_TYPE
			FOREIGN KEY (CATALOGED_ITEM_TYPE)
			REFERENCES CTCATALOGED_ITEM_TYPE (CATALOGED_ITEM_TYPE)
)
TABLESPACE UAM_DAT_1
PARTITION BY LIST (COLLECTION_ID) (
    PARTITION UAM_MAMM  VALUES (1),
	PARTITION UAM_BIRD  VALUES (2),
	PARTITION UAM_HERP  VALUES (3),
	PARTITION UAM_ENTO  VALUES (4),
	PARTITION UAM_HERB  VALUES (6),
	PARTITION NBSB_BIRD  VALUES (7),
	PARTITION UAM_FISH  VALUES (10),
	PARTITION UAM_INV  VALUES (11),
	PARTITION KWP_ENTO  VALUES (12),
	PARTITION UAMOBS_MAMM  VALUES (13),
	PARTITION MSB_MAMM  VALUES (14),
	PARTITION DGR_ENTO  VALUES (15),
	PARTITION DGR_BIRD  VALUES (16),
	PARTITION DGR_MAMM  VALUES (17),
	PARTITION DGR_HERP  VALUES (18),
	PARTITION DGR_FISH  VALUES (19),
	PARTITION MSB_BIRD  VALUES (20),
	PARTITION UAM_ES  VALUES (21),
	PARTITION WNMU_BIRD  VALUES (22),
	PARTITION WNMU_FISH  VALUES (23),
	PARTITION WNMU_MAMM  VALUES (24),
	PARTITION PSU_MAMM  VALUES (25),
	PARTITION CRCM_BIRD  VALUES (26),
	PARTITION MSB_PARA  VALUES (27),
	PARTITION MVZ_MAMM  VALUES (28),
	PARTITION MVZ_BIRD  VALUES (29),
	PARTITION MVZ_HERP  VALUES (30),
	PARTITION MVZ_EGG  VALUES (31),
	PARTITION MVZ_HILD  VALUES (32),
	PARTITION MVZ_IMG  VALUES (33),
	PARTITION MVZ_PAGE  VALUES (34),
    PARTITION MVZOBS_BIRD  VALUES (35),
	PARTITION MVZOBS_HERP  VALUES (36),
	PARTITION MVZOBS_MAMM  VALUES (37),
	PARTITION UAM_ART  VALUES (39),
	PARTITION UAMB_HERB  VALUES (40),
	PARTITION MSBOBS_MAMM  VALUES (41)
);

-- case-insensitive index on "guid"
CREATE UNIQUE INDEX IU_catitem_catnum_coln_UPR ON cataloged_item (UPPER(cat_num),collection_id) TABLESPACE UAM_IDX_1;
	
	