CREATE TABLE CITATION (
	PUBLICATION_ID NUMBER NOT NULL,
	COLLECTION_OBJECT_ID NUMBER NOT NULL,
	CITED_TAXON_NAME_ID NUMBER NOT NULL,
	CIT_CURRENT_FG NUMBER NOT NULL,
	OCCURS_PAGE_NUMBER NUMBER,
	TYPE_STATUS VARCHAR2(60),
	CITATION_REMARKS VARCHAR2(255),
	CITATION_TEXT VARCHAR2(255),
	REP_PUBLISHED_YEAR NUMBER,
		CONSTRAINT PK_CITATION
		    PRIMARY KEY (COLLECTION_OBJECT_ID, PUBLICATION_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_CITATION_CATITEM
			FOREIGN KEY (COLLECTION_OBJECT_ID)
			REFERENCES CATALOGED_ITEM (COLLECTION_OBJECT_ID),
		CONSTRAINT FK_CITATION_PUBLICATION
			FOREIGN KEY (PUBLICATION_ID)
			REFERENCES PUBLICATION (PUBLICATION_ID),
		CONSTRAINT FK_CTCITATION_TYPE_STATUS
			FOREIGN KEY (TYPE_STATUS)
			REFERENCES CTCITATION_TYPE_STATUS (TYPE_STATUS),
		CONSTRAINT FK_CITATION_TAXONOMY
			FOREIGN KEY (CITED_TAXON_NAME_ID)
			REFERENCES TAXONOMY (TAXON_NAME_ID)
) TABLESPACE UAM_DAT_1;
