CREATE TABLE COLLECTOR (
	COLLECTION_OBJECT_ID NUMBER NOT NULL,
	AGENT_ID NUMBER NOT NULL,
	COLLECTOR_ROLE CHAR(1) NOT NULL,
	COLL_NUM_PREFIX VARCHAR2(20),
	COLL_NUM NUMBER(15,0),
	COLL_NUM_SUFFIX VARCHAR2(9),
	COLL_ORDER NUMBER NOT NULL,
	    CONSTRAINT COLL_ROLE_CHECK
            CHECK (COLLECTOR_ROLE IN ('c','p')),
        CONSTRAINT PK_COLLECTOR
            PRIMARY KEY (COLLECTION_OBJECT_ID, AGENT_ID, COLLECTOR_ROLE)
            USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_COLLECTOR_AGENT
			FOREIGN KEY (AGENT_ID)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_COLLECTOR_CATITEM
			FOREIGN KEY (COLLECTION_OBJECT_ID)
			REFERENCES CATALOGED_ITEM (COLLECTION_OBJECT_ID),
		CONSTRAINT FK_CTCOLLECTOR_ROLE
			FOREIGN KEY (COLLECTOR_ROLE)
			REFERENCES CTCOLLECTOR_ROLE (COLLECTOR_ROLE)
) TABLESPACE UAM_DAT_1;
