CREATE TABLE COLLECTION_CONTACTS (
	COLLECTION_CONTACT_ID NUMBER NOT NULL,
	COLLECTION_ID NUMBER NOT NULL,
	CONTACT_ROLE VARCHAR2(60) NOT NULL,
	CONTACT_AGENT_ID NUMBER NOT NULL,
		CONSTRAINT PK_COLLECTION_CONTACTS
			PRIMARY KEY (COLLECTION_CONTACT_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_COLLCONTACTS_AGENT
			FOREIGN KEY (CONTACT_AGENT_ID)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_COLLCONTACTS_COLLECTION
			FOREIGN KEY (COLLECTION_ID)
			REFERENCES COLLECTION (COLLECTION_ID),
		CONSTRAINT FK_CTCOLL_CONTACT_ROLE
			FOREIGN KEY (CONTACT_ROLE)
			REFERENCES CTCOLL_CONTACT_ROLE (CONTACT_ROLE)
) TABLESPACE UAM_DAT_1;
