CREATE TABLE COLL_OBJ_CONT_HIST (
	COLLECTION_OBJECT_ID NUMBER NOT NULL,
	CONTAINER_ID NUMBER NOT NULL,
	INSTALLED_DATE DATE NOT NULL,
	CURRENT_CONTAINER_FG NUMBER NOT NULL,
	    CONSTRAINT PK_COLL_OBJ_CONT_HIST
            PRIMARY KEY (COLLECTION_OBJECT_ID, CONTAINER_ID)
            USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_COLLOBJCONTHIST_CONTAINER
			FOREIGN KEY (CONTAINER_ID)
			REFERENCES CONTAINER (CONTAINER_ID),
		CONSTRAINT FK_COLLOBJCONTHIST_SPECPART
			FOREIGN KEY (COLLECTION_OBJECT_ID)
			REFERENCES SPECIMEN_PART (COLLECTION_OBJECT_ID) ON DELETE CASCADE
) TABLESPACE UAM_DAT_1;


-- ALTER TABLE coll_obj_cont_hist MODIFY current_container_fg NUMBER(1) DEFAULT 1;
    
