CREATE TABLE COLLECTOR_FORMATTED (
    COLLECTION_OBJECT_ID NUMBER(*,0) NOT NULL,
    COLLECTORS VARCHAR2(255) NOT NULL,
        CONSTRAINT PK_COLLECTOR_FORMATTED 
            PRIMARY KEY (COLLECTION_OBJECT_ID)
            USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;
