CREATE TABLE COLLECTION (
	COLLECTION_CDE VARCHAR2(5) NOT NULL,
	INSTITUTION_ACRONYM VARCHAR2(20),
	DESCR VARCHAR2(255),
	COLLECTION VARCHAR2(30) NOT NULL,
	COLLECTION_ID NUMBER NOT NULL,
	WEB_LINK VARCHAR2(4000),
	WEB_LINK_TEXT VARCHAR2(25),
	GENBANK_PRID NUMBER,
	GENBANK_USERNAME VARCHAR2(20),
	GENBANK_PWD VARCHAR2(20),
	LOAN_POLICY_URL VARCHAR2(255),
	INSTITUTION VARCHAR2(255),
	GUID_PREFIX VARCHAR2(20) NOT NULL,
		CONSTRAINT PK_COLLECTION
		    PRIMARY KEY (COLLECTION_ID)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;
