CREATE TABLE COLLECTING_EVENT (
	COLLECTING_EVENT_ID NUMBER NOT NULL,
	LOCALITY_ID NUMBER NOT NULL,
	BEGAN_DATE DATE NOT NULL,
	ENDED_DATE DATE NOT NULL,
	VERBATIM_DATE VARCHAR2(60) NOT NULL,
	VERBATIM_LOCALITY VARCHAR2(260),
	COLL_EVENT_REMARKS VARCHAR2(255),
	VALID_DISTRIBUTION_FG NUMBER,
	COLLECTING_SOURCE VARCHAR2(15) NOT NULL,
	COLLECTING_METHOD VARCHAR2(255),
	HABITAT_DESC VARCHAR2(255),
	DATE_DETERMINED_BY_AGENT_ID NUMBER,
		CONSTRAINT PK_COLLECTING_EVENT
		    PRIMARY KEY (COLLECTING_EVENT_ID)
		    USING INDEX TABLESPACE UAM_IDX_1,
        CONSTRAINT CK_BEGAN_BEFORE_END
            CHECK (began_date <= ended_date),
		CONSTRAINT FK_COLLEVENT_LOCALITY
			FOREIGN KEY (LOCALITY_ID)
			REFERENCES LOCALITY (LOCALITY_ID),
		CONSTRAINT FK_CTCOLLECTING_SOURCE
			FOREIGN KEY (COLLECTING_SOURCE)
			REFERENCES CTCOLLECTING_SOURCE (COLLECTING_SOURCE)
) TABLESPACE UAM_DAT_1;
