CREATE TABLE COMMON_NAME (
	TAXON_NAME_ID NUMBER NOT NULL,
	COMMON_NAME VARCHAR2(60) NOT NULL,
		CONSTRAINT PK_COMMON_NAME
			PRIMARY KEY (TAXON_NAME_ID, COMMON_NAME)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_COMMONNAME_TAXONOMY
			FOREIGN KEY (TAXON_NAME_ID)
			REFERENCES TAXONOMY (TAXON_NAME_ID)
) TABLESPACE UAM_DAT_1;
