CREATE TABLE CONTAINER_CHECK (
	CONTAINER_CHECK_ID NUMBER NOT NULL,
	CONTAINER_ID NUMBER NOT NULL,
	CHECK_DATE DATE NOT NULL,
	CHECKED_AGENT_ID NUMBER NOT NULL,
	CHECK_REMARK VARCHAR2(255),
		CONSTRAINT PK_CONTAINER_CHECK
			PRIMARY KEY (CONTAINER_CHECK_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_CONTAINERCHECK_AGENT
			FOREIGN KEY (CHECKED_AGENT_ID)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_CONTAINERCHECK_CONTAINER
			FOREIGN KEY (CONTAINER_ID)
			REFERENCES CONTAINER (CONTAINER_ID)
) TABLESPACE UAM_DAT_1;
