CREATE TABLE CONTAINER (
	CONTAINER_ID NUMBER NOT NULL,
	PARENT_CONTAINER_ID NUMBER NOT NULL,
	CONTAINER_TYPE VARCHAR2(20) NOT NULL,
	LABEL VARCHAR2(255) NOT NULL,
	DESCRIPTION VARCHAR2(255),
	PARENT_INSTALL_DATE DATE,
	CONTAINER_REMARKS VARCHAR2(255),
	BARCODE VARCHAR2(50),
	PRINT_FG NUMBER(1,0),
	WIDTH NUMBER,
	HEIGHT NUMBER,
	LENGTH NUMBER,
	NUMBER_POSITIONS NUMBER,
	LOCKED_POSITION NUMBER(1,0) NOT NULL,
	INSTITUTION_ACRONYM VARCHAR2(20) NOT NULL,
		CONSTRAINT PK_CONTAINER
			PRIMARY KEY (CONTAINER_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_CTCONTAINER_TYPE
			FOREIGN KEY (CONTAINER_TYPE)
			REFERENCES CTCONTAINER_TYPE (CONTAINER_TYPE)
) TABLESPACE UAM_DAT_1 ENABLE ROW MOVEMENT;
