CREATE TABLE ELECTRONIC_ADDRESS (
	AGENT_ID NUMBER NOT NULL,
	ADDRESS_TYPE VARCHAR2(30) NOT NULL,
	ADDRESS VARCHAR2(255) NOT NULL,
		CONSTRAINT FK_ELECTRONICADDR_AGENT
			FOREIGN KEY (AGENT_ID)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_CTELECTRONIC_ADDR_TYPE
			FOREIGN KEY (ADDRESS_TYPE)
			REFERENCES CTELECTRONIC_ADDR_TYPE (ADDRESS_TYPE)
) TABLESPACE UAM_DAT_1;
