CREATE TABLE ENCUMBRANCE (
	ENCUMBRANCE_ID NUMBER NOT NULL,
	ENCUMBERING_AGENT_ID NUMBER NOT NULL,
	EXPIRATION_DATE DATE,
	EXPIRATION_EVENT VARCHAR2(60),
	ENCUMBRANCE VARCHAR2(60) NOT NULL,
	MADE_DATE DATE,
	REMARKS VARCHAR2(255),
	ENCUMBRANCE_ACTION VARCHAR2(30) NOT NULL,
		CONSTRAINT PK_ENCUMBRANCE
			PRIMARY KEY (ENCUMBRANCE_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_ENCUMBRANCE_AGENT
			FOREIGN KEY (ENCUMBERING_AGENT_ID)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_CTENCUMBRANCE_ACTION
			FOREIGN KEY (ENCUMBRANCE_ACTION)
			REFERENCES CTENCUMBRANCE_ACTION (ENCUMBRANCE_ACTION)
) TABLESPACE UAM_DAT_1;
