CREATE TABLE FIELD_NOTEBOOK_SECTION (
	PUBLICATION_ID NUMBER(*,0) NOT NULL,
	BEGIN_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	BEGINS_COLLECTORS_NUM VARCHAR2(15),
	ENDS_COLLECTORS_NUM VARCHAR2(15),
	FIELD_NOTEBOOK_SECTION_TYPE VARCHAR2(30),
		CONSTRAINT PK_FIELD_NOTEBOOK_SECTION
			PRIMARY KEY (PUBLICATION_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_FIELDNOTESEC_BOOKSEC
			FOREIGN KEY (PUBLICATION_ID)
			REFERENCES BOOK_SECTION (PUBLICATION_ID)
) TABLESPACE UAM_DAT_1;
