CREATE TABLE FLUID_CONTAINER_HISTORY (
	CONTAINER_ID NUMBER NOT NULL,
	CHECKED_DATE DATE NOT NULL,
	FLUID_TYPE VARCHAR2(30) NOT NULL,
	CONCENTRATION NUMBER(2,2) NOT NULL,
	FLUID_REMARKS VARCHAR2(255),
		CONSTRAINT FK_FLUIDCONTHIST_CONTAINER
			FOREIGN KEY (CONTAINER_ID)
			REFERENCES CONTAINER (CONTAINER_ID),
		CONSTRAINT FK_FLUIDCONTHIST_CTFLUIDCONC
			FOREIGN KEY (CONCENTRATION)
			REFERENCES CTFLUID_CONCENTRATION (CONCENTRATION),
		CONSTRAINT FK_FLUIDCONTHIST_CTCTFLUIDTYPE
			FOREIGN KEY (FLUID_TYPE)
			REFERENCES CTFLUID_TYPE (FLUID_TYPE)
) TABLESPACE UAM_DAT_1;
