CREATE TABLE FORMATTED_PUBLICATION (
    PUBLICATION_ID NUMBER NOT NULL,
	FORMAT_STYLE VARCHAR2(25) NOT NULL,
	FORMATTED_PUBLICATION VARCHAR2(4000),
        CONSTRAINT FK_FORMATTEDPUB_PUBLICATION
            FOREIGN KEY (PUBLICATION_ID)
            REFERENCES PUBLICATION (PUBLICATION_ID)
            ON DELETE CASCADE
) TABLESPACE UAM_DAT_1;
