CREATE TABLE GEOG_AUTH_REC (
	GEOG_AUTH_REC_ID NUMBER NOT NULL,
	CONTINENT_OCEAN VARCHAR2(50),
	COUNTRY VARCHAR2(50),
	STATE_PROV VARCHAR2(75),
	COUNTY VARCHAR2(50),
	QUAD VARCHAR2(30),
	FEATURE VARCHAR2(50),
	ISLAND VARCHAR2(50),
	ISLAND_GROUP VARCHAR2(50),
	SEA VARCHAR2(50),
	VALID_CATALOG_TERM_FG NUMBER(3,0) NOT NULL,
	SOURCE_AUTHORITY VARCHAR2(45) NOT NULL,
	HIGHER_GEOG VARCHAR2(255),
		CONSTRAINT PK_GEOG_AUTH_REC
			PRIMARY KEY (GEOG_AUTH_REC_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_CTCONTINENT
			FOREIGN KEY (CONTINENT_OCEAN)
			REFERENCES CTCONTINENT (CONTINENT_OCEAN),
		CONSTRAINT FK_CTFEATURE
			FOREIGN KEY (FEATURE)
			REFERENCES CTFEATURE (FEATURE),
		CONSTRAINT FK_CTISLAND_GROUP
			FOREIGN KEY (ISLAND_GROUP)
			REFERENCES CTISLAND_GROUP (ISLAND_GROUP)
) TABLESPACE UAM_DAT_1;
