CREATE TABLE GEOLOGY_ATTRIBUTES (
	GEOLOGY_ATTRIBUTE_ID NUMBER NOT NULL,
	LOCALITY_ID NUMBER NOT NULL,
	GEOLOGY_ATTRIBUTE VARCHAR2(255) NOT NULL,
	GEO_ATT_VALUE VARCHAR2(255) NOT NULL,
	GEO_ATT_DETERMINER_ID NUMBER,
	GEO_ATT_DETERMINED_DATE DATE,
	GEO_ATT_DETERMINED_METHOD VARCHAR2(255),
	GEO_ATT_REMARK VARCHAR2(4000),
		CONSTRAINT PK_GEOLOGY_ATTRIBUTES
			PRIMARY KEY (GEOLOGY_ATTRIBUTE_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_GEOLATTRIBUTES_LOCALITY
			FOREIGN KEY (LOCALITY_ID)
			REFERENCES LOCALITY (LOCALITY_ID)
) TABLESPACE UAM_DAT_1;
