CREATE TABLE GEOLOGY_ATTRIBUTE_HIERARCHY (
	GEOLOGY_ATTRIBUTE_HIERARCHY_ID NUMBER NOT NULL,
	PARENT_ID NUMBER,
	ATTRIBUTE VARCHAR2(255) NOT NULL,
	ATTRIBUTE_VALUE VARCHAR2(255) NOT NULL,
	USABLE_VALUE_FG NUMBER NOT NULL,
	DESCRIPTION VARCHAR2(4000),
		CONSTRAINT PK_GEOLOGY_ATTRIBUTE_HIERARCHY
			PRIMARY KEY (GEOLOGY_ATTRIBUTE_HIERARCHY_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
        CONSTRAINT GEO_ATT_H_USABLE_CK
	         CHECK (usable_value_fg IN (0,1)),
		CONSTRAINT FK_GEOLATTRHIER_GEOLATTRHIER
			FOREIGN KEY (PARENT_ID)
			REFERENCES GEOLOGY_ATTRIBUTE_HIERARCHY (GEOLOGY_ATTRIBUTE_HIERARCHY_ID)
) TABLESPACE UAM_DAT_1;
