CREATE TABLE GROUP_MEMBER (
	GROUP_AGENT_ID NUMBER(*,0) NOT NULL,
	MEMBER_AGENT_ID NUMBER(*,0) NOT NULL,
	MEMBER_ORDER NUMBER(*,0) NOT NULL,
        CONSTRAINT PK_GROUP_MEMBER
            PRIMARY KEY (GROUP_AGENT_ID, MEMBER_AGENT_ID)
            USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_GROUPMEMBER_AGENT_GROUP
			FOREIGN KEY (GROUP_AGENT_ID)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_GROUPMEMBER_AGENT_MEMBER
			FOREIGN KEY (MEMBER_AGENT_ID)
			REFERENCES AGENT (AGENT_ID)
) TABLESPACE UAM_DAT_1;
