CREATE TABLE IDENTIFICATION_TAXONOMY (
	IDENTIFICATION_ID NUMBER NOT NULL,
	TAXON_NAME_ID NUMBER NOT NULL,
	VARIABLE CHAR(1),
        CONSTRAINT PK_IDENTIFICATION_TAXONOMY
            PRIMARY KEY (IDENTIFICATION_ID, TAXON_NAME_ID, VARIABLE)
            USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_IDTAXONOMY_IDENTIFICATION
			FOREIGN KEY (IDENTIFICATION_ID)
			REFERENCES IDENTIFICATION (IDENTIFICATION_ID),
		CONSTRAINT FK_CTTAXON_VARIABLE
			FOREIGN KEY (VARIABLE)
			REFERENCES CTTAXON_VARIABLE (TAXON_VARIABLE),
		CONSTRAINT FK_IDTAXONOMY_TAXONOMY
			FOREIGN KEY (TAXON_NAME_ID)
			REFERENCES TAXONOMY (TAXON_NAME_ID)
) TABLESPACE UAM_DAT_1;
