CREATE TABLE IDENTIFICATION_AGENT (
	IDENTIFICATION_ID NUMBER NOT NULL,
	AGENT_ID NUMBER NOT NULL,
	IDENTIFIER_ORDER NUMBER NOT NULL,
	IDENTIFICATION_AGENT_ID NUMBER,
		CONSTRAINT PK_IDENTIFICATION_AGENT
			PRIMARY KEY (IDENTIFICATION_AGENT_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_IDAGENT_AGENT
			FOREIGN KEY (AGENT_ID)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_IDAGENT_IDENTIFICATION
			FOREIGN KEY (IDENTIFICATION_ID)
			REFERENCES IDENTIFICATION (IDENTIFICATION_ID)
) TABLESPACE UAM_DAT_1;
