-- alter table identification modify taxa_formula varchar2(25);

CREATE TABLE IDENTIFICATION (
	IDENTIFICATION_ID NUMBER NOT NULL,
	COLLECTION_OBJECT_ID NUMBER NOT NULL,
	MADE_DATE DATE,
	NATURE_OF_ID VARCHAR2(30) NOT NULL,
	ACCEPTED_ID_FG NUMBER NOT NULL,
	IDENTIFICATION_REMARKS VARCHAR2(4000),
	TAXA_FORMULA VARCHAR2(25) NOT NULL,
	SCIENTIFIC_NAME VARCHAR2(255) NOT NULL,
		CONSTRAINT PK_IDENTIFICATION
			PRIMARY KEY (IDENTIFICATION_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_IDENTIFICATION_CATITEM
			FOREIGN KEY (COLLECTION_OBJECT_ID)
			REFERENCES CATALOGED_ITEM (COLLECTION_OBJECT_ID),
		CONSTRAINT FK_CTNATURE_OF_ID
			FOREIGN KEY (NATURE_OF_ID)
			REFERENCES CTNATURE_OF_ID (NATURE_OF_ID),
		CONSTRAINT FK_CTTAXA_FORMULA
			FOREIGN KEY (TAXA_FORMULA)
			REFERENCES CTTAXA_FORMULA (TAXA_FORMULA)
) TABLESPACE UAM_DAT_1;
