CREATE TABLE JOURNAL_ARTICLE (
	PUBLICATION_ID NUMBER NOT NULL,
	JOURNAL_ID NUMBER,
	BEGINS_PAGE_NUMBER NUMBER(*,0),
	ENDS_PAGE_NUMBER NUMBER(*,0),
	VOLUME_NUMBER NUMBER(*,0),
	ISSUE_NUMBER NUMBER(*,0),
		CONSTRAINT PK_JOURNAL_ARTICLE
			PRIMARY KEY (PUBLICATION_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_JOURNALARTICLE_JOURNAL
			FOREIGN KEY (JOURNAL_ID)
			REFERENCES JOURNAL (JOURNAL_ID)
) TABLESPACE UAM_DAT_1;
