CREATE TABLE JOURNAL (
	JOURNAL_ID NUMBER NOT NULL,
	JOURNAL_ABBREVIATION VARCHAR2(50) NOT NULL,
	PUBLISHER_NAME VARCHAR2(127),
	JOURNAL_NAME VARCHAR2(150) NOT NULL,
		CONSTRAINT PK_JOURNAL
			PRIMARY KEY (JOURNAL_ID)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;
