-- alter table lat_long modify MAX_ERROR_DISTANCE number null;
-- alter table lat_long modify MAX_ERROR_UNITS VARCHAR2(2) null;

CREATE TABLE LAT_LONG (
	LAT_LONG_ID NUMBER NOT NULL,
	LOCALITY_ID NUMBER NOT NULL,
	LAT_DEG NUMBER,
	DEC_LAT_MIN NUMBER(8,6),
	LAT_MIN NUMBER,
	LAT_SEC NUMBER(8,6),
	LAT_DIR CHAR(1),
	LONG_DEG NUMBER,
	DEC_LONG_MIN NUMBER(10,8),
	LONG_MIN NUMBER,
	LONG_SEC NUMBER(8,6),
	LONG_DIR CHAR(1),
	DEC_LAT NUMBER(12,10),
	DEC_LONG NUMBER(13,10),
	DATUM VARCHAR2(55) NOT NULL,
	UTM_ZONE VARCHAR2(3),
	UTM_EW NUMBER,
	UTM_NS NUMBER,
	ORIG_LAT_LONG_UNITS VARCHAR2(20) NOT NULL,
	DETERMINED_BY_AGENT_ID NUMBER NOT NULL,
	DETERMINED_DATE DATE NOT NULL,
	LAT_LONG_REF_SOURCE VARCHAR2(255) NOT NULL,
	LAT_LONG_REMARKS VARCHAR2(4000),
	MAX_ERROR_DISTANCE NUMBER,
	MAX_ERROR_UNITS VARCHAR2(2),
	NEAREST_NAMED_PLACE VARCHAR2(255),
	LAT_LONG_FOR_NNP_FG NUMBER,
	FIELD_VERIFIED_FG NUMBER,
	ACCEPTED_LAT_LONG_FG NUMBER NOT NULL,
	EXTENT NUMBER(8,3),
	GPSACCURACY NUMBER(8,3),
	GEOREFMETHOD VARCHAR2(255) NOT NULL,
	VERIFICATIONSTATUS VARCHAR2(40) NOT NULL,
	SPATIALFIT NUMBER(4,3),
		CONSTRAINT PK_LAT_LONG
		    PRIMARY KEY (LAT_LONG_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
        CONSTRAINT DEC_LAT_RANGE
            CHECK (dec_lat BETWEEN -90 AND 90),
        CONSTRAINT DEC_LONG_RANGE
            CHECK (dec_long BETWEEN -180 AND 180),
		CONSTRAINT LAT_DEG_RANGE 
		    CHECK (lat_deg BETWEEN 0 AND 90),
		CONSTRAINT DEC_LAT_MIN_RANGE 
	        CHECK (DEC_LAT_MIN >= 0 AND DEC_LAT_MIN < 60),
		CONSTRAINT LAT_MIN_RANGE 
		    CHECK (LAT_MIN >= 0 AND LAT_MIN < 60),
		CONSTRAINT LAT_SEC_RANGE 
        	CHECK (LAT_SEC >= 0 AND LAT_SEC < 60),
		CONSTRAINT LAT_DIR_RANGE 
        	CHECK (LAT_DIR IN ('N','S')),
		CONSTRAINT LONG_DEG_RANGE 
			CHECK (LONG_DEG BETWEEN 0 AND 180),
		CONSTRAINT DEC_LONG_MIN_RANGE 
			CHECK (DEC_LONG_MIN >= 0 AND DEC_LONG_MIN < 60),
		CONSTRAINT LONG_MIN_RANGE 
			CHECK (LONG_MIN >= 0 AND LONG_MIN < 60),
		CONSTRAINT LONG_SEC_RANGE 
			CHECK (LONG_SEC >= 0 AND LONG_SEC < 60),
		CONSTRAINT ACCEPTED_LAT_LONG_FG_RANGE 
			CHECK (ACCEPTED_LAT_LONG_FG IN (0,1)),
		CONSTRAINT FK_LATLONG_AGENT
			FOREIGN KEY (DETERMINED_BY_AGENT_ID)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_LATLONG_LOCALITY
			FOREIGN KEY (LOCALITY_ID)
			REFERENCES LOCALITY (LOCALITY_ID),
		CONSTRAINT FK_CTDATUM
			FOREIGN KEY (DATUM)
			REFERENCES CTDATUM (DATUM),
		CONSTRAINT FK_CTEW
			FOREIGN KEY (LONG_DIR)
			REFERENCES CTEW (E_OR_W),
		CONSTRAINT FK_CTGEOREFMETHOD
			FOREIGN KEY (GEOREFMETHOD)
			REFERENCES CTGEOREFMETHOD (GEOREFMETHOD),
		CONSTRAINT FK_CTLAT_LONG_ERROR_UNITS
			FOREIGN KEY (MAX_ERROR_UNITS)
			REFERENCES CTLAT_LONG_ERROR_UNITS (LAT_LONG_ERROR_UNITS),
		CONSTRAINT FK_CTLAT_LONG_UNITS
			FOREIGN KEY (ORIG_LAT_LONG_UNITS)
			REFERENCES CTLAT_LONG_UNITS (ORIG_LAT_LONG_UNITS),
		CONSTRAINT FK_CTNS
			FOREIGN KEY (LAT_DIR)
			REFERENCES CTNS (N_OR_S),
		CONSTRAINT FK_CTVERIFICATIONSTATUS
			FOREIGN KEY (VERIFICATIONSTATUS)
			REFERENCES CTVERIFICATIONSTATUS (VERIFICATIONSTATUS)
) TABLESPACE UAM_DAT_1;
