CREATE TABLE LOAN_ITEM (
    TRANSACTION_ID NUMBER NOT NULL ENABLE,
	COLLECTION_OBJECT_ID NUMBER NOT NULL ENABLE,
	RECONCILED_BY_PERSON_ID NUMBER NOT NULL ENABLE,
	RECONCILED_DATE DATE,
	ITEM_DESCR VARCHAR2(127) NOT NULL ENABLE,
	ITEM_INSTRUCTIONS VARCHAR2(255),
	LOAN_ITEM_REMARKS VARCHAR2(255),
		CONSTRAINT PK_LOAN_ITEM 
			PRIMARY KEY (TRANSACTION_ID, COLLECTION_OBJECT_ID)
			USING INDEX TABLESPACE UAM_IDX_1 ENABLE,
		CONSTRAINT FK_LOANITEM_LOAN
			FOREIGN KEY (TRANSACTION_ID)
			REFERENCES LOAN (TRANSACTION_ID) ENABLE,
		CONSTRAINT FK_LOANITEM_PERSON
			FOREIGN KEY (RECONCILED_BY_PERSON_ID)
			REFERENCES PERSON (PERSON_ID) ENABLE,
		CONSTRAINT FK_LOANITEM_SPECIMENPART
			FOREIGN KEY (COLLECTION_OBJECT_ID)
			REFERENCES SPECIMEN_PART (COLLECTION_OBJECT_ID) ENABLE
) TABLESPACE UAM_DAT_1
