CREATE TABLE LOAN (
	TRANSACTION_ID NUMBER NOT NULL,
	LOAN_TYPE VARCHAR2(25),
	LOAN_NUM_PREFIX VARCHAR2(10),
	LOAN_NUM NUMBER,
	LOAN_NUM_SUFFIX VARCHAR2(10),
	LOAN_STATUS VARCHAR2(20) NOT NULL,
	LOAN_INSTRUCTIONS VARCHAR2(4000),
	RETURN_DUE_DATE DATE,
	LOAN_DESCRIPTION VARCHAR2(4000),
	LOAN_NUMBER VARCHAR2(255) NOT NULL,
		CONSTRAINT PK_LOAN
			PRIMARY KEY (TRANSACTION_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_LOAN_TRANS
			FOREIGN KEY (TRANSACTION_ID)
			REFERENCES TRANS (TRANSACTION_ID),
		CONSTRAINT FK_CTLOAN_STATUS
			FOREIGN KEY (LOAN_STATUS)
			REFERENCES CTLOAN_STATUS (LOAN_STATUS),
		CONSTRAINT FK_CTLOAN_TYPE
			FOREIGN KEY (LOAN_TYPE)
			REFERENCES CTLOAN_TYPE (LOAN_TYPE)
) TABLESPACE UAM_DAT_1;
