CREATE TABLE MEDIA (
	MEDIA_ID NUMBER NOT NULL,
	MEDIA_URI VARCHAR2(255) NOT NULL,
	MIME_TYPE VARCHAR2(255) NOT NULL,
	MEDIA_TYPE VARCHAR2(255) NOT NULL,
	PREVIEW_URI VARCHAR2(255),
		CONSTRAINT PK_MEDIA
			PRIMARY KEY (MEDIA_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_MEDIA_CTMIMETYPE
			FOREIGN KEY (MIME_TYPE)
			REFERENCES CTMIME_TYPE (MIME_TYPE),
		CONSTRAINT FK_CTMEDIA_TYPE
			FOREIGN KEY (MEDIA_TYPE)
			REFERENCES CTMEDIA_TYPE (MEDIA_TYPE)
) TABLESPACE UAM_DAT_1;
