CREATE TABLE MEDIA_RELATIONS (
	MEDIA_RELATIONS_ID NUMBER NOT NULL,
	MEDIA_ID NUMBER NOT NULL,
	MEDIA_RELATIONSHIP VARCHAR2(40) NOT NULL,
	CREATED_BY_AGENT_ID NUMBER NOT NULL,
	RELATED_PRIMARY_KEY NUMBER NOT NULL,
		CONSTRAINT PK_MEDIA_RELATIONS
			PRIMARY KEY (MEDIA_RELATIONS_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_MEDIARELNS_AGENT
			FOREIGN KEY (CREATED_BY_AGENT_ID)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_MEDIARELNS_CTMEDIARELNS
			FOREIGN KEY (MEDIA_RELATIONSHIP)
			REFERENCES CTMEDIA_RELATIONSHIP (MEDIA_RELATIONSHIP),
		CONSTRAINT FK_MEDIARELNS_MEDIA
			FOREIGN KEY (MEDIA_ID)
			REFERENCES MEDIA (MEDIA_ID)
) TABLESPACE UAM_DAT_1;
