CREATE TABLE OBJECT_CONDITION (
	OBJECT_CONDITION_ID NUMBER NOT NULL,
	COLLECTION_OBJECT_ID NUMBER NOT NULL,
	DETERMINED_AGENT_ID NUMBER NOT NULL,
	CONDITION VARCHAR2(4000) NOT NULL,
	DETERMINED_DATE DATE NOT NULL,
		CONSTRAINT PK_OBJECT_CONDITION
			PRIMARY KEY (OBJECT_CONDITION_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_OBJECTCONDITION_AGENT
			FOREIGN KEY (DETERMINED_AGENT_ID)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_OBJECTCONDITION_COLLOBJECT
			FOREIGN KEY (COLLECTION_OBJECT_ID)
			REFERENCES COLL_OBJECT (COLLECTION_OBJECT_ID) ON DELETE CASCADE
) TABLESPACE UAM_DAT_1 ENABLE ROW MOVEMENT;
