CREATE TABLE PAGE (
	PAGE_ID NUMBER(10,0) NOT NULL,
	PUBLICATION_ID NUMBER(10,0) NOT NULL,
	SECTION_PAGE_ORDER NUMBER(10,0) NOT NULL,
	PAGE_NUM VARCHAR2(20),
		CONSTRAINT PK_PAGE
			PRIMARY KEY (PAGE_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_PAGE_PUBLICATION
			FOREIGN KEY (PUBLICATION_ID)
			REFERENCES PUBLICATION (PUBLICATION_ID)
) TABLESPACE UAM_DAT_1;
