CREATE TABLE PERMIT_TRANS (
	PERMIT_ID NUMBER NOT NULL,
	TRANSACTION_ID NUMBER NOT NULL,
		CONSTRAINT PK_PERMIT_TRANS
			PRIMARY KEY (PERMIT_ID, TRANSACTION_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_PERMITTRANS_PERMIT
			FOREIGN KEY (PERMIT_ID)
			REFERENCES PERMIT (PERMIT_ID),
		CONSTRAINT FK_PERMITTRANS_TRANS
			FOREIGN KEY (TRANSACTION_ID)
			REFERENCES TRANS (TRANSACTION_ID)
) TABLESPACE UAM_DAT_1;
