CREATE TABLE PERMIT (
	PERMIT_ID NUMBER NOT NULL,
	ISSUED_BY_AGENT_ID NUMBER NOT NULL,
	ISSUED_DATE DATE,
	ISSUED_TO_AGENT_ID NUMBER NOT NULL,
	RENEWED_DATE DATE,
	EXP_DATE DATE,
	PERMIT_NUM VARCHAR2(25),
	PERMIT_TYPE VARCHAR2(50) NOT NULL,
	PERMIT_REMARKS VARCHAR2(300),
	CONTACT_AGENT_ID NUMBER,
		CONSTRAINT PK_PERMIT
			PRIMARY KEY (PERMIT_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_PERMIT_AGENT_CONTACT
			FOREIGN KEY (CONTACT_AGENT_ID)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_PERMIT_AGENT_ISSUEDBY
			FOREIGN KEY (ISSUED_BY_AGENT_ID)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_PERMIT_AGENT_ISSUEDTO
			FOREIGN KEY (ISSUED_TO_AGENT_ID)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_CTPERMIT_TYPE
			FOREIGN KEY (PERMIT_TYPE)
			REFERENCES CTPERMIT_TYPE (PERMIT_TYPE)
) TABLESPACE UAM_DAT_1;
