CREATE TABLE PERSON (
	PERSON_ID NUMBER NOT NULL,
	PREFIX VARCHAR2(20),
	LAST_NAME VARCHAR2(60) NOT NULL,
	FIRST_NAME VARCHAR2(40),
	MIDDLE_NAME VARCHAR2(40),
	SUFFIX VARCHAR2(20),
	BIRTH_DATE DATE,
	DEATH_DATE DATE,
		CONSTRAINT PK_PERSON
			PRIMARY KEY (PERSON_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_PERSON_AGENT
			FOREIGN KEY (PERSON_ID)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_CTPREFIX
			FOREIGN KEY (PREFIX)
			REFERENCES CTPREFIX (PREFIX),
		CONSTRAINT FK_CTSUFFIX
			FOREIGN KEY (SUFFIX)
			REFERENCES CTSUFFIX (SUFFIX)
) TABLESPACE UAM_DAT_1;
