CREATE TABLE PROJECT_TRANS (
	PROJECT_ID NUMBER NOT NULL,
	TRANSACTION_ID NUMBER NOT NULL,
	PROJECT_TRANS_REMARKS VARCHAR2(255),
	    CONSTRAINT PK_PROJECT_TRANS
            PRIMARY KEY (PROJECT_ID, TRANSACTION_ID)
            USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_PROJECTTRANS_PROJECT
			FOREIGN KEY (PROJECT_ID)
			REFERENCES PROJECT (PROJECT_ID),
		CONSTRAINT FK_PROJECTTRANS_TRANS
			FOREIGN KEY (TRANSACTION_ID)
			REFERENCES TRANS (TRANSACTION_ID)
) TABLESPACE UAM_DAT_1;
