CREATE TABLE PROJECT_PUBLICATION (
	PROJECT_ID NUMBER NOT NULL,
	PUBLICATION_ID NUMBER NOT NULL,
	PROJECT_PUBLICATION_REMARKS VARCHAR2(255),
	    CONSTRAINT PK_PROJECT_PUBLICATION
            PRIMARY KEY (PROJECT_ID, PUBLICATION_ID)
            USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_PROJECTPUB_PROJECT
			FOREIGN KEY (PROJECT_ID)
			REFERENCES PROJECT (PROJECT_ID),
		CONSTRAINT FK_PROJECTPUB_PUBLICATION
			FOREIGN KEY (PUBLICATION_ID)
			REFERENCES PUBLICATION (PUBLICATION_ID)
) TABLESPACE UAM_DAT_1;
