CREATE TABLE PROJECT_SPONSOR (
	PROJECT_SPONSOR_ID NUMBER NOT NULL,
	PROJECT_ID NUMBER NOT NULL,
	AGENT_NAME_ID NUMBER NOT NULL,
	ACKNOWLEDGEMENT VARCHAR2(255),
		CONSTRAINT PK_PROJECT_SPONSOR
			PRIMARY KEY (PROJECT_SPONSOR_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_PROJECTSPONSOR_AGENTNAME
			FOREIGN KEY (AGENT_NAME_ID)
			REFERENCES AGENT_NAME (AGENT_NAME_ID),
		CONSTRAINT FK_PROJECTSPONSOR_PROJECT
			FOREIGN KEY (PROJECT_ID)
			REFERENCES PROJECT (PROJECT_ID)
) TABLESPACE UAM_DAT_1;
