CREATE TABLE PROJECT_AGENT (
	PROJECT_ID NUMBER NOT NULL,
	AGENT_NAME_ID NUMBER NOT NULL,
	PROJECT_AGENT_ROLE VARCHAR2(25) NOT NULL,
	PROJECT_AGENT_REMARKS VARCHAR2(255),
	AGENT_POSITION NUMBER NOT NULL,
        CONSTRAINT PK_PROJECT_AGENT
            PRIMARY KEY (PROJECT_ID, AGENT_NAME_ID, PROJECT_AGENT_ROLE)
            USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_PROJECTAGENT_AGENTNAME
			FOREIGN KEY (AGENT_NAME_ID)
			REFERENCES AGENT_NAME (AGENT_NAME_ID),
		CONSTRAINT FK_PROJECTAGENT_PROJECT
			FOREIGN KEY (PROJECT_ID)
			REFERENCES PROJECT (PROJECT_ID),
		CONSTRAINT FK_CTPROJECT_AGENT_ROLE
			FOREIGN KEY (PROJECT_AGENT_ROLE)
			REFERENCES CTPROJECT_AGENT_ROLE (PROJECT_AGENT_ROLE)
) TABLESPACE UAM_DAT_1;
