CREATE TABLE PUBLICATION_URL (
	PUBLICATION_ID NUMBER NOT NULL,
	DESCRIPTION VARCHAR2(255) NOT NULL,
	PUBLICATION_URL_ID NUMBER NOT NULL,
	LINK VARCHAR2(4000) NOT NULL,
		CONSTRAINT PK_PUBLICATION_URL
			PRIMARY KEY (PUBLICATION_URL_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_PUBLICATIONURL_PUBLICATION
			FOREIGN KEY (PUBLICATION_ID)
			REFERENCES PUBLICATION (PUBLICATION_ID)
) TABLESPACE UAM_DAT_1;
