CREATE TABLE PUBLICATION (
	PUBLICATION_ID NUMBER NOT NULL,
	PUBLISHED_YEAR NUMBER,
	PUBLICATION_TYPE VARCHAR2(21) NOT NULL,
	PUBLICATION_LOC VARCHAR2(25),
	PUBLICATION_TITLE VARCHAR2(4000) NOT NULL,
	PUBLICATION_REMARKS VARCHAR2(255),
	IS_PEER_REVIEWED_FG NUMBER(1,0) NOT NULL,
		CONSTRAINT PK_PUBLICATION
		    PRIMARY KEY (PUBLICATION_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
        CONSTRAINT CK_PEER_FLAG
            CHECK (is_peer_reviewed_fg IN (0,1)),
		CONSTRAINT FK_CTPUBLICATION_TYPE
			FOREIGN KEY (PUBLICATION_TYPE)
			REFERENCES CTPUBLICATION_TYPE (PUBLICATION_TYPE)
) TABLESPACE UAM_DAT_1;
