CREATE TABLE PUBLICATION_AUTHOR_NAME (
	PUBLICATION_ID NUMBER NOT NULL,
	AGENT_NAME_ID NUMBER NOT NULL,
	AUTHOR_POSITION NUMBER NOT NULL,
	AUTHOR_ROLE VARCHAR2(60) NOT NULL,
	PUBLICATION_AUTHOR_NAME_ID NUMBER NOT NULL,
		CONSTRAINT PK_PUBLICATION_AUTHOR_NAME
			PRIMARY KEY (PUBLICATION_AUTHOR_NAME_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_PUBAUTHNAME_AGENTNAME
			FOREIGN KEY (AGENT_NAME_ID)
			REFERENCES AGENT_NAME (AGENT_NAME_ID),
		CONSTRAINT FK_PUBAUTHNAME_PUBLICATION
			FOREIGN KEY (PUBLICATION_ID)
			REFERENCES PUBLICATION (PUBLICATION_ID),
		CONSTRAINT FK_AUTHOR_ROLE
			FOREIGN KEY (AUTHOR_ROLE)
			REFERENCES CTAUTHOR_ROLE (AUTHOR_ROLE)
) TABLESPACE UAM_DAT_1;
