CREATE TABLE PUBLICATION_ATTRIBUTES (
	PUBLICATION_ATTRIBUTE_ID NUMBER NOT NULL,
	PUBLICATION_ID NUMBER NOT NULL,
	PUBLICATION_ATTRIBUTE VARCHAR2(60) NOT NULL,
	PUB_ATT_VALUE VARCHAR2(4000) NOT NULL,
		CONSTRAINT PK_PUBLICATION_ATTRIBUTES
			PRIMARY KEY (PUBLICATION_ATTRIBUTE_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_PUBATTR_CTPUBATTR
			FOREIGN KEY (PUBLICATION_ATTRIBUTE)
			REFERENCES CTPUBLICATION_ATTRIBUTE (PUBLICATION_ATTRIBUTE)
		CONSTRAINT FK_PUBATTR_PUBLICATION
		    FOREIGN KEY (PUBLICATION_ID)
            REFERENCES PUBLICATION (PUBLICATION_ID)
) TABLESPACE UAM_DAT_1;
