CREATE TABLE SHIPMENT (
	CONTAINER_ID NUMBER,
	TRANSACTION_ID NUMBER NOT NULL,
	PACKED_BY_AGENT_ID NUMBER NOT NULL,
	SHIPPED_CARRIER_METHOD VARCHAR2(25) NOT NULL,
	CARRIERS_TRACKING_NUMBER VARCHAR2(20),
	SHIPPED_DATE DATE,
	PACKAGE_WEIGHT VARCHAR2(10),
	HAZMAT_FG NUMBER(1,0) NOT NULL,
	INSURED_FOR_INSURED_VALUE NUMBER,
	SHIPMENT_REMARKS VARCHAR2(255),
	CONTENTS VARCHAR2(255),
	FOREIGN_SHIPMENT_FG NUMBER(1,0) NOT NULL,
	SHIPPED_TO_ADDR_ID NUMBER NOT NULL,
	SHIPPED_FROM_ADDR_ID NUMBER NOT NULL,
		CONSTRAINT FK_SHIPMENT_ADDR_SHIPPEDFROM
			FOREIGN KEY (SHIPPED_FROM_ADDR_ID)
			REFERENCES ADDR (ADDR_ID),
		CONSTRAINT FK_SHIPMENT_ADDR_SHIPPEDTO
			FOREIGN KEY (SHIPPED_TO_ADDR_ID)
			REFERENCES ADDR (ADDR_ID),
		CONSTRAINT FK_SHIPMENT_AGENT
			FOREIGN KEY (PACKED_BY_AGENT_ID)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_SHIPMENT_CONTAINER
			FOREIGN KEY (CONTAINER_ID)
			REFERENCES CONTAINER (CONTAINER_ID),
		CONSTRAINT FK_SHIPMENT_TRANS
			FOREIGN KEY (TRANSACTION_ID)
			REFERENCES TRANS (TRANSACTION_ID),
		CONSTRAINT FK_CTSHIPPED_CARRIER_METHOD
			FOREIGN KEY (SHIPPED_CARRIER_METHOD)
			REFERENCES CTSHIPPED_CARRIER_METHOD (SHIPPED_CARRIER_METHOD)
) TABLESPACE UAM_DAT_1;
