CREATE TABLE SPECIMEN_PART (
    COLLECTION_OBJECT_ID NUMBER NOT NULL ENABLE,
	PART_NAME VARCHAR2(255) NOT NULL ENABLE,
	SAMPLED_FROM_OBJ_ID NUMBER,
	DERIVED_FROM_CAT_ITEM NUMBER NOT NULL ENABLE,
	CONSTRAINT PK_SPECIMEN_PART
		PRIMARY KEY (COLLECTION_OBJECT_ID)
		USING INDEX TABLESPACE UAM_IDX_1  ENABLE,
	CONSTRAINT CK_SPECIMENPART_NOTSAMPFRSELF 
		CHECK (SAMPLED_FROM_OBJ_ID != COLLECTION_OBJECT_ID) ENABLE,
	CONSTRAINT FK_SPECIMENPART_CATITEM
		FOREIGN KEY (DERIVED_FROM_CAT_ITEM)
		REFERENCES CATALOGED_ITEM (COLLECTION_OBJECT_ID) ENABLE,
	CONSTRAINT FK_SPECIMENPART_COLLOBJECT
		FOREIGN KEY (COLLECTION_OBJECT_ID)
		REFERENCES COLL_OBJECT (COLLECTION_OBJECT_ID) ENABLE,
	CONSTRAINT FK_SPECIMENPART_SPECIMENPART
		FOREIGN KEY (SAMPLED_FROM_OBJ_ID)
		REFERENCES SPECIMEN_PART (COLLECTION_OBJECT_ID) ENABLE
) TABLESPACE UAM_DAT_1;