CREATE TABLE TAG (
    TAG_ID NUMBER NOT NULL,
    MEDIA_ID NUMBER NOT NULL,
    REMARK VARCHAR2(4000),
    REFTOP NUMBER,
	REFLEFT NUMBER,
	REFH NUMBER,
	REFW NUMBER,
	IMGH NUMBER,
	IMGW NUMBER,
	COLLECTION_OBJECT_ID NUMBER,
	COLLECTING_EVENT_ID NUMBER,
	LOCALITY_ID NUMBER,
	AGENT_ID NUMBER,
        CONSTRAINT PK_TAG
            PRIMARY KEY (TAG_ID)
            USING INDEX TABLESPACE UAM_IDX_1,
        CONSTRAINT FK_TAG_MEDIA
            FOREIGN KEY (MEDIA_ID)
            REFERENCES MEDIA (MEDIA_ID),
        CONSTRAINT FK_TAG_CATITEM
            FOREIGN KEY (COLLECTION_OBJECT_ID)
		    REFERENCES CATALOGED_ITEM (COLLECTION_OBJECT_ID),
        CONSTRAINT FK_TAG_COLLEVENT
            FOREIGN KEY (COLLECTING_EVENT_ID)
			REFERENCES COLLECTING_EVENT (COLLECTING_EVENT_ID),
		CONSTRAINT FK_TAG_LOCALITY
		    FOREIGN KEY (LOCALITY_ID)
			REFERENCES LOCALITY (LOCALITY_ID),
		CONSTRAINT FK_TAG_AGENT
		    FOREIGN KEY (AGENT_ID)
            REFERENCES AGENT (AGENT_ID)
) TABLESPACE UAM_DAT_1;
