CREATE TABLE TAXONOMY (
	TAXON_NAME_ID NUMBER NOT NULL,
	PHYLCLASS VARCHAR2(20),
	PHYLORDER VARCHAR2(30),
	SUBORDER VARCHAR2(30),
	FAMILY VARCHAR2(30),
	SUBFAMILY VARCHAR2(30),
	GENUS VARCHAR2(30),
	SUBGENUS VARCHAR2(20),
	SPECIES VARCHAR2(40),
	SUBSPECIES VARCHAR2(40),
	VALID_CATALOG_TERM_FG NUMBER NOT NULL,
	SOURCE_AUTHORITY VARCHAR2(45) NOT NULL,
	FULL_TAXON_NAME VARCHAR2(4000) NOT NULL,
	SCIENTIFIC_NAME VARCHAR2(255) NOT NULL,
	AUTHOR_TEXT VARCHAR2(255),
	TRIBE VARCHAR2(30),
	INFRASPECIFIC_RANK VARCHAR2(20),
	TAXON_REMARKS VARCHAR2(4000),
	PHYLUM VARCHAR2(30),
	KINGDOM VARCHAR2(255),
	NOMENCLATURAL_CODE VARCHAR2(255) NOT NULL,
	INFRASPECIFIC_AUTHOR VARCHAR2(255),
	SUBCLASS VARCHAR2(255),
	SUPERFAMILY VARCHAR2(255),
	DISPLAY_NAME VARCHAR2(255),
		CONSTRAINT PK_TAXONOMY
			PRIMARY KEY (TAXON_NAME_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_CTINFRASPECIFIC_RANK
			FOREIGN KEY (INFRASPECIFIC_RANK)
			REFERENCES CTINFRASPECIFIC_RANK (INFRASPECIFIC_RANK),
		CONSTRAINT FK_CTTAXONOMIC_AUTHORITY
			FOREIGN KEY (SOURCE_AUTHORITY)
			REFERENCES CTTAXONOMIC_AUTHORITY (SOURCE_AUTHORITY),
		CONSTRAINT FK_CTNOMENCLATURAL_CODE
			FOREIGN KEY (NOMENCLATURAL_CODE)
			REFERENCES CTNOMENCLATURAL_CODE (NOMENCLATURAL_CODE)
) TABLESPACE UAM_DAT_1;
