CREATE TABLE TAXON_RELATIONS (
	TAXON_NAME_ID NUMBER(10,0) NOT NULL,
	RELATED_TAXON_NAME_ID NUMBER(10,0) NOT NULL,
	TAXON_RELATIONSHIP VARCHAR2(50) NOT NULL,
	RELATION_AUTHORITY VARCHAR2(45),
		CONSTRAINT PK_TAXON_RELATIONS
			PRIMARY KEY (TAXON_NAME_ID, RELATED_TAXON_NAME_ID, TAXON_RELATIONSHIP)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_CTTAXON_RELATION
			FOREIGN KEY (TAXON_RELATIONSHIP)
			REFERENCES CTTAXON_RELATION (TAXON_RELATIONSHIP),
		CONSTRAINT FK_TAXONRELN_TAXONOMY_RTNID
			FOREIGN KEY (RELATED_TAXON_NAME_ID)
			REFERENCES TAXONOMY (TAXON_NAME_ID),
		CONSTRAINT FK_TAXONRELN_TAXONOMY_TNID
			FOREIGN KEY (TAXON_NAME_ID)
			REFERENCES TAXONOMY (TAXON_NAME_ID)
) TABLESPACE UAM_DAT_1;
