CREATE TABLE TRANS (
	TRANSACTION_ID NUMBER NOT NULL,
	AUTH_AGENT_ID NUMBER,
	TRANS_DATE DATE,
	TRANS_ENTERED_AGENT_ID NUMBER,
	RECEIVED_AGENT_ID NUMBER,
	CORRESP_FG NUMBER,
	TRANSACTION_TYPE VARCHAR2(18) NOT NULL,
	NATURE_OF_MATERIAL VARCHAR2(4000) NOT NULL,
	TRANS_REMARKS VARCHAR2(4000),
	INSTITUTION_ACRONYM VARCHAR2(20),
	TRANS_AGENCY_ID NUMBER,
	COLLECTION_ID NUMBER NOT NULL,
		CONSTRAINT PK_TRANS
			PRIMARY KEY (TRANSACTION_ID)
			USING INDEX TABLESPACE UAM_IDX_1,
        CONSTRAINT TRANS_TRANSACTION_TYPE
            CHECK (TRANSACTION_TYPE IN ('accn','loan','borrow')),
        CONSTRAINT TRANS_CORRESP_FG
            CHECK (CORRESP_FG IN (0,1)),
		CONSTRAINT FK_TRANS_COLLECTION
			FOREIGN KEY (COLLECTION_ID)
			REFERENCES COLLECTION (COLLECTION_ID),
		CONSTRAINT FK_CTTRANSACTION_TYPE
			FOREIGN KEY (TRANSACTION_TYPE)
			REFERENCES CTTRANSACTION_TYPE (TRANSACTION_TYPE)
) TABLESPACE UAM_DAT_1;
