/*
select 'grant ' || privilege || ' on ' || TABLE_NAME || ' to ' || grantee || ';'
from dba_tab_privs tp, dba_objects o
where tp.TABLE_NAME = o.object_name
and tp.owner = 'UAM'
and o.owner = 'UAM'
and object_type = 'FUNCTION'
order by table_name, grantee, privilege
*/

grant EXECUTE on ALL_TAXON_NAMES to PUBLIC;
grant EXECUTE on ATC to PUBLIC;
grant EXECUTE on AUTHYEAR to PUBLIC;
grant EXECUTE on AY to PUBLIC;
grant EXECUTE on BUILDSCIENTIFICNAME to PUBLIC;
grant EXECUTE on BULK_CHECK_ONE to PUBLIC;
grant EXECUTE on B_CONCATGEOLOGYATTRIBUTEDETAIL to PUBLIC;
grant EXECUTE on CHECKCONTAINERMOVEMENT to PUBLIC;
grant EXECUTE on CONCATACCEPTEDIDENTIFYINGAGENT to PUBLIC;
grant EXECUTE on CONCATALLIDENTIFICATION to PUBLIC;
grant EXECUTE on CONCATATTRIBUTE to PUBLIC;
grant EXECUTE on CONCATATTRIBUTE to UAM_QUERY;
grant EXECUTE on CONCATATTRIBUTEDETAIL to PUBLIC;
grant EXECUTE on CONCATATTRIBUTEDETAIL to UAM_QUERY;
grant EXECUTE on CONCATATTRIBUTEVALUE to PUBLIC;
grant EXECUTE on CONCATATTRIBUTEVALUE to UAM_QUERY;
grant EXECUTE on CONCATCOLL to PUBLIC;
grant EXECUTE on CONCATCOLL to UAM_QUERY;
grant EXECUTE on CONCATCOLLS to PUBLIC;
grant EXECUTE on CONCATCOLLS to UAM_QUERY;
grant EXECUTE on CONCATCOLLW_NUM to PUBLIC;
grant EXECUTE on CONCATCOMMONNAME to PUBLIC;
grant EXECUTE on CONCATCOMMONNAME to UAM_QUERY;
grant EXECUTE on CONCATDARWINRELATIONS to PUBLIC;
grant EXECUTE on CONCATENCUMBRANCEDETAILS to PUBLIC;
grant EXECUTE on CONCATENCUMBRANCEDETAILS to UAM_QUERY;
grant EXECUTE on CONCATENCUMBRANCES to PUBLIC;
grant EXECUTE on CONCATENCUMBRANCES to UAM_QUERY;
grant EXECUTE on CONCATGENBANK to PUBLIC;
grant EXECUTE on CONCATGENBANK to UAM_QUERY;
grant EXECUTE on CONCATGEOLOGYATTRIBUTE to PUBLIC;
grant EXECUTE on CONCATGEOLOGYATTRIBUTEDETAIL to PUBLIC;
grant EXECUTE on CONCATIDAGENT to PUBLIC;
grant EXECUTE on CONCATIDENTIFIERS to PUBLIC;
grant EXECUTE on CONCATIDENTIFYINGAGENT to PUBLIC;
grant EXECUTE on CONCATIDRBYIDID to PUBLIC;
grant EXECUTE on CONCATIMAGEURL to PUBLIC;
grant EXECUTE on CONCATNAME to PUBLIC;
grant EXECUTE on CONCATORIGLAT to PUBLIC;
grant EXECUTE on CONCATORIGLATLONG to PUBLIC;
grant EXECUTE on CONCATORIGLATLONG to UAM_QUERY;
grant EXECUTE on CONCATOTHERID to PUBLIC;
grant EXECUTE on CONCATOTHERID to UAM_QUERY;
grant EXECUTE on CONCATOTHERIDFILT to PUBLIC;
grant EXECUTE on CONCATOTHERIDFILT to UAM_QUERY;
grant EXECUTE on CONCATPARTNAME to PUBLIC;
grant EXECUTE on CONCATPARTNAME to UAM_QUERY;
grant EXECUTE on CONCATPARTS to PUBLIC;
grant EXECUTE on CONCATPARTS to UAM_QUERY;
grant EXECUTE on CONCATPARTSDETAIL to PUBLIC;
grant EXECUTE on CONCATPARTSWITHLOC to PUBLIC;
grant EXECUTE on CONCATPARTSWITHLOC to UAM_QUERY;
grant EXECUTE on CONCATPREP to PUBLIC;
grant EXECUTE on CONCATPREP to UAM_QUERY;
grant EXECUTE on CONCATPROJAGENT to PUBLIC;
grant EXECUTE on CONCATPROJAGENT to UAM_QUERY;
grant EXECUTE on CONCATRELATIONS to PUBLIC;
grant EXECUTE on CONCATRELATIONS to UAM_QUERY;
grant EXECUTE on CONCATSEX to PUBLIC;
grant EXECUTE on CONCATSEX to UAM_QUERY;
grant EXECUTE on CONCATSINGLEOTHERID to PUBLIC;
grant EXECUTE on CONCATSINGLEOTHERID to UAM_QUERY;
grant EXECUTE on CONCATSINGLEOTHERIDINT to PUBLIC;
grant EXECUTE on CONCATSTRING to PUBLIC;
grant EXECUTE on CONCATSTRING to UAM_QUERY;
grant EXECUTE on CONCATTHIS to PUBLIC;
grant EXECUTE on CONCATTRANSAGENT to PUBLIC;
grant EXECUTE on CONCATTYPESTATUS to PUBLIC;
grant EXECUTE on CONCATTYPESTATUS to UAM_QUERY;
grant EXECUTE on CONCAT_LIST to PUBLIC;
grant EXECUTE on CONCAT_LIST to UAM_QUERY;
grant EXECUTE on CP to PUBLIC;
grant EXECUTE on CVSDATA to PUBLIC;
grant EXECUTE on GETJSONMEDIAURIBYSPECIMEN to PUBLIC;
grant EXECUTE on GETLABELNAME to PUBLIC;
grant EXECUTE on GETMEDIABYSPECIMEN to PUBLIC;
grant EXECUTE on GETTAXA to PUBLIC;
grant EXECUTE on GET_ADDRESS to PUBLIC;
grant EXECUTE on GET_CONTAINER_BARCODE to PUBLIC;
grant EXECUTE on GET_MEDIA_RELATIONS_STRING to PUBLIC;
grant EXECUTE on GET_SCIENTIFIC_NAME_AUTHS to PUBLIC;
grant EXECUTE on GET_TAXONOMY to PUBLIC;
grant EXECUTE on GET_TAXONOMY to UAM_QUERY;
grant EXECUTE on ISDATE to PUBLIC;
grant EXECUTE on ISNUMERIC to PUBLIC;
grant EXECUTE on IS_NUMBER to PUBLIC;
grant EXECUTE on IS_POSITIVE_NUMBER to PUBLIC;
grant EXECUTE on MEDIA_RELATION_SUMMARY to PUBLIC;
grant EXECUTE on NICEURL to PUBLIC;
grant EXECUTE on NICEURLNUMBERS to PUBLIC;
grant EXECUTE on P to PUBLIC;
grant EXECUTE on Q_MEDIA_RELATIONS to PUBLIC;
grant EXECUTE on STDMAMMMEAS to PUBLIC;
grant EXECUTE on STRINGAGG to PUBLIC;
grant EXECUTE on STRINGAGG to UAM_QUERY;
grant EXECUTE on TO_DATE2 to PUBLIC;
grant EXECUTE on TO_METERS to PUBLIC;
grant EXECUTE on TRANSPOSE to PUBLIC;
