/*
select 'grant ' || privilege || ' on ' || TABLE_NAME || ' to ' || grantee || ';'
from dba_tab_privs tp, dba_objects o
where tp.TABLE_NAME = o.object_name
and tp.owner = 'UAM'
and o.owner = 'UAM'
and object_type = 'SEQUENCE'
order by table_name, grantee, privilege
*/

grant SELECT on BLONLINE_PKEY to UAM_QUERY;
grant SELECT on BULKLOADER_PKEY to PUBLIC;
grant SELECT on BULKLOADER_PKEY to UAM_QUERY;
grant SELECT on DGR_LOCATOR_SEQ to PUBLIC;
grant SELECT on DGR_LOCATOR_SEQ to UAM_QUERY;
grant ALTER on JUSTNUMBERS to UAM_QUERY;
grant SELECT on JUSTNUMBERS to UAM_QUERY;
grant SELECT on LAT_LONG_ID_SEQ to PUBLIC;
grant SELECT on LOCALITY_ID_SEQ to PUBLIC;
grant SELECT on QUERYSTATS_SEQ to UAM_QUERY;
grant SELECT on SEQ_CF_USER_LOAN to UAM_QUERY;
grant SELECT on SEQ_MEDIA_RELATIONS to PUBLIC;
grant SELECT on SOMERANDOMSEQUENCE to PUBLIC;
grant SELECT on SQ_ADDR_ID to PUBLIC;
grant SELECT on SQ_AGENT_ID to PUBLIC;
grant SELECT on SQ_AGENT_NAME_ID to PUBLIC;
grant SELECT on SQ_ALA_IMAGE_ID to PUBLIC;
grant SELECT on SQ_ATTRIBUTE_ID to PUBLIC;
grant SELECT on SQ_COLLECTING_EVENT_ID to PUBLIC;
grant SELECT on SQ_COLLECTION_CONTACT_ID to PUBLIC;
grant SELECT on SQ_COLLECTION_ID to PUBLIC;
grant SELECT on SQ_COLLECTION_OBJECT_ID to PUBLIC;
grant SELECT on SQ_COLL_OBJ_OTHER_ID_NUM_ID to PUBLIC;
grant SELECT on SQ_CONTAINER_CHECK_ID to PUBLIC;
grant SELECT on SQ_CONTAINER_ID to PUBLIC;
grant SELECT on SQ_ENCUMBRANCE_ID to PUBLIC;
grant SELECT on SQ_GEOG_AUTH_REC_ID to PUBLIC;
grant SELECT on SQ_GEOLOGY_ATTRIBUTE_HIER_ID to PUBLIC;
grant SELECT on SQ_IDENTIFICATION_ID to PUBLIC;
grant SELECT on SQ_JOURNAL_ID to PUBLIC;
grant SELECT on SQ_LAT_LONG_ID to PUBLIC;
grant SELECT on SQ_LOCALITY_ID to PUBLIC;
grant SELECT on SQ_MEDIA_ID to PUBLIC;
grant SELECT on SQ_PERMIT_ID to PUBLIC;
grant SELECT on SQ_PROJECT_ID to PUBLIC;
grant SELECT on SQ_PUBLICATION_ID to PUBLIC;
grant SELECT on SQ_PUBLICATION_URL_ID to PUBLIC;
grant SELECT on SQ_TAG_ID to PUBLIC;
grant SELECT on SQ_TAXON_NAME_ID to PUBLIC;
grant SELECT on SQ_TRANSACTION_ID to PUBLIC;
