CREATE USER uam_query IDENTIFIED BY "secret_password1" PROFILE arctos_user;
    
ALTER USER uam_query DEFAULT TABLESPACE users QUOTA 1G on users;
ALTER USER uam_query QUOTA UNLIMITED ON UAM_DAT_1;
ALTER USER uam_query QUOTA UNLIMITED ON UAM_IDX_1;

GRANT CONNECT TO uam_query;
GRANT CREATE TABLE TO uam_query;
GRANT CREATE job TO uam_query;
GRANT CREATE PROCEDURE TO uam_query;
GRANT SELECT ANY DICTIONARY TO uam_query;
GRANT CREATE SEQUENCE TO uam_query;
