/*
select dbms_metadata.get_ddl( 'INDEX', index_name) 
from user_indexes 
where table_name like 'CF%'
order by table_name, uniqueness, index_name;

CF_BUGS
CF_CANNED_SEARCH
CF_REPORT_SQL
CF_SPEC_RES_COLS
CF_TACC_TRANSFER
CF_TEMP_ATTRIBUTES
CF_USERS

*/

-- CF_BUGS
CREATE UNIQUE INDEX PK_CF_BUGS
	ON CF_BUGS (BUG_ID)
	TABLESPACE UAM_IDX_1;

-- CF_CANNED_SEARCH
CREATE UNIQUE INDEX IU_CFCANNEDSEARCH_USERID_SRCH
	ON CF_CANNED_SEARCH (USER_ID, SEARCH_NAME)
	TABLESPACE UAM_IDX_1;

CREATE UNIQUE INDEX IU_CFCANNEDSEARCH_USERID_URL
	ON CF_CANNED_SEARCH (USER_ID, URL)
	TABLESPACE UAM_IDX_1;

CREATE UNIQUE INDEX PK_CF_CANNED_SEARCH
	ON CF_CANNED_SEARCH (CANNED_ID)
	TABLESPACE UAM_IDX_1;

-- CF_REPORT_SQL
CREATE UNIQUE INDEX IU_CFREPORTSQL_REPORTNAME
	ON CF_REPORT_SQL (REPORT_NAME)
	TABLESPACE UAM_IDX_1;

CREATE UNIQUE INDEX PK_CF_REPORT_SQL
	ON CF_REPORT_SQL (REPORT_ID)
	TABLESPACE UAM_IDX_1;

-- CF_SPEC_RES_COLS
CREATE UNIQUE INDEX PK_CF_SPEC_RES_COLS
	ON CF_SPEC_RES_COLS (CF_SPEC_RES_COLS_ID)
	TABLESPACE UAM_IDX_1;

-- CF_TACC_TRANSFER
CREATE UNIQUE INDEX PK_CF_TACC_TRANSFER
	ON CF_TACC_TRANSFER (MEDIA_ID)
	TABLESPACE UAM_IDX_1;

-- CF_TEMP_ATTRIBUTES
CREATE UNIQUE INDEX PK_CF_TEMP_ATTRIBUTES
	ON CF_TEMP_ATTRIBUTES (KEY)
	TABLESPACE UAM_IDX_1;

-- CF_USERS
-- drop 
CREATE UNIQUE INDEX IU_CFUSERS_USERNAME
	ON CF_USERS (USERNAME)
	TABLESPACE UAM_IDX_1;
-- new
create unique index iu_u_username on cf_users (upper(username)) tablespace uam_idx_1;

	
	
CREATE UNIQUE INDEX PK_CF_USERS
	ON CF_USERS (USER_ID)
	TABLESPACE UAM_IDX_1;
	