/*
select dbms_metadata.get_ddl('INDEX', index_name)
from user_indexes
where table_name like 'CT%'
order by table_name, uniqueness, index_name;

CTABUNDANCE
CTACCN_STATUS
CTACCN_TYPE
CTADDR_TYPE
CTAGENT_NAME_TYPE
CTAGENT_RANK
CTAGENT_RELATIONSHIP
CTAGENT_TYPE
CTAGE_CLASS
CTATTRIBUTE_CODE_TABLES
CTATTRIBUTE_TYPE
CTAUTHOR_ROLE
CTBIOL_RELATIONS
CTBORROW_STATUS
CTCASTE
CTCATALOGED_ITEM_TYPE
CTCF_LOAN_USE_TYPE
CTCITATION_TYPE_STATUS
CTCLASS
CTCOLLECTING_SOURCE
CTCOLLECTION_CDE
CTCOLLECTOR_ROLE
CTCOLL_CONTACT_ROLE
CTCOLL_OBJECT_TYPE
CTCOLL_OBJ_DISP
CTCOLL_OTHER_ID_TYPE
CTCONTAINER_TYPE
CTCONTAINER_TYPE_SIZE
CTCONTINENT
CTDATUM
CTDEPTH_UNITS
CTDOWNLOAD_PURPOSE
CTELECTRONIC_ADDR_TYPE
CTENCUMBRANCE_ACTION
CTEW
CTFEATURE
CTFLAGS
CTFLUID_CONCENTRATION
CTFLUID_TYPE
CTGEOG_SOURCE_AUTHORITY
CTGEOREFMETHOD
CTIMAGE_OBJECT_TYPE
CTINFRASPECIFIC_RANK
CTISLAND_GROUP
CTJOURNAL_NAME
CTKILL_METHOD
CTLAT_LONG_ERROR_UNITS
CTLAT_LONG_REF_SOURCE
CTLAT_LONG_UNITS
CTLENGTH_UNITS
CTLOAN_STATUS
CTLOAN_TYPE
CTMEDIA_LABEL
CTMEDIA_RELATIONSHIP
CTMEDIA_TYPE
CTMIME_TYPE
CTNATURE_OF_ID
CTNOMENCLATURAL_CODE
CTNS
CTNUMERIC_AGE_UNITS
CTORIG_ELEV_UNITS
CTPERMIT_TYPE
CTPREFIX
CTPROJECT_AGENT_ROLE
CTPUBLICATION_ATTRIBUTE
CTPUBLICATION_TYPE
CTSECTION_TYPE
CTSEX_CDE
CTSHIPPED_CARRIER_METHOD
CTSPECIMEN_PART_LIST_ORDER
CTSPECIMEN_PART_MODIFIER
CTSPECIMEN_PART_NAME
CTSPECIMEN_PRESERV_METHOD
CTSUFFIX
CTTAXA_FORMULA
CTTAXONOMIC_AUTHORITY
CTTAXON_RELATION
CTTAXON_VARIABLE
CTTRANSACTION_TYPE
CTTRANS_AGENT_ROLE
CTVERIFICATIONSTATUS
CTWEIGHT_UNITS
*/

-- CTABUNDANCE
CREATE UNIQUE INDEX PK_CTABUNDANCE
	ON CTABUNDANCE (COLLECTION_CDE, ABUNDANCE)
	TABLESPACE UAM_IDX_1;

-- CTACCN_STATUS
CREATE UNIQUE INDEX PK_CTACCN_STATUS
	ON CTACCN_STATUS (ACCN_STATUS)
	TABLESPACE UAM_IDX_1;

-- CTACCN_TYPE
CREATE UNIQUE INDEX PK_CTACCN_TYPE
	ON CTACCN_TYPE (ACCN_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTADDR_TYPE
CREATE UNIQUE INDEX PK_CTADDR_TYPE
	ON CTADDR_TYPE (ADDR_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTAGENT_NAME_TYPE
CREATE UNIQUE INDEX PK_CTAGENT_NAME_TYPE
	ON CTAGENT_NAME_TYPE (AGENT_NAME_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTAGENT_RANK
CREATE UNIQUE INDEX PK_CTAGENT_RANK
	ON CTAGENT_RANK (AGENT_RANK)
	TABLESPACE UAM_IDX_1;

-- CTAGENT_RELATIONSHIP
CREATE UNIQUE INDEX PK_CTAGENT_RELATIONSHIP
	ON CTAGENT_RELATIONSHIP (AGENT_RELATIONSHIP)
	TABLESPACE UAM_IDX_1;

-- CTAGENT_TYPE
CREATE UNIQUE INDEX PK_CTAGENT_TYPE
	ON CTAGENT_TYPE (AGENT_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTAGE_CLASS
CREATE UNIQUE INDEX PK_CTAGE_CLASS
	ON CTAGE_CLASS (AGE_CLASS, COLLECTION_CDE)
	TABLESPACE UAM_IDX_1;

-- CTATTRIBUTE_CODE_TABLES
CREATE UNIQUE INDEX PK_CTATTRIBUTE_CODE_TABLES
	ON CTATTRIBUTE_CODE_TABLES (ATTRIBUTE_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTATTRIBUTE_TYPE
CREATE UNIQUE INDEX PK_CTATTRIBUTE_TYPE
	ON CTATTRIBUTE_TYPE (ATTRIBUTE_TYPE, COLLECTION_CDE)
	TABLESPACE UAM_IDX_1;

-- CTAUTHOR_ROLE
CREATE UNIQUE INDEX PK_CTAUTHOR_ROLE
	ON CTAUTHOR_ROLE (AUTHOR_ROLE)
	TABLESPACE UAM_IDX_1;

-- CTBIOL_RELATIONS
CREATE UNIQUE INDEX PK_CTBIOL_RELATIONS
	ON CTBIOL_RELATIONS (BIOL_INDIV_RELATIONSHIP)
	TABLESPACE UAM_IDX_1;

-- CTBORROW_STATUS
CREATE UNIQUE INDEX PK_CTBORROW_STATUS
	ON CTBORROW_STATUS (BORROW_STATUS)
	TABLESPACE UAM_IDX_1;

-- CTCASTE
CREATE UNIQUE INDEX PK_CTCASTE
	ON CTCASTE (COLLECTION_CDE,CASTE)
	TABLESPACE UAM_IDX_1;

-- CTCATALOGED_ITEM_TYPE
CREATE UNIQUE INDEX PK_CTCATALOGED_ITEM_TYPE
	ON CTCATALOGED_ITEM_TYPE (CATALOGED_ITEM_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTCF_LOAN_USE_TYPE
CREATE UNIQUE INDEX PK_CTCF_LOAN_USE_TYPE
	ON CTCF_LOAN_USE_TYPE (USE_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTCITATION_TYPE_STATUS
CREATE UNIQUE INDEX PK_CTCITATION_TYPE_STATUS
	ON CTCITATION_TYPE_STATUS (TYPE_STATUS)
	TABLESPACE UAM_IDX_1;

-- CTCLASS
CREATE UNIQUE INDEX PK_CTCLASS
	ON CTCLASS (PHYLCLASS)
	TABLESPACE UAM_IDX_1;

-- CTCOLLECTING_SOURCE
CREATE UNIQUE INDEX PK_CTCOLLECTING_SOURCE
	ON CTCOLLECTING_SOURCE (COLLECTING_SOURCE)
	TABLESPACE UAM_IDX_1;

-- CTCOLLECTION_CDE
CREATE UNIQUE INDEX PK_CTCOLLECTION_CDE
	ON CTCOLLECTION_CDE (COLLECTION_CDE)
	TABLESPACE UAM_IDX_1;

-- CTCOLLECTOR_ROLE
CREATE UNIQUE INDEX PK_CTCOLLECTOR_ROLE
	ON CTCOLLECTOR_ROLE (COLLECTOR_ROLE)
	TABLESPACE UAM_IDX_1;

-- CTCOLL_CONTACT_ROLE
CREATE UNIQUE INDEX PK_CTCOLL_CONTACT_ROLE
	ON CTCOLL_CONTACT_ROLE (CONTACT_ROLE)
	TABLESPACE UAM_IDX_1;

-- CTCOLL_OBJECT_TYPE
CREATE UNIQUE INDEX PK_CTCOLL_OBJECT_TYPE
	ON CTCOLL_OBJECT_TYPE (COLL_OBJECT_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTCOLL_OBJ_DISP
CREATE UNIQUE INDEX PK_CTCOLL_OBJ_DISP
	ON CTCOLL_OBJ_DISP (COLL_OBJ_DISPOSITION)
	TABLESPACE UAM_IDX_1;

-- CTCOLL_OTHER_ID_TYPE
CREATE UNIQUE INDEX PK_CTCOLL_OTHER_ID_TYPE
	ON CTCOLL_OTHER_ID_TYPE (OTHER_ID_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTCONTAINER_TYPE
CREATE UNIQUE INDEX PK_CTCONTAINER_TYPE
	ON CTCONTAINER_TYPE (CONTAINER_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTCONTAINER_TYPE_SIZE
CREATE UNIQUE INDEX PK_CTCONTAINER_TYPE_SIZE
	ON CTCONTAINER_TYPE_SIZE (CONTAINER_TYPE, CONTAINER_SIZE)
	TABLESPACE UAM_IDX_1;

-- CTCONTINENT
CREATE UNIQUE INDEX PK_CTCONTINENT
	ON CTCONTINENT (CONTINENT_OCEAN)
	TABLESPACE UAM_IDX_1;

-- CTDATUM
CREATE UNIQUE INDEX PK_CTDATUM
	ON CTDATUM (DATUM)
	TABLESPACE UAM_IDX_1;

-- CTDEPTH_UNITS
CREATE UNIQUE INDEX PK_CTDEPTH_UNITS
	ON CTDEPTH_UNITS (DEPTH_UNITS)
	TABLESPACE UAM_IDX_1;

-- CTDOWNLOAD_PURPOSE
CREATE UNIQUE INDEX PK_CTDOWNLOAD_PURPOSE
	ON CTDOWNLOAD_PURPOSE (DOWNLOAD_PURPOSE)
	TABLESPACE UAM_IDX_1;

-- CTELECTRONIC_ADDR_TYPE
CREATE UNIQUE INDEX PK_CTELECTRONIC_ADDR_TYPE
	ON CTELECTRONIC_ADDR_TYPE (ADDRESS_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTENCUMBRANCE_ACTION
CREATE UNIQUE INDEX PK_CTENCUMBRANCE_ACTION
	ON CTENCUMBRANCE_ACTION (ENCUMBRANCE_ACTION)
	TABLESPACE UAM_IDX_1;

-- CTEW
CREATE UNIQUE INDEX PK_CTEW
	ON CTEW (E_OR_W)
	TABLESPACE UAM_IDX_1;

-- CTFEATURE
CREATE UNIQUE INDEX PK_CTFEATURE
	ON CTFEATURE (FEATURE)
	TABLESPACE UAM_IDX_1;

-- CTFLAGS
CREATE UNIQUE INDEX PK_CTFLAGS
	ON CTFLAGS (FLAGS)
	TABLESPACE UAM_IDX_1;

-- CTFLUID_CONCENTRATION
CREATE UNIQUE INDEX PK_CTFLUID_CONCENTRATION
	ON CTFLUID_CONCENTRATION (CONCENTRATION)
	TABLESPACE UAM_IDX_1;

-- CTFLUID_TYPE
CREATE UNIQUE INDEX PK_CTFLUID_TYPE
	ON CTFLUID_TYPE (FLUID_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTGEOG_SOURCE_AUTHORITY
CREATE UNIQUE INDEX PK_CTGEOG_SOURCE_AUTHORITY
	ON CTGEOG_SOURCE_AUTHORITY (SOURCE_AUTHORITY)
	TABLESPACE UAM_IDX_1;

-- CTGEOREFMETHOD
CREATE UNIQUE INDEX PK_CTGEOREFMETHOD
	ON CTGEOREFMETHOD (GEOREFMETHOD)
	TABLESPACE UAM_IDX_1;

-- CTIMAGE_OBJECT_TYPE
CREATE UNIQUE INDEX PK_CTIMAGE_OBJECT_TYPE
	ON CTIMAGE_OBJECT_TYPE (IMAGE_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTINFRASPECIFIC_RANK
CREATE UNIQUE INDEX PK_CTINFRASPECIFIC_RANK
	ON CTINFRASPECIFIC_RANK (INFRASPECIFIC_RANK)
	TABLESPACE UAM_IDX_1;

-- CTISLAND_GROUP
CREATE UNIQUE INDEX PK_CTISLAND_GROUP
	ON CTISLAND_GROUP (ISLAND_GROUP)
	TABLESPACE UAM_IDX_1;

-- CTJOURNAL_NAME
CREATE UNIQUE INDEX PK_CTJOURNAL_NAME
	ON CTJOURNAL_NAME (JOURNAL_NAME)
	TABLESPACE UAM_IDX_1;

-- CTKILL_METHOD
CREATE UNIQUE INDEX PK_CTKILL_METHOD
	ON CTKILL_METHOD (KILL_METHOD, COLLECTION_CDE)
	TABLESPACE UAM_IDX_1;

-- CTLAT_LONG_ERROR_UNITS
CREATE UNIQUE INDEX PK_CTLAT_LONG_ERROR_UNITS
	ON CTLAT_LONG_ERROR_UNITS (LAT_LONG_ERROR_UNITS)
	TABLESPACE UAM_IDX_1;

-- CTLAT_LONG_REF_SOURCE
CREATE UNIQUE INDEX PK_CTLAT_LONG_REF_SOURCE
	ON CTLAT_LONG_REF_SOURCE (LAT_LONG_REF_SOURCE)
	TABLESPACE UAM_IDX_1;

-- CTLAT_LONG_UNITS
CREATE UNIQUE INDEX PK_CTLAT_LONG_UNITS
	ON CTLAT_LONG_UNITS (ORIG_LAT_LONG_UNITS)
	TABLESPACE UAM_IDX_1;

-- CTLENGTH_UNITS
CREATE UNIQUE INDEX PK_CTLENGTH_UNITS
	ON CTLENGTH_UNITS (LENGTH_UNITS)
	TABLESPACE UAM_IDX_1;

-- CTLOAN_STATUS
CREATE UNIQUE INDEX PK_CTLOAN_STATUS
	ON CTLOAN_STATUS (LOAN_STATUS)
	TABLESPACE UAM_IDX_1;

-- CTLOAN_TYPE
CREATE UNIQUE INDEX PK_CTLOAN_TYPE
	ON CTLOAN_TYPE (LOAN_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTMEDIA_LABEL
CREATE UNIQUE INDEX PK_CTMEDIA_LABEL
	ON CTMEDIA_LABEL (MEDIA_LABEL)
	TABLESPACE UAM_IDX_1;

-- CTMEDIA_RELATIONSHIP
CREATE UNIQUE INDEX PK_CTMEDIA_RELATIONSHIP
	ON CTMEDIA_RELATIONSHIP (MEDIA_RELATIONSHIP)
	TABLESPACE UAM_IDX_1;

-- CTMEDIA_TYPE
CREATE UNIQUE INDEX PK_CTMEDIA_TYPE
	ON CTMEDIA_TYPE (MEDIA_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTMIME_TYPE
CREATE UNIQUE INDEX PK_CTMIME_TYPE
	ON CTMIME_TYPE (MIME_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTNATURE_OF_ID
CREATE UNIQUE INDEX PK_CTNATURE_OF_ID
	ON CTNATURE_OF_ID (NATURE_OF_ID)
	TABLESPACE UAM_IDX_1;

-- CTNOMENCLATURAL_CODE
CREATE UNIQUE INDEX PK_CTNOMENCLATURAL_CODE
	ON CTNOMENCLATURAL_CODE (NOMENCLATURAL_CODE)
	TABLESPACE UAM_IDX_1;

-- CTNS
CREATE UNIQUE INDEX PK_CTNS
	ON CTNS (N_OR_S)
	TABLESPACE UAM_IDX_1;

-- CTNUMERIC_AGE_UNITS
CREATE UNIQUE INDEX PK_CTNUMERIC_AGE_UNITS
	ON CTNUMERIC_AGE_UNITS (NUMERIC_AGE_UNITS)
	TABLESPACE UAM_IDX_1;

-- CTORIG_ELEV_UNITS
CREATE UNIQUE INDEX PK_CTORIG_ELEV_UNITS
	ON CTORIG_ELEV_UNITS (ORIG_ELEV_UNITS)
	TABLESPACE UAM_IDX_1;

-- CTPERMIT_TYPE
CREATE UNIQUE INDEX PK_CTPERMIT_TYPE
	ON CTPERMIT_TYPE (PERMIT_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTPREFIX
CREATE UNIQUE INDEX PK_CTPREFIX
	ON CTPREFIX (PREFIX)
	TABLESPACE UAM_IDX_1;

-- CTPROJECT_AGENT_ROLE
CREATE UNIQUE INDEX PK_CTPROJECT_AGENT_ROLE
	ON CTPROJECT_AGENT_ROLE (PROJECT_AGENT_ROLE)
	TABLESPACE UAM_IDX_1;

-- CTPUBLICATION_ATTRIBUTE
CREATE UNIQUE INDEX PK_CTPUBLICATION_ATTRIBUTE
	ON CTPUBLICATION_ATTRIBUTE (PUBLICATION_ATTRIBUTE)
	TABLESPACE UAM_IDX_1;

-- CTPUBLICATION_TYPE
CREATE UNIQUE INDEX PK_CTPUBLICATION_TYPE
	ON CTPUBLICATION_TYPE (PUBLICATION_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTSECTION_TYPE
CREATE UNIQUE INDEX PK_CTSECTION_TYPE
	ON CTSECTION_TYPE (FIELD_NOTE_SECT_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTSEX_CDE
CREATE UNIQUE INDEX PK_CTSEX_CDE
	ON CTSEX_CDE (SEX_CDE, COLLECTION_CDE)
	TABLESPACE UAM_IDX_1;

-- CTSHIPPED_CARRIER_METHOD
CREATE UNIQUE INDEX PK_CTSHIPPED_CARRIER_METHOD
	ON CTSHIPPED_CARRIER_METHOD (SHIPPED_CARRIER_METHOD)
	TABLESPACE UAM_IDX_1;

-- CTSPECIMEN_PART_LIST_ORDER
CREATE UNIQUE INDEX PK_CTSPECIMEN_PART_LIST_ORDER
	ON CTSPECIMEN_PART_LIST_ORDER (PARTNAME, LIST_ORDER)
	TABLESPACE UAM_IDX_1;

-- CTSPECIMEN_PART_MODIFIER
CREATE UNIQUE INDEX PK_CTSPECIMEN_PART_MODIFIER
	ON CTSPECIMEN_PART_MODIFIER (PART_MODIFIER)
	TABLESPACE UAM_IDX_1;

-- CTSPECIMEN_PART_NAME
CREATE INDEX IX_CTSPECIMENPARTNAME_PARTNAME
	ON CTSPECIMEN_PART_NAME (PART_NAME)
	TABLESPACE UAM_IDX_1;

CREATE UNIQUE INDEX PK_CTSPECIMEN_PART_NAME
	ON CTSPECIMEN_PART_NAME (PART_NAME, COLLECTION_CDE)
	TABLESPACE UAM_IDX_1;

-- CTSPECIMEN_PRESERV_METHOD
CREATE UNIQUE INDEX PK_CTSPECIMEN_PRESERV_METHOD
	ON CTSPECIMEN_PRESERV_METHOD (COLLECTION_CDE, PRESERVE_METHOD)
	TABLESPACE UAM_IDX_1;

-- CTSUFFIX
CREATE UNIQUE INDEX PK_CTSUFFIX
	ON CTSUFFIX (SUFFIX)
	TABLESPACE UAM_IDX_1;

-- CTTAXA_FORMULA
CREATE UNIQUE INDEX PK_CTTAXA_FORMULA
	ON CTTAXA_FORMULA (TAXA_FORMULA)
	TABLESPACE UAM_IDX_1;

-- CTTAXONOMIC_AUTHORITY
CREATE UNIQUE INDEX PK_CTTAXONOMIC_AUTHORITY
	ON CTTAXONOMIC_AUTHORITY (SOURCE_AUTHORITY)
	TABLESPACE UAM_IDX_1;

-- CTTAXON_RELATION
CREATE UNIQUE INDEX PK_CTTAXON_RELATION
	ON CTTAXON_RELATION (TAXON_RELATIONSHIP)
	TABLESPACE UAM_IDX_1;

-- CTTAXON_VARIABLE
CREATE UNIQUE INDEX PK_CTTAXON_VARIABLE
	ON CTTAXON_VARIABLE (TAXON_VARIABLE)
	TABLESPACE UAM_IDX_1;

-- CTTRANSACTION_TYPE
CREATE UNIQUE INDEX PK_CTTRANSACTION_TYPE
	ON CTTRANSACTION_TYPE (TRANSACTION_TYPE)
	TABLESPACE UAM_IDX_1;

-- CTTRANS_AGENT_ROLE
CREATE UNIQUE INDEX PK_CTTRANS_AGENT_ROLE
	ON CTTRANS_AGENT_ROLE (TRANS_AGENT_ROLE)
	TABLESPACE UAM_IDX_1;

-- CTVERIFICATIONSTATUS
CREATE UNIQUE INDEX PK_CTVERIFICATIONSTATUS
	ON CTVERIFICATIONSTATUS (VERIFICATIONSTATUS)
	TABLESPACE UAM_IDX_1;

-- CTWEIGHT_UNITS
CREATE UNIQUE INDEX PK_CTWEIGHT_UNITS
	ON CTWEIGHT_UNITS (WEIGHT_UNITS)
	TABLESPACE UAM_IDX_1;
	