-- QUERY_STATS
CREATE UNIQUE INDEX UAM_QUERY.PK_QUERY_STATS
    ON UAM_QUERY.QUERY_STATS (QUERY_ID)
    TABLESPACE UAM_IDX_1;

CREATE INDEX UAM_QUERY.IX_QUERYSTATS_CRDATE
    ON UAM_QUERY.QUERY_STATS (CREATE_DATE)
    TABLESPACE UAM_IDX_1;

-- QUERY_STATS_COLL
CREATE UNIQUE INDEX UAM_QUERY.PK_QUERY_STATS_COLL
    ON UAM_QUERY.QUERY_STATS_COLL (QUERY_ID, COLLECTION_ID)
    TABLESPACE UAM_IDX_1;

CREATE INDEX UAM_QUERY.IX_QUERYSTATSCOLL_QID
    ON UAM_QUERY.QUERY_STATS_COLL (QUERY_ID)
    TABLESPACE UAM_IDX_1;

CREATE INDEX UAM_QUERY.IX_QUERYSTATSCOLL_COLLID
    ON UAM_QUERY.QUERY_STATS_COLL (COLLECTION_ID)
    TABLESPACE UAM_IDX_1;
