CREATE TABLE DGR_LOCATOR (
    LOCATOR_ID NUMBER NOT NULL,
	COLLECTION_OBJECT_ID NUMBER,
	FREEZER NUMBER NOT NULL,
	RACK NUMBER NOT NULL,
	BOX NUMBER NOT NULL,
	PLACE NUMBER NOT NULL,
	NK NUMBER,
	TISSUE_TYPE VARCHAR2(255)
) TABLESPACE UAM_DAT_1
;