-- ACHTUNG!!!
-- trigger adds columns and foreign keys as needed when media_relationships code table is updated.

CREATE TABLE TAB_MEDIA_REL_FKEY (
	MEDIA_RELATIONS_ID NUMBER NOT NULL,
	CFK_CATALOGED_ITEM NUMBER,
	CFK_AGENT NUMBER,
	CFK_MEDIA NUMBER,
	CFK_LOCALITY NUMBER,
	CFK_COLLECTING_EVENT NUMBER,
	CFK_PROJECT NUMBER,
	CFK_TAXONOMY NUMBER,
	CFK_PUBLICATION NUMBER,
	CFK_ACCN NUMBER,
	    CONSTRAINT PK_TAB_MEDIA_REL_FKEY PRIMARY KEY (MEDIA_RELATIONS_ID)
            TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_TABMEDIARELFKEY_CATITEM
			FOREIGN KEY (CFK_CATALOGED_ITEM)
			REFERENCES CATALOGED_ITEM (COLLECTION_OBJECT_ID),
		CONSTRAINT FK_TABMEDIARELFKEY_AGENT
			FOREIGN KEY (CFK_AGENT)
			REFERENCES AGENT (AGENT_ID),
		CONSTRAINT FK_TABMEDIARELFKEY_COLLEVENT
			FOREIGN KEY (CFK_COLLECTING_EVENT)
			REFERENCES COLLECTING_EVENT (COLLECTING_EVENT_ID),
		CONSTRAINT FK_TABMEDIARELFKEY_LOCALITY
			FOREIGN KEY (CFK_LOCALITY)
			REFERENCES LOCALITY (LOCALITY_ID),
		CONSTRAINT FK_MR_PROJECT
			FOREIGN KEY (CFK_PROJECT)
			REFERENCES PROJECT (PROJECT_ID),
		CONSTRAINT FK_TABMEDIARELFKEY_TAXONOMY FOREIGN KEY (CFK_TAXONOMY)
            REFERENCES TAXONOMY (TAXON_NAME_ID),
         CONSTRAINT FK_TABMEDIARELFKEY_PUBLICATION FOREIGN KEY (CFK_PUBLICATION)
			REFERENCES PUBLICATION (PUBLICATION_ID),
         CONSTRAINT FK_TABMEDIARELFKEY_ACCN FOREIGN KEY (CFK_ACCN)
			REFERENCES ACCN (TRANSACTION_ID),
         CONSTRAINT FK_TABMEDIARELFKEY_MEDIA FOREIGN KEY (CFK_MEDIA)
			REFERENCES MEDIA (MEDIA_ID)
) TABLESPACE UAM_DAT_1;
