CREATE TABLE VPD_COLLECTION_LOCALITY (
	COLLECTION_ID NUMBER NOT NULL,
	LOCALITY_ID NUMBER NOT NULL,
	STALE_FG NUMBER(1,0),
		CONSTRAINT PK_VPD_COLLECTION_LOCALITY
			PRIMARY KEY (COLLECTION_ID, LOCALITY_ID)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;