/* These cf_* tables are used. 
CF_ADDRESS
CF_BUGS
CF_CANNED_SEARCH
CF_COLLECTION
CF_COLLECTION_APPEARANCE
CF_CTUSER_ROLES
CF_DATABASE_ACTIVITY
CF_DOWNLOAD
CF_FORM_PERMISSIONS
CF_GENBANK_CRAWL
CF_GENBANK_INFO
CF_LOAN
CF_LOAN_ITEM
CF_LOG
CF_PROJECT
CF_REPORT_SQL
CF_SEARCH_RESULTS
CF_SEARCH_TERMS
CF_SITEMAPS
CF_SPEC_RES_COLS
CF_TACC_TRANSFER
CF_TEMP_AGENTS
CF_TEMP_ATTRIBUTES
CF_TEMP_BARCODE_PARTS
CF_TEMP_BL_RELATIONS
CF_TEMP_CITATION
CF_TEMP_CONTAINER_LOCATION
CF_TEMP_CONT_EDIT
CF_TEMP_GEOREF
CF_TEMP_LOAN_ITEM
CF_TEMP_MEDIA
CF_TEMP_MEDIA_LABELS
CF_TEMP_MEDIA_RELATIONS
CF_TEMP_OIDS
CF_TEMP_PARTS
CF_TEMP_RELATIONS
CF_TEMP_SCANS
CF_TEMP_TAXONOMY
CF_USERS
CF_USER_DATA
CF_USER_LOAN
CF_USER_LOG
CF_USER_ROLES
*/

/*
-- These cf* tables are not used
-- DLM ordered to die: 
CFT
CF_ADDR
CF_AUTH_ARCTOSDOC
CF_LABEL
CF_TEMP_CONTAINER_LOCATION_TWO -- used in code, but is created as a copy of CF_TEMP_CONTAINER_LOCATION
*/

/*
CREATE TABLE CFT (
	KEY NUMBER NOT NULL,
	CONTAINER_ID NUMBER,
	PARENT_CONTAINER_ID NUMBER,
	BARCODE VARCHAR2(255),
	LABEL VARCHAR2(255),
	DESCRIPTION VARCHAR2(255),
	CONTAINER_TYPE VARCHAR2(255),
	CONTAINER_REMARKS VARCHAR2(255)
) TABLESPACE UAM_DAT_1;
*/

/*
CREATE TABLE CF_ADDR (
	ADDR_ID NUMBER NOT NULL,
	STREET_ADDR1 VARCHAR2(255) NOT NULL,
	STREET_ADDR2 VARCHAR2(255),
	CITY VARCHAR2(60) NOT NULL,
	STATE VARCHAR2(20) NOT NULL,
	ZIP VARCHAR2(10) NOT NULL,
	COUNTRY_CDE VARCHAR2(50),
	MAIL_STOP VARCHAR2(20),
	FORMATTED_ADDR VARCHAR2(510),
	AGENT_ID NUMBER NOT NULL,
	ADDR_TYPE VARCHAR2(25) NOT NULL,
	JOB_TITLE VARCHAR2(60),
	VALID_ADDR_FG NUMBER NOT NULL,
	ADDR_REMARKS VARCHAR2(255),
	INSTITUTION VARCHAR2(255),
	DEPARTMENT VARCHAR2(255)
) TABLESPACE UAM_DAT_1;
*/

/*
CREATE TABLE CF_AUTH_ARCTOSDOC (
	USERNAME VARCHAR2(255) NOT NULL,
	AUTHORIZED_BY VARCHAR2(255) NOT NULL,
	PRIVS VARCHAR2(30) NOT NULL
) TABLESPACE UAM_DAT_1;
*/

/*
CREATE TABLE CF_LABEL (
	PART_ID NUMBER NOT NULL,
	CONTAINER_TYPE VARCHAR2(60),
	CAT_NUM NUMBER NOT NULL,
	COLLECTOR VARCHAR2(255),
	VERBATIM_DATE VARCHAR2(60),
	ORIGINAL_FIELD_NUMBER VARCHAR2(255),
	AF_NUMBER VARCHAR2(15),
	LAT_LONG VARCHAR2(255),
	SEX VARCHAR2(20) NOT NULL,
	MEAS VARCHAR2(255),
	LOCALITY VARCHAR2(255),
	SCIENTIFIC_NAME VARCHAR2(255),
	PART_NAME VARCHAR2(60),
	BARCODE VARCHAR2(60)
) TABLESPACE UAM_DAT_1;
*/

/* created from CF_TEMP_CONTAINER_LOCATION
CREATE TABLE CF_TEMP_CONTAINER_LOCATION_TWO (
	CONTAINER_ID NUMBER,
	PARENT_CONTAINER_ID NUMBER,
	TIMESTAMP DATE
) TABLESPACE UAM_DAT_1;
*/
