CREATE TABLE CF_ADDRESS (
	ADDR_ID NUMBER NOT NULL,
	STREET_ADDR1 VARCHAR2(255) NOT NULL,
	STREET_ADDR2 VARCHAR2(255),
	CITY VARCHAR2(60) NOT NULL,
	STATE VARCHAR2(20) NOT NULL,
	ZIP VARCHAR2(10) NOT NULL,
	COUNTRY_CDE VARCHAR2(50),
	MAIL_STOP VARCHAR2(20),
	ADDR_TYPE VARCHAR2(25) NOT NULL,
	JOB_TITLE VARCHAR2(60),
	VALID_ADDR_FG NUMBER NOT NULL,
	ADDR_REMARKS VARCHAR2(255),
	INSTITUTION VARCHAR2(255),
	DEPARTMENT VARCHAR2(255),
	USER_ID NUMBER NOT NULL
) TABLESPACE UAM_DAT_1;
