CREATE TABLE CF_DOWNLOAD (
	USER_ID NUMBER NOT NULL,
	DOWNLOAD_PURPOSE VARCHAR2(60) NOT NULL,
	DOWNLOAD_DATE DATE NOT NULL,
	NUM_RECORDS NUMBER NOT NULL,
	AGREE_TO_TERMS VARCHAR2(3) NOT NULL,
		CONSTRAINT FK_CTDOWNLOAD_PURPOSE
			FOREIGN KEY (DOWNLOAD_PURPOSE)
			REFERENCES CTDOWNLOAD_PURPOSE (DOWNLOAD_PURPOSE)
) TABLESPACE UAM_DAT_1;
