CREATE TABLE CF_GENBANK_CRAWL (
	GBCID NUMBER NOT NULL,
	OWNER VARCHAR2(60),
	LINK_URL VARCHAR2(255) NOT NULL,
	FOUND_COUNT NUMBER,
	QUERY_TYPE VARCHAR2(30),
	RUN_DATE DATE DEFAULT sysdate
) TABLESPACE UAM_DAT_1;
