CREATE TABLE CF_GENBANK_INFO (
	GBI_ID NUMBER NOT NULL,
	CITATION VARCHAR2(4000) NOT NULL,
	PUBINARCTOS VARCHAR2(20),
	CITATIONSINGENBANK VARCHAR2(20),
	CITATIONINPUBLICATION VARCHAR2(20),
	CITATIONSINARCTOS VARCHAR2(20),
	ARCTICLEATURL VARCHAR2(4000),
	COMMENTS VARCHAR2(4000),
	STATUS VARCHAR2(20)
) TABLESPACE UAM_DAT_1;
