CREATE TABLE CF_LOG (
	LOG_ID NUMBER NOT NULL,
	USERNAME VARCHAR2(255),
	TEMPLATE VARCHAR2(255),
	ACCESS_DATE DATE,
	QUERY_STRING VARCHAR2(4000),
	REPORTED_COUNT NUMBER,
	REFERRING_URL VARCHAR2(4000)
) TABLESPACE UAM_DAT_1 ENABLE ROW MOVEMENT;
