CREATE TABLE CF_LOAN_ITEM (
	USER_LOAN_ID NUMBER NOT NULL,
	COLLECTION_OBJECT_ID NUMBER NOT NULL,
	REMARK VARCHAR2(255),
	USE_TYPE VARCHAR2(30) NOT NULL,
	APPROVAL_STATUS VARCHAR2(60),
	ADMIN_REMARK VARCHAR2(255)
) TABLESPACE UAM_DAT_1;
