CREATE TABLE CF_LOAN (
	LOAN_ID NUMBER NOT NULL,
	TRANS_ID NUMBER NOT NULL,
	LOAN_NAME VARCHAR2(255) NOT NULL,
	LOAN_DESCRIPTION VARCHAR2(4000),
	INSTRUCTIONS VARCHAR2(4000),
	TRANSACTION_ID NUMBER
) TABLESPACE UAM_DAT_1;
