CREATE TABLE CF_PROJECT (
	TRANS_ID NUMBER NOT NULL,
	USER_ID NUMBER NOT NULL,
	PROJ_TITLE VARCHAR2(255) NOT NULL,
	PROJ_DESC VARCHAR2(4000),
	REMARKS VARCHAR2(4000),
	PROJECT_ID NUMBER
) TABLESPACE UAM_DAT_1;
