CREATE TABLE CF_SPEC_RES_COLS (
	COLUMN_NAME VARCHAR2(38),
	SQL_ELEMENT VARCHAR2(255),
	CATEGORY VARCHAR2(255),
	CF_SPEC_RES_COLS_ID NUMBER NOT NULL,
	DISP_ORDER NUMBER NOT NULL,
		CONSTRAINT PK_CF_SPEC_RES_COLS
			PRIMARY KEY (CF_SPEC_RES_COLS_ID)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;
