CREATE TABLE CF_TEMP_CONT_EDIT (
	KEY NUMBER NOT NULL,
	BARCODE VARCHAR2(60),
	PARENT_BARCODE VARCHAR2(60),
	CONTAINER_TYPE VARCHAR2(60),
	LABEL VARCHAR2(60),
	DESCRIPTION VARCHAR2(60),
	REMARKS VARCHAR2(60),
	WIDTH NUMBER,
	HEIGHT NUMBER,
	LENGTH NUMBER,
	NUMBER_POSITIONS NUMBER,
	CONTAINER_ID NUMBER,
	PARENT_CONTAINER_ID NUMBER,
	STATUS VARCHAR2(255)
) TABLESPACE UAM_DAT_1;
