CREATE TABLE CF_TEMP_CITATION (
	KEY NUMBER,
	PUBLICATION_TITLE VARCHAR2(4000),
	PUBLICATION_ID NUMBER,
	INSTITUTION_ACRONYM VARCHAR2(6),
	COLLECTION_CDE VARCHAR2(5),
	OTHER_ID_TYPE VARCHAR2(60),
	OTHER_ID_NUMBER VARCHAR2(60),
	COLLECTION_OBJECT_ID NUMBER,
	CITED_SCIENTIFIC_NAME VARCHAR2(60),
	CITED_TAXON_NAME_ID NUMBER,
	OCCURS_PAGE_NUMBER NUMBER,
	TYPE_STATUS VARCHAR2(60),
	CITATION_REMARKS VARCHAR2(255),
	STATUS VARCHAR2(255)
) TABLESPACE UAM_DAT_1;
