CREATE TABLE CF_TEMP_LOAN_ITEM (
	KEY NUMBER NOT NULL,
	INSTITUTION_ACRONYM VARCHAR2(5) NOT NULL,
	COLLECTION_CDE VARCHAR2(5) NOT NULL,
	OTHER_ID_TYPE VARCHAR2(30) NOT NULL,
	OTHER_ID_NUMBER VARCHAR2(30) NOT NULL,
	PART_NAME VARCHAR2(30) NOT NULL,
	SUBSAMPLE VARCHAR2(3) NOT NULL,
	ITEM_DESCRIPTION VARCHAR2(255),
	ITEM_REMARKS VARCHAR2(255),
	LOAN_NUMBER VARCHAR2(30) NOT NULL,
	PARTID NUMBER,
	TRANSACTION_ID NUMBER,
	STATUS VARCHAR2(255)
) TABLESPACE UAM_DAT_1;
