CREATE TABLE CF_TEMP_ATTRIBUTES (
	KEY NUMBER NOT NULL,
	OTHER_ID_TYPE VARCHAR2(60),
	OTHER_ID_NUMBER VARCHAR2(60),
	ATTRIBUTE VARCHAR2(60),
	ATTRIBUTE_VALUE VARCHAR2(60),
	ATTRIBUTE_UNITS VARCHAR2(60),
	ATTRIBUTE_DATE VARCHAR2(60),
	ATTRIBUTE_METH VARCHAR2(255),
	DETERMINER VARCHAR2(60),
	REMARKS VARCHAR2(255),
	COLLECTION_CDE VARCHAR2(5),
	COLLECTION_OBJECT_ID NUMBER,
	INSTITUTION_ACRONYM VARCHAR2(20),
	DETERMINED_BY_AGENT_ID NUMBER,
	STATUS VARCHAR2(255),
		CONSTRAINT PK_CF_TEMP_ATTRIBUTES
			PRIMARY KEY (KEY)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;
