CREATE TABLE CF_TEMP_SCANS (
	KEY NUMBER,
	COLLECTION_OBJECT_ID NUMBER,
	PART_NAME VARCHAR2(60),
	BARCODE VARCHAR2(60),
	PARENT_BARCODE VARCHAR2(60),
	PRINT_FLAG NUMBER,
	PROBLEM VARCHAR2(4000)
) TABLESPACE UAM_DAT_1;
