CREATE TABLE CF_TEMP_BL_RELATIONS (
	KEY NUMBER NOT NULL,
	INSTITUTION_ACRONYM VARCHAR2(6) NOT NULL,
	COLLECTION_CDE VARCHAR2(5) NOT NULL,
	OTHER_ID_TYPE VARCHAR2(255) NOT NULL,
	OTHER_ID_VAL VARCHAR2(255) NOT NULL,
	RELATIONSHIP VARCHAR2(255) NOT NULL,
	RELATED_INSTITUTION_ACRONYM VARCHAR2(6) NOT NULL,
	RELATED_COLLECTION_CDE VARCHAR2(6) NOT NULL,
	RELATED_OTHER_ID_TYPE VARCHAR2(255) NOT NULL,
	RELATED_OTHER_ID_VAL VARCHAR2(255) NOT NULL,
	COLLECTION_OBJECT_ID NUMBER,
	RELATED_COLLECTION_OBJECT_ID NUMBER,
	VALIDATED_STATUS VARCHAR2(255)
) TABLESPACE UAM_DAT_1;
