CREATE TABLE CF_USER_LOAN (
	USER_LOAN_ID NUMBER NOT NULL,
	USER_ID NUMBER NOT NULL,
	IS_ACTIVE NUMBER NOT NULL,
	PROJECT_TITLE VARCHAR2(255),
	PROJECT_DESCRIPTION VARCHAR2(4000)
) TABLESPACE UAM_DAT_1;
