CREATE TABLE CF_USER_LOG (
	IP VARCHAR2(30),
	HOST VARCHAR2(255),
	FORM VARCHAR2(255),
	DATESTAMP DATE,
	USERNAME VARCHAR2(60),
	COLLECTIONS VARCHAR2(100),
	NUMRECORDS NUMBER
) TABLESPACE UAM_DAT_1;
