/*
CTABUNDANCE
CTACCN_STATUS
CTACCN_TYPE
CTADDR_TYPE
CTAGENT_NAME_TYPE
CTAGENT_RANK
CTAGENT_RELATIONSHIP
CTAGENT_TYPE
CTAGE_CLASS
CTATTRIBUTE_CODE_TABLES
CTATTRIBUTE_TYPE
CTAUTHOR_ROLE
CTBIOL_RELATIONS
CTBORROW_STATUS
CTCASTE
CTCATALOGED_ITEM_TYPE
CTCF_LOAN_USE_TYPE
CTCITATION_TYPE_STATUS
CTCLASS
CTCOLLECTING_SOURCE
CTCOLLECTION_CDE
CTCOLLECTOR_ROLE
CTCOLL_CONTACT_ROLE
CTCOLL_OBJECT_TYPE
CTCOLL_OBJ_DISP
CTCOLL_OTHER_ID_TYPE
CTCONTAINER_TYPE
CTCONTAINER_TYPE_SIZE
CTCONTINENT
CTDATUM
CTDEPTH_UNITS
CTDOWNLOAD_PURPOSE
CTELECTRONIC_ADDR_TYPE
CTENCUMBRANCE_ACTION
CTEW
CTFEATURE
CTFLAGS
CTFLUID_CONCENTRATION
CTFLUID_TYPE
CTGEOG_SOURCE_AUTHORITY
CTGEOREFMETHOD
CTIMAGE_OBJECT_TYPE
CTINFRASPECIFIC_RANK
CTISLAND_GROUP
CTJOURNAL_NAME
CTKILL_METHOD
CTLAT_LONG_ERROR_UNITS
CTLAT_LONG_REF_SOURCE
CTLAT_LONG_UNITS
CTLENGTH_UNITS
CTLOAN_STATUS
CTLOAN_TYPE
CTMEDIA_LABEL
CTMEDIA_RELATIONSHIP
CTMEDIA_TYPE
CTMIME_TYPE
CTMONETARY_UNITS
CTNATURE_OF_ID
CTNOMENCLATURAL_CODE
CTNS
CTNUMERIC_AGE_UNITS
CTORIG_ELEV_UNITS
CTPERMIT_TYPE
CTPREFIX
CTPROJECT_AGENT_ROLE
CTPUBLICATION_ATTRIBUTE
CTPUBLICATION_TYPE
CTSECTION_TYPE
CTSEX_CDE
CTSHIPPED_CARRIER_METHOD
CTSPECIMEN_PART_LIST_ORDER
CTSPECIMEN_PART_MODIFIER
CTSPECIMEN_PART_NAME
CTSPECIMEN_PRESERV_METHOD
CTSUFFIX
CTTAXA_FORMULA
CTTAXONOMIC_AUTHORITY
CTTAXON_RELATION
CTTAXON_VARIABLE
CTTRANSACTION_TYPE
CTTRANS_AGENT_ROLE
CTVERIFICATIONSTATUS
CTWEIGHT_UNITS
*/

CREATE TABLE CTABUNDANCE (
	COLLECTION_CDE VARCHAR2(5) NOT NULL,
	ABUNDANCE VARCHAR2(60) NOT NULL,
		CONSTRAINT PK_CTABUNDANCE
			PRIMARY KEY (COLLECTION_CDE, ABUNDANCE)
			USING INDEX TABLESPACE UAM_IDX_1,
		CONSTRAINT FK_CTABUNDANCE
			FOREIGN KEY (COLLECTION_CDE)
			REFERENCES CTCOLLECTION_CDE (COLLECTION_CDE)
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTACCN_STATUS (
	ACCN_STATUS VARCHAR2(20) NOT NULL,
		CONSTRAINT PK_CTACCN_STATUS
			PRIMARY KEY (ACCN_STATUS)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTACCN_TYPE (
	ACCN_TYPE VARCHAR2(35) NOT NULL,
		CONSTRAINT PK_CTACCN_TYPE
			PRIMARY KEY (ACCN_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTADDR_TYPE (
	ADDR_TYPE VARCHAR2(20),
		CONSTRAINT PK_CTADDR_TYPE
			PRIMARY KEY (ADDR_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTAGENT_NAME_TYPE (
	AGENT_NAME_TYPE VARCHAR2(40) NOT NULL,
		CONSTRAINT PK_CTAGENT_NAME_TYPE
			PRIMARY KEY (AGENT_NAME_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTAGENT_RANK (
	AGENT_RANK VARCHAR2(50),
	DESCRIPTION VARCHAR2(4000),
		CONSTRAINT PK_CTAGENT_RANK
			PRIMARY KEY (AGENT_RANK)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTAGENT_RELATIONSHIP (
	AGENT_RELATIONSHIP VARCHAR2(18) NOT NULL,
		CONSTRAINT PK_CTAGENT_RELATIONSHIP
			PRIMARY KEY (AGENT_RELATIONSHIP)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTAGENT_TYPE (
	AGENT_TYPE VARCHAR2(30) NOT NULL,
		CONSTRAINT PK_CTAGENT_TYPE
			PRIMARY KEY (AGENT_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTAGE_CLASS (
	AGE_CLASS VARCHAR2(21) NOT NULL,
	COLLECTION_CDE VARCHAR2(5) NOT NULL,
	DESCRIPTION VARCHAR2(4000),
		CONSTRAINT PK_CTAGE_CLASS
			PRIMARY KEY (AGE_CLASS, COLLECTION_CDE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTATTRIBUTE_CODE_TABLES (
	ATTRIBUTE_TYPE VARCHAR2(60) NOT NULL,
	VALUE_CODE_TABLE VARCHAR2(60),
	UNITS_CODE_TABLE VARCHAR2(60),
		CONSTRAINT PK_CTATTRIBUTE_CODE_TABLES
			PRIMARY KEY (ATTRIBUTE_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTATTRIBUTE_TYPE (
	ATTRIBUTE_TYPE VARCHAR2(60) NOT NULL,
	COLLECTION_CDE VARCHAR2(5) NOT NULL,
	DESCRIPTION VARCHAR2(4000),
		CONSTRAINT PK_CTATTRIBUTE_TYPE
			PRIMARY KEY (ATTRIBUTE_TYPE, COLLECTION_CDE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTAUTHOR_ROLE (
	AUTHOR_ROLE VARCHAR2(60),
		CONSTRAINT PK_CTAUTHOR_ROLE
			PRIMARY KEY (AUTHOR_ROLE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTBIOL_RELATIONS (
	BIOL_INDIV_RELATIONSHIP VARCHAR2(18) NOT NULL,
	DESCRIPTION VARCHAR2(4000),
		CONSTRAINT PK_CTBIOL_RELATIONS
			PRIMARY KEY (BIOL_INDIV_RELATIONSHIP)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTBORROW_STATUS (
	BORROW_STATUS VARCHAR2(20) NOT NULL,
		CONSTRAINT PK_CTBORROW_STATUS
			PRIMARY KEY (BORROW_STATUS)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTCASTE (
	COLLECTION_CDE VARCHAR2(5),
	CASTE VARCHAR2(60),
		CONSTRAINT PK_CTCASTE
			PRIMARY KEY (COLLECTION_CDE, CASTE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTCATALOGED_ITEM_TYPE (
	CATALOGED_ITEM_TYPE CHAR(2),
	DESCRIPTION VARCHAR2(4000),
		CONSTRAINT PK_CTCATALOGED_ITEM_TYPE
			PRIMARY KEY (CATALOGED_ITEM_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTCF_LOAN_USE_TYPE (
	USE_TYPE VARCHAR2(30),
		CONSTRAINT PK_CTCF_LOAN_USE_TYPE
			PRIMARY KEY (USE_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTCITATION_TYPE_STATUS (
	TYPE_STATUS VARCHAR2(60) NOT NULL,
	DESCRIPTION VARCHAR2(4000),
		CONSTRAINT PK_CTCITATION_TYPE_STATUS
			PRIMARY KEY (TYPE_STATUS)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTCLASS (
	PHYLCLASS VARCHAR2(20),
	DESCRIPTION VARCHAR2(4000),
		CONSTRAINT PK_CTCLASS
			PRIMARY KEY (PHYLCLASS)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTCOLLECTING_SOURCE (
	COLLECTING_SOURCE VARCHAR2(30),
		CONSTRAINT PK_CTCOLLECTING_SOURCE
			PRIMARY KEY (COLLECTING_SOURCE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTCOLLECTION_CDE (
	COLLECTION_CDE VARCHAR2(5) NOT NULL,
		CONSTRAINT PK_CTCOLLECTION_CDE
			PRIMARY KEY (COLLECTION_CDE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTCOLLECTOR_ROLE (
	COLLECTOR_ROLE CHAR(1) NOT NULL,
		CONSTRAINT PK_CTCOLLECTOR_ROLE
			PRIMARY KEY (COLLECTOR_ROLE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTCOLL_CONTACT_ROLE (
	CONTACT_ROLE VARCHAR2(60) NOT NULL,
		CONSTRAINT PK_CTCOLL_CONTACT_ROLE
			PRIMARY KEY (CONTACT_ROLE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTCOLL_OBJECT_TYPE (
	COLL_OBJECT_TYPE CHAR(2) NOT NULL,
		CONSTRAINT PK_CTCOLL_OBJECT_TYPE
			PRIMARY KEY (COLL_OBJECT_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTCOLL_OBJ_DISP (
	COLL_OBJ_DISPOSITION VARCHAR2(20) NOT NULL,
		CONSTRAINT PK_CTCOLL_OBJ_DISP
			PRIMARY KEY (COLL_OBJ_DISPOSITION)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTCOLL_OTHER_ID_TYPE (
	OTHER_ID_TYPE VARCHAR2(75) NOT NULL,
	DESCRIPTION VARCHAR2(4000),
	BASE_URL VARCHAR2(4000),
		CONSTRAINT PK_CTCOLL_OTHER_ID_TYPE
			PRIMARY KEY (OTHER_ID_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTCONTAINER_TYPE (
	CONTAINER_TYPE VARCHAR2(20) NOT NULL,
		CONSTRAINT PK_CTCONTAINER_TYPE
			PRIMARY KEY (CONTAINER_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTCONTAINER_TYPE_SIZE (
	CONTAINER_TYPE VARCHAR2(255),
	CONTAINER_SIZE NUMBER,
		CONSTRAINT PK_CTCONTAINER_TYPE_SIZE
			PRIMARY KEY (CONTAINER_TYPE, CONTAINER_SIZE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTCONTINENT (
	CONTINENT_OCEAN VARCHAR2(45) NOT NULL,
		CONSTRAINT PK_CTCONTINENT
			PRIMARY KEY (CONTINENT_OCEAN)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTDATUM (
	DATUM VARCHAR2(55) NOT NULL,
		CONSTRAINT PK_CTDATUM
			PRIMARY KEY (DATUM)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTDEPTH_UNITS (
	DEPTH_UNITS VARCHAR2(20) NOT NULL,
		CONSTRAINT PK_CTDEPTH_UNITS
			PRIMARY KEY (DEPTH_UNITS)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTDOWNLOAD_PURPOSE (
	DOWNLOAD_PURPOSE VARCHAR2(60) NOT NULL,
		CONSTRAINT PK_CTDOWNLOAD_PURPOSE
			PRIMARY KEY (DOWNLOAD_PURPOSE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTELECTRONIC_ADDR_TYPE (
	ADDRESS_TYPE VARCHAR2(25) NOT NULL,
		CONSTRAINT PK_CTELECTRONIC_ADDR_TYPE
			PRIMARY KEY (ADDRESS_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTENCUMBRANCE_ACTION (
	ENCUMBRANCE_ACTION VARCHAR2(30),
		CONSTRAINT PK_CTENCUMBRANCE_ACTION
			PRIMARY KEY (ENCUMBRANCE_ACTION)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTEW (
	E_OR_W CHAR(1) NOT NULL,
		CONSTRAINT PK_CTEW
			PRIMARY KEY (E_OR_W)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTFEATURE (
	FEATURE VARCHAR2(50),
		CONSTRAINT PK_CTFEATURE
			PRIMARY KEY (FEATURE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTFLAGS (
	FLAGS VARCHAR2(20) NOT NULL,
		CONSTRAINT PK_CTFLAGS
			PRIMARY KEY (FLAGS)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTFLUID_CONCENTRATION (
	CONCENTRATION NUMBER(2,2),
		CONSTRAINT PK_CTFLUID_CONCENTRATION
			PRIMARY KEY (CONCENTRATION)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTFLUID_TYPE (
	FLUID_TYPE VARCHAR2(30) NOT NULL,
		CONSTRAINT PK_CTFLUID_TYPE
			PRIMARY KEY (FLUID_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTGEOG_SOURCE_AUTHORITY (
	SOURCE_AUTHORITY VARCHAR2(45) NOT NULL,
		CONSTRAINT PK_CTGEOG_SOURCE_AUTHORITY
			PRIMARY KEY (SOURCE_AUTHORITY)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTGEOREFMETHOD (
	GEOREFMETHOD VARCHAR2(255),
		CONSTRAINT PK_CTGEOREFMETHOD
			PRIMARY KEY (GEOREFMETHOD)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTIMAGE_OBJECT_TYPE (
	IMAGE_TYPE VARCHAR2(11) NOT NULL,
		CONSTRAINT PK_CTIMAGE_OBJECT_TYPE
			PRIMARY KEY (IMAGE_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTINFRASPECIFIC_RANK (
	INFRASPECIFIC_RANK VARCHAR2(20),
		CONSTRAINT PK_CTINFRASPECIFIC_RANK
			PRIMARY KEY (INFRASPECIFIC_RANK)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTISLAND_GROUP (
	ISLAND_GROUP VARCHAR2(50) NOT NULL,
		CONSTRAINT PK_CTISLAND_GROUP
			PRIMARY KEY (ISLAND_GROUP)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTJOURNAL_NAME (
	JOURNAL_NAME VARCHAR2(150) NOT NULL,
		CONSTRAINT PK_CTJOURNAL_NAME
			PRIMARY KEY (JOURNAL_NAME)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTKILL_METHOD (
	KILL_METHOD VARCHAR2(20) NOT NULL,
	COLLECTION_CDE VARCHAR2(5) NOT NULL,
		CONSTRAINT PK_CTKILL_METHOD
			PRIMARY KEY (KILL_METHOD, COLLECTION_CDE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTLAT_LONG_ERROR_UNITS (
	LAT_LONG_ERROR_UNITS VARCHAR2(2),
		CONSTRAINT PK_CTLAT_LONG_ERROR_UNITS
			PRIMARY KEY (LAT_LONG_ERROR_UNITS)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTLAT_LONG_REF_SOURCE (
	LAT_LONG_REF_SOURCE VARCHAR2(255) NOT NULL,
		CONSTRAINT PK_CTLAT_LONG_REF_SOURCE
			PRIMARY KEY (LAT_LONG_REF_SOURCE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTLAT_LONG_UNITS (
	ORIG_LAT_LONG_UNITS VARCHAR2(20) NOT NULL,
		CONSTRAINT PK_CTLAT_LONG_UNITS
			PRIMARY KEY (ORIG_LAT_LONG_UNITS)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTLENGTH_UNITS (
	LENGTH_UNITS VARCHAR2(2) NOT NULL,
		CONSTRAINT PK_CTLENGTH_UNITS
			PRIMARY KEY (LENGTH_UNITS)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTLOAN_STATUS (
	LOAN_STATUS VARCHAR2(20) NOT NULL,
		CONSTRAINT PK_CTLOAN_STATUS
			PRIMARY KEY (LOAN_STATUS)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTLOAN_TYPE (
	LOAN_TYPE VARCHAR2(25) NOT NULL,
		CONSTRAINT PK_CTLOAN_TYPE
			PRIMARY KEY (LOAN_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTMEDIA_LABEL (
	MEDIA_LABEL VARCHAR2(255) NOT NULL,
	DESCRIPTION VARCHAR2(4000),
		CONSTRAINT PK_CTMEDIA_LABEL
			PRIMARY KEY (MEDIA_LABEL)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTMEDIA_RELATIONSHIP (
	MEDIA_RELATIONSHIP VARCHAR2(40) NOT NULL,
		CONSTRAINT PK_CTMEDIA_RELATIONSHIP
			PRIMARY KEY (MEDIA_RELATIONSHIP)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTMEDIA_TYPE (
	MEDIA_TYPE VARCHAR2(40) NOT NULL,
	DESCRIPTION VARCHAR2(4000),
		CONSTRAINT PK_CTMEDIA_TYPE
			PRIMARY KEY (MEDIA_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTMIME_TYPE (
	MIME_TYPE VARCHAR2(40) NOT NULL,
	DESCRIPTION VARCHAR2(4000) NOT NULL,
		CONSTRAINT PK_CTMIME_TYPE
			PRIMARY KEY (MIME_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTMONETARY_UNITS (
	MONETARY_UNITS VARCHAR2(30) NOT NULL)
TABLESPACE UAM_DAT_1;

CREATE TABLE CTNATURE_OF_ID (
	NATURE_OF_ID VARCHAR2(35) NOT NULL,
	DESCRIPTION VARCHAR2(4000),
		CONSTRAINT PK_CTNATURE_OF_ID
			PRIMARY KEY (NATURE_OF_ID)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTNOMENCLATURAL_CODE (
	NOMENCLATURAL_CODE VARCHAR2(10) NOT NULL,
		CONSTRAINT PK_CTNOMENCLATURAL_CODE
			PRIMARY KEY (NOMENCLATURAL_CODE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTNS (
	N_OR_S CHAR(1) NOT NULL,
		CONSTRAINT PK_CTNS
			PRIMARY KEY (N_OR_S)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTNUMERIC_AGE_UNITS (
	NUMERIC_AGE_UNITS VARCHAR2(6) NOT NULL,
		CONSTRAINT PK_CTNUMERIC_AGE_UNITS
			PRIMARY KEY (NUMERIC_AGE_UNITS)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTORIG_ELEV_UNITS (
	ORIG_ELEV_UNITS VARCHAR2(2) NOT NULL,
		CONSTRAINT PK_CTORIG_ELEV_UNITS
			PRIMARY KEY (ORIG_ELEV_UNITS)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTPERMIT_TYPE (
	PERMIT_TYPE VARCHAR2(50) NOT NULL,
		CONSTRAINT PK_CTPERMIT_TYPE
			PRIMARY KEY (PERMIT_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTPREFIX (
	PREFIX VARCHAR2(20) NOT NULL,
		CONSTRAINT PK_CTPREFIX
			PRIMARY KEY (PREFIX)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTPROJECT_AGENT_ROLE (
	PROJECT_AGENT_ROLE VARCHAR2(25) NOT NULL,
		CONSTRAINT PK_CTPROJECT_AGENT_ROLE
			PRIMARY KEY (PROJECT_AGENT_ROLE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTPUBLICATION_ATTRIBUTE (
	PUBLICATION_ATTRIBUTE VARCHAR2(60) NOT NULL,
	DESCRIPTION VARCHAR2(4000),
	CONTROL VARCHAR2(40),
		CONSTRAINT PK_CTPUBLICATION_ATTRIBUTE
			PRIMARY KEY (PUBLICATION_ATTRIBUTE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTPUBLICATION_TYPE (
	PUBLICATION_TYPE VARCHAR2(21) NOT NULL,
		CONSTRAINT PK_CTPUBLICATION_TYPE
			PRIMARY KEY (PUBLICATION_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTSECTION_TYPE (
	FIELD_NOTE_SECT_TYPE VARCHAR2(30) NOT NULL,
		CONSTRAINT PK_CTSECTION_TYPE
			PRIMARY KEY (FIELD_NOTE_SECT_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTSEX_CDE (
	SEX_CDE VARCHAR2(20) NOT NULL,
	COLLECTION_CDE VARCHAR2(5) NOT NULL,
		CONSTRAINT PK_CTSEX_CDE
			PRIMARY KEY (SEX_CDE, COLLECTION_CDE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTSHIPPED_CARRIER_METHOD (
	SHIPPED_CARRIER_METHOD VARCHAR2(30) NOT NULL,
		CONSTRAINT PK_CTSHIPPED_CARRIER_METHOD
			PRIMARY KEY (SHIPPED_CARRIER_METHOD
)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTSPECIMEN_PART_LIST_ORDER (
	PARTNAME VARCHAR2(255) NOT NULL,
	LIST_ORDER NUMBER NOT NULL,
		CONSTRAINT PK_CTSPECIMEN_PART_LIST_ORDER
			PRIMARY KEY (PARTNAME, LIST_ORDER)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTSPECIMEN_PART_MODIFIER (
	PART_MODIFIER VARCHAR2(60) NOT NULL,
		CONSTRAINT PK_CTSPECIMEN_PART_MODIFIER
			PRIMARY KEY (PART_MODIFIER)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTSPECIMEN_PART_NAME (
	PART_NAME VARCHAR2(70) NOT NULL,
	COLLECTION_CDE VARCHAR2(5) NOT NULL,
	DESCRIPTION VARCHAR2(4000),
		CONSTRAINT PK_CTSPECIMEN_PART_NAME
			PRIMARY KEY (PART_NAME, COLLECTION_CDE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTSPECIMEN_PRESERV_METHOD (
	PRESERVE_METHOD VARCHAR2(30) NOT NULL,
	COLLECTION_CDE VARCHAR2(5) NOT NULL,
	DESCRIPTION VARCHAR2(4000),
		CONSTRAINT PK_CTSPECIMEN_PRESERV_METHOD
			PRIMARY KEY (COLLECTION_CDE, PRESERVE_METHOD)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTSUFFIX (
	SUFFIX VARCHAR2(20) NOT NULL,
		CONSTRAINT PK_CTSUFFIX
			PRIMARY KEY (SUFFIX)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTTAXA_FORMULA (
	TAXA_FORMULA VARCHAR2(25) NOT NULL,
	DESCRIPTION VARCHAR2(4000),
		CONSTRAINT PK_CTTAXA_FORMULA
			PRIMARY KEY (TAXA_FORMULA)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTTAXONOMIC_AUTHORITY (
	SOURCE_AUTHORITY VARCHAR2(45) NOT NULL,
	DESCRIPTION VARCHAR2(4000),
		CONSTRAINT PK_CTTAXONOMIC_AUTHORITY
			PRIMARY KEY (SOURCE_AUTHORITY)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTTAXON_RELATION (
	TAXON_RELATIONSHIP VARCHAR2(40) NOT NULL,
	DESCRIPTION VARCHAR2(4000),
		CONSTRAINT PK_CTTAXON_RELATION
			PRIMARY KEY (TAXON_RELATIONSHIP)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTTAXON_VARIABLE (
	TAXON_VARIABLE CHAR(1) NOT NULL,
		CONSTRAINT PK_CTTAXON_VARIABLE
			PRIMARY KEY (TAXON_VARIABLE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTTRANSACTION_TYPE (
	TRANSACTION_TYPE VARCHAR2(18) NOT NULL,
		CONSTRAINT PK_CTTRANSACTION_TYPE
			PRIMARY KEY (TRANSACTION_TYPE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTTRANS_AGENT_ROLE (
	TRANS_AGENT_ROLE VARCHAR2(60) NOT NULL,
	DESCRIPTION VARCHAR2(4000),
		CONSTRAINT PK_CTTRANS_AGENT_ROLE
			PRIMARY KEY (TRANS_AGENT_ROLE)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTVERIFICATIONSTATUS (
	VERIFICATIONSTATUS VARCHAR2(40),
	DESCRIPTION VARCHAR2(4000),
		CONSTRAINT PK_CTVERIFICATIONSTATUS
			PRIMARY KEY (VERIFICATIONSTATUS)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTWEIGHT_UNITS (
	WEIGHT_UNITS VARCHAR2(15) NOT NULL,
		CONSTRAINT PK_CTWEIGHT_UNITS
			PRIMARY KEY (WEIGHT_UNITS)
			USING INDEX TABLESPACE UAM_IDX_1
) TABLESPACE UAM_DAT_1;

CREATE TABLE CTYES_NO (
	YES_OR_NO VARCHAR2(3),
		CONSTRAINT PK_CTYES_NO
			PRIMARY KEY (YES_OR_NO)
			USING INDEX TABLESPACE UAM_IDX_1)
TABLESPACE UAM_DAT_1;
