/*
 Keep ALL flat and filtered_flat indexes organized here

*/





CREATE UNIQUE INDEX PK_FILTERED_FLAT ON FILTERED_FLAT (COLLECTION_OBJECT_ID) TABLESPACE UAM_IDX_1;

alter index PK_FILTERED_FLAT rebuild;

CREATE INDEX IX_FILTERED_FLAT_BEGANDATE	ON FILTERED_FLAT (BEGAN_DATE) TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_BEGANDATE_YEAR ON FILTERED_FLAT (substr(began_date,1,4))	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_CATNUM ON FILTERED_FLAT (CAT_NUM) TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_COLLECTIONID
	ON FILTERED_FLAT (COLLECTION_ID)
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_COLLECTORS
	ON FILTERED_FLAT (COLLECTORS)
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_ENDEDDATE ON FILTERED_FLAT (ENDED_DATE)	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_ENDEDDATE_YEAR
	ON FILTERED_FLAT (substr(ENDED_DATE,1,4))
	TABLESPACE UAM_IDX_1;


CREATE INDEX IX_F_FLAT_IDENTIFICATIONID
	ON FILTERED_FLAT (IDENTIFICATION_ID)
	TABLESPACE UAM_IDX_1;


CREATE INDEX IX_F_FLAT_COLLEVENTID
	ON FILTERED_FLAT (COLLECTING_EVENT_ID)
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_CONTINENTOCEAN_UPR
	ON FILTERED_FLAT (UPPER(CONTINENT_OCEAN))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_COUNTRY_UPR
	ON FILTERED_FLAT (UPPER(COUNTRY))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_COUNTY_UPR
	ON FILTERED_FLAT (UPPER(COUNTY))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_FEATURE_UPR
	ON FILTERED_FLAT (UPPER(FEATURE))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_HIGHER_GEOG_UPR
	ON FILTERED_FLAT (UPPER(HIGHER_GEOG))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_ISLAND_UPR
	ON FILTERED_FLAT (UPPER(ISLAND))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_ISLANDGROUP_UPR
	ON FILTERED_FLAT (UPPER(ISLAND_GROUP))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_LOCALITYID
	ON FILTERED_FLAT (LOCALITY_ID)
	TABLESPACE UAM_IDX_1;
	

CREATE INDEX IX_FLAT_LOCALITYID
	ON FLAT (LOCALITY_ID)
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_PARTS_UPR
	ON FILTERED_FLAT (UPPER(PARTS))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_QUAD_UPR
	ON FILTERED_FLAT (UPPER(QUAD))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_SCIENTIFICNAME_UPR
	ON FILTERED_FLAT (UPPER(SCIENTIFIC_NAME))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_SEA_UPR
	ON FILTERED_FLAT (UPPER(SEA))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_SPECLOCALITY_UPR
	ON FILTERED_FLAT (UPPER(SPEC_LOCALITY))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_STATEPROV_UPR ON FLAT (UPPER(STATE_PROV))	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_TYPESTATUS_UPR
	ON FILTERED_FLAT (UPPER(TYPESTATUS))
	TABLESPACE UAM_IDX_1;

	
	drop index IU_F_FLAT_GUID_UPR;
	
CREATE UNIQUE INDEX IU_F_FLAT_GUID ON FILTERED_FLAT (upper(GUID)) TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_COUNTRY
	ON FILTERED_FLAT (COUNTRY)
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_DEC_LAT
    ON FILTERED_FLAT (DEC_LAT)
    TABLESPACE UAM_IDX_1;

CREATE INDEX ID_F_FLAT_DEC_LONG ON FILTERED_FLAT (DEC_LONG)  TABLESPACE UAM_IDX_1;

drop index IX_UPR_F_FLAT_ACCN;

CREATE INDEX IX_U_FLAT_ACCN ON FLAT (accession)  TABLESPACE UAM_IDX_1;
CREATE INDEX IX_U_FLAT_ACCN ON FLAT (accession)  TABLESPACE UAM_IDX_1;


CREATE INDEX IX_U_F_FLAT_ACCN ON FILTERED_FLAT (accession)  TABLESPACE UAM_IDX_1;
CREATE INDEX IX_UPR_F_FLAT_ACCN ON FILTERED_FLAT (upper(accession))  TABLESPACE UAM_IDX_1;

CREATE INDEX IX_U_F_FLAT_ACCNID ON FILTERED_FLAT (accn_id)  TABLESPACE UAM_IDX_1;
CREATE INDEX IX_U_FLAT_ACCNID ON FLAT (accn_id)  TABLESPACE UAM_IDX_1;


CREATE INDEX IX_f_FLAT_U_CATNUM ON FILTERED_FLAT (upper(cat_num))  TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_SCIENTIFICNAME ON FILTERED_FLAT (scientific_name)  TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_U_PORDER ON FILTERED_FLAT (upper(phylorder))  TABLESPACE UAM_IDX_1;
CREATE INDEX IX_F_FLAT_U_KINGDOM ON FILTERED_FLAT (upper(kingdom))  TABLESPACE UAM_IDX_1;
CREATE INDEX IX_F_FLAT_U_PHYLUM ON FILTERED_FLAT (upper(phylum))  TABLESPACE UAM_IDX_1;
CREATE INDEX IX_F_FLAT_U_CLASS ON FILTERED_FLAT (upper(phylclass))  TABLESPACE UAM_IDX_1;
CREATE INDEX IX_F_FLAT_U_FAMILY ON FILTERED_FLAT (upper(family))  TABLESPACE UAM_IDX_1;
CREATE INDEX IX_F_FLAT_U_GENUS ON FILTERED_FLAT (upper(genus))  TABLESPACE UAM_IDX_1;

CREATE INDEX IF_F_FLAT_SPEC_LOC ON FILTERED_FLAT (spec_locality)  TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_GUID ON FILTERED_FLAT (guid)  TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_MONTH ON FILTERED_FLAT (month)  TABLESPACE UAM_IDX_1;
CREATE INDEX IX_F_FLAT_STALEFLAG ON FILTERED_FLAT (STALE_FLAG)  TABLESPACE UAM_IDX_1;

CREATE INDEX IX_f_FLAT_U_CATNUM ON FILTERED_FLAT (upper(cat_num))  TABLESPACE UAM_IDX_1;

drop index IX_F_FLAT_U_CATNUM;
drop index IX_F_FLAT_U_GENUS;


select * from all_ind_columns where table_name='FLAT' ;


select index_name,column_name from all_ind_columns where table_name='FLAT' and column_name not in (
	select column_name from all_ind_columns where table_name='FILTERED_FLAT'
);





select * from all_ind_columns where table_name='FILTERED_FLAT' and column_name like '%ACCESSION%';
drop index IX_U_F_FLAT_ACCN;
CREATE INDEX IX_F_UPR_FLAT_ACCN ON FILTERED_FLAT (upper(ACCESSION))  TABLESPACE UAM_IDX_1;





-- drop all filtered_flat indexes

select 'drop index ' ||  index_name || ';' from all_ind_columns where table_name='FILTERED_FLAT';

drop index IU_F_FLAT_GUID;
drop index IX_F_FLAT_HASTISSUES;
drop index IX_U_F_FLAT_ACCNIF;
drop index IX_F_FLAT_ISLAND_UPR;
drop index IX_F_FLAT_MONTH;
drop index IX_F_FLAT_CONTINENTOCEAN_UPR;
drop index IX_F_FLAT_COUNTRY_UPR;
drop index IX_F_FLAT_COUNTY_UPR;
drop index IX_F_FLAT_FEATURE_UPR;
drop index IX_F_FLAT_HIGHER_GEOG_UPR;
drop index IX_F_FLAT_ISLANDGROUP_UPR;
drop index IX_F_FLAT_PARTS_UPR;
drop index IX_F_FLAT_QUAD_UPR;
drop index IX_F_FLAT_SCIENTIFICNAME_UPR;
drop index IX_F_FLAT_SEA_UPR;
drop index IX_F_FLAT_SPECLOCALITY_UPR;
drop index IX_F_FLAT_TYPESTATUS_UPR;
drop index IX_F_FLAT_U_PORDER;
drop index IX_F_FLAT_U_KINGDOM;
drop index IX_F_FLAT_U_PHYLUM;
drop index IX_F_FLAT_U_CLASS;
drop index IX_F_FLAT_U_FAMILY;
drop index IX_F_FLAT_CATNUM;
drop index IX_F_FLAT_COLLECTIONID;
drop index IX_F_FLAT_COLLECTORS;
drop index IX_F_FLAT_ENDEDDATE;
drop index IX_F_FLAT_IDENTIFICATIONID;
drop index IX_F_FLAT_COLLEVENTID;
drop index IX_F_FLAT_LOCALITYID;
drop index IX_F_FLAT_COUNTRY;
drop index IX_F_FLAT_DEC_LAT;
drop index ID_F_FLAT_DEC_LONG;
drop index IX_F_FLAT_SCIENTIFICNAME;
drop index IF_F_FLAT_SPEC_LOC;
drop index IX_F_FLAT_GUID;
drop index IX_F_FLAT_BEGANDATE_YEAR;
drop index PK_FILTERED_FLAT;
drop index IX_FILTERED_FLAT_BEGANDATE;
drop index IX_F_FLAT_ENDEDDATE_YEAR;


-- get all indexes from flat
SELECT DBMS_METADATA.get_ddl ('INDEX', index_name)
	FROM   all_indexes
	WHERE   table_name = 'FLAT';

	

  CREATE INDEX "UAM"."IX_F_FLAT_HASTISSUES" ON "UAM"."FILTERED_FLAT" ("HAS_TISSUES") TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_ISLAND_UPR" ON "UAM"."FILTERED_FLAT" (UPPER("ISLAND")) TABLESPACE "UAM_IDX_1"  ;

  CREATE INDEX "UAM"."IX_F_FLAT_ISLANDGROUP_UPR" ON "UAM"."FILTERED_FLAT" (UPPER("ISLAND_GROUP")) TABLESPACE "UAM_IDX_1"  ;

  CREATE INDEX "UAM"."IX_F_FLAT_PARTS_UPR" ON "UAM"."FILTERED_FLAT" (UPPER("PARTS"))   TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_QUAD_UPR" ON "UAM"."FILTERED_FLAT" (UPPER("QUAD"))  TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_SCIENTIFICNAME_UPR" ON "UAM"."FILTERED_FLAT" (UPPER("SCIENTIFIC_NAME")) TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_SEA_UPR" ON "UAM"."FILTERED_FLAT" (UPPER("SEA")) TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_STATEPROV_UPR" ON "UAM"."FILTERED_FLAT" (UPPER("STATE_PROV"))  TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_TYPESTATUS_UPR" ON "UAM"."FILTERED_FLAT" (UPPER("TYPESTATUS")) TABLESPACE "UAM_IDX_1";

  CREATE UNIQUE INDEX "UAM"."IU_F_FLAT_GUID_UPR" ON "UAM"."FILTERED_FLAT" (UPPER("GUID")) TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_U_F_FLAT_ACCNID" ON "UAM"."FILTERED_FLAT" ("ACCN_ID") TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_U_PORDER" ON "UAM"."FILTERED_FLAT" (UPPER("PHYLORDER")) TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_U_KINGDOM" ON "UAM"."FILTERED_FLAT" (UPPER("KINGDOM")) TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_U_PHYLUM" ON "UAM"."FILTERED_FLAT" (UPPER("PHYLUM")) TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_U_CLASS" ON "UAM"."FILTERED_FLAT" (UPPER("PHYLCLASS")) TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_U_FAMILY" ON "UAM"."FILTERED_FLAT" (UPPER("FAMILY")) TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_U_GENUS" ON "UAM"."FILTERED_FLAT" (UPPER("GENUS")) TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_U_CATNUM" ON "UAM"."FILTERED_FLAT" (UPPER("CAT_NUM")) TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_UPR_F_FLAT_ACCN" ON "UAM"."FILTERED_FLAT" (UPPER("ACCESSION")) TABLESPACE "UAM_IDX_1";

  CREATE UNIQUE INDEX "UAM"."PK_F_FLAT" ON "UAM"."FILTERED_FLAT" ("COLLECTION_OBJECT_ID") TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_CATNUM" ON "UAM"."FILTERED_FLAT" ("CAT_NUM") TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_COLLECTIONID" ON "UAM"."FILTERED_FLAT" ("COLLECTION_ID")  TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_COLLECTORS" ON "UAM"."FILTERED_FLAT" ("COLLECTORS")  TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_IDENTIFICATIONID" ON "UAM"."FILTERED_FLAT" ("IDENTIFICATION_ID") TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_STALEFLAG" ON "UAM"."FILTERED_FLAT" ("STALE_FLAG")  TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_COLLEVENTID" ON "UAM"."FILTERED_FLAT" ("COLLECTING_EVENT_ID")  TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_LOCALITYID" ON "UAM"."FILTERED_FLAT" ("LOCALITY_ID") TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."FLAT_F_COUNTRY" ON "UAM"."FILTERED_FLAT" ("COUNTRY") TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."FLAT_F_DEC_LAT" ON "UAM"."FILTERED_FLAT" ("DEC_LAT") TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."FLAT_F_DEC_LONG" ON "UAM"."FILTERED_FLAT" ("DEC_LONG") TABLESPACE "UAM_IDX_1";
  CREATE INDEX "UAM"."FLAT_F_SPEC_LOC" ON "UAM"."FILTERED_FLAT" ("SPEC_LOCALITY") TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_GUID" ON "UAM"."FILTERED_FLAT" ("GUID") TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_SCIENTIFICNAME" ON "UAM"."FILTERED_FLAT" ("SCIENTIFIC_NAME") TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_YEAR" ON "UAM"."FILTERED_FLAT" ("YEAR") TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_MONTH" ON "UAM"."FILTERED_FLAT" ("MONTH") TABLESPACE "UAM_IDX_1";
  
  CREATE INDEX "UAM"."IX_F_FLAT_DAY" ON "UAM"."FILTERED_FLAT" ("DAY") TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_GEOGAUTHRECID" ON "UAM"."FILTERED_FLAT" ("GEOG_AUTH_REC_ID")  TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_CONTINENTOCEAN_UPR" ON "UAM"."FILTERED_FLAT" (UPPER("CONTINENT_OCEAN")) TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_COUNTRY_UPR" ON "UAM"."FILTERED_FLAT" (UPPER("COUNTRY")) TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_COUNTY_UPR" ON "UAM"."FILTERED_FLAT" (UPPER("COUNTY")) TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_F_FLAT_FEATURE_UPR" ON "UAM"."FILTERED_FLAT" (UPPER("FEATURE")) TABLESPACE "UAM_IDX_1";



  CREATE INDEX "UAM"."IX_F_FLAT_HIGHER_GEOG_UPR" ON "UAM"."FILTERED_FLAT" (UPPER("HIGHER_GEOG")) TABLESPACE "UAM_IDX_1";

  CREATE INDEX "UAM"."IX_UPR_F_FLAT_ACCN" ON "UAM"."FILTERED_FLAT" (UPPER("ACCESSION")) TABLESPACE "UAM_IDX_1";
drop index IX_UPR_F_FLAT_ACCN;

  CREATE INDEX "UAM"."IX_F_FLAT_YEAR" ON "UAM"."FILTERED_FLAT" ("YEAR") TABLESPACE "UAM_IDX_1";


IX_FLAT_YEAR
YEAR
drop index IX_F_FLAT_U_FAMILY;
  CREATE INDEX "UAM"."IX_F_FLAT_U_FAMILY" ON "UAM"."FILTERED_FLAT" (UPPER("FAMILY")) TABLESPACE "UAM_IDX_1";

  
  
IX_FLAT_U_FAMILY
SYS_NC00142$

  CREATE INDEX "UAM"."IX_F_FLAT_DAY" ON "UAM"."FILTERED_FLAT" ("DAY") TABLESPACE "UAM_IDX_1";

IX_FLAT_DAY
DAY

  CREATE INDEX "UAM"."IX_F_FLAT_GEOGAUTHRECID" ON "UAM"."FILTERED_FLAT" ("GEOG_AUTH_REC_ID")  TABLESPACE "UAM_IDX_1";

IX_FLAT_GEOGAUTHRECID
GEOG_AUTH_REC_ID

CREATE INDEX IX_f_FLAT_U_CATNUM ON FILTERED_FLAT (upper(cat_num))  TABLESPACE UAM_IDX_1;

drop index IX_f_FLAT_U_CATNUM
 CREATE INDEX "UAM"."IX_FLAT_U_CATNUM" ON "UAM"."FLAT" (UPPER("CAT_NUM")) TABLESPACE "UAM_IDX_1";
