/*
 Keep ALL flat and filtered_flat indexes organized here

*/





CREATE UNIQUE INDEX PK_FILTERED_FLAT ON FILTERED_FLAT (COLLECTION_OBJECT_ID) TABLESPACE UAM_IDX_1;

CREATE INDEX IX_FILTERED_FLAT_BEGANDATE	ON FILTERED_FLAT (BEGAN_DATE) TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_BEGANDATE_YEAR ON FILTERED_FLAT (substr(began_date,1,4))	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_CATNUM ON FILTERED_FLAT (CAT_NUM) TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_COLLECTIONID
	ON FILTERED_FLAT (COLLECTION_ID)
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_COLLECTORS
	ON FILTERED_FLAT (COLLECTORS)
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_ENDEDDATE
	ON FILTERED_FLAT (ENDED_DATE)
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_ENDEDDATE_YEAR
	ON FILTERED_FLAT (substr(ENDED_DATE,1,4))
	TABLESPACE UAM_IDX_1;


CREATE INDEX IX_F_FLAT_IDENTIFICATIONID
	ON FILTERED_FLAT (IDENTIFICATION_ID)
	TABLESPACE UAM_IDX_1;


CREATE INDEX IX_F_FLAT_COLLEVENTID
	ON FILTERED_FLAT (COLLECTING_EVENT_ID)
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_CONTINENTOCEAN_UPR
	ON FILTERED_FLAT (UPPER(CONTINENT_OCEAN))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_COUNTRY_UPR
	ON FILTERED_FLAT (UPPER(COUNTRY))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_COUNTY_UPR
	ON FILTERED_FLAT (UPPER(COUNTY))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_FEATURE_UPR
	ON FILTERED_FLAT (UPPER(FEATURE))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_HIGHER_GEOG_UPR
	ON FILTERED_FLAT (UPPER(HIGHER_GEOG))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_ISLAND_UPR
	ON FILTERED_FLAT (UPPER(ISLAND))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_ISLANDGROUP_UPR
	ON FILTERED_FLAT (UPPER(ISLAND_GROUP))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_LOCALITYID
	ON FILTERED_FLAT (LOCALITY_ID)
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_PARTS_UPR
	ON FILTERED_FLAT (UPPER(PARTS))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_QUAD_UPR
	ON FILTERED_FLAT (UPPER(QUAD))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_SCIENTIFICNAME_UPR
	ON FILTERED_FLAT (UPPER(SCIENTIFIC_NAME))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_SEA_UPR
	ON FILTERED_FLAT (UPPER(SEA))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_SPECLOCALITY_UPR
	ON FILTERED_FLAT (UPPER(SPEC_LOCALITY))
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_STATEPROV_UPR ON FLAT (UPPER(STATE_PROV))	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_TYPESTATUS_UPR
	ON FILTERED_FLAT (UPPER(TYPESTATUS))
	TABLESPACE UAM_IDX_1;

	
	drop index IU_F_FLAT_GUID_UPR;
	
CREATE UNIQUE INDEX IU_F_FLAT_GUID ON FILTERED_FLAT (upper(GUID)) TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_COUNTRY
	ON FILTERED_FLAT (COUNTRY)
	TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_DEC_LAT
    ON FILTERED_FLAT (DEC_LAT)
    TABLESPACE UAM_IDX_1;

CREATE INDEX ID_F_FLAT_DEC_LONG ON FILTERED_FLAT (DEC_LONG)  TABLESPACE UAM_IDX_1;

drop index IX_UPR_F_FLAT_ACCN;

CREATE INDEX IX_U_F_FLAT_ACCN ON FILTERED_FLAT (accession)  TABLESPACE UAM_IDX_1;
CREATE INDEX IX_UPR_F_FLAT_ACCN ON FILTERED_FLAT (upper(accession))  TABLESPACE UAM_IDX_1;

CREATE INDEX IX_U_F_FLAT_ACCNID ON FILTERED_FLAT (accn_id)  TABLESPACE UAM_IDX_1;
CREATE INDEX IX_U_FLAT_ACCNID ON FLAT (accn_id)  TABLESPACE UAM_IDX_1;


CREATE INDEX IX_f_FLAT_U_CATNUM ON FILTERED_FLAT (upper(cat_num))  TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_SCIENTIFICNAME ON FILTERED_FLAT (scientific_name)  TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_U_PORDER ON FILTERED_FLAT (upper(phylorder))  TABLESPACE UAM_IDX_1;
CREATE INDEX IX_F_FLAT_U_KINGDOM ON FILTERED_FLAT (upper(kingdom))  TABLESPACE UAM_IDX_1;
CREATE INDEX IX_F_FLAT_U_PHYLUM ON FILTERED_FLAT (upper(phylum))  TABLESPACE UAM_IDX_1;
CREATE INDEX IX_F_FLAT_U_CLASS ON FILTERED_FLAT (upper(phylclass))  TABLESPACE UAM_IDX_1;
CREATE INDEX IX_F_FLAT_U_FAMILY ON FILTERED_FLAT (upper(family))  TABLESPACE UAM_IDX_1;
CREATE INDEX IX_F_FLAT_U_GENUS ON FILTERED_FLAT (upper(genus))  TABLESPACE UAM_IDX_1;

CREATE INDEX IF_F_FLAT_SPEC_LOC ON FILTERED_FLAT (spec_locality)  TABLESPACE UAM_IDX_1;

CREATE INDEX IX_F_FLAT_GUID ON FILTERED_FLAT (guid)  TABLESPACE UAM_IDX_1;

